### ISSUE TITLE
table info - the count of upload data is 0

### ISSUE THREAD

**Issue by rxt2012kc** [FederatedAI/FATE#1055]
when I deployed the cluster version, and test the min_test_task as follow codes:
```
source /data/projects/fate/init_env.sh
cd /data/projects/fate/python/examples/min_test_task/
sh run.sh host fast 
```
I meet a problem that **the count of upload data is 0**, the console is outputed as follows. I don't know how to handle with this problem.
```
(venv) [app@hadoop-slave1 min_test_task]$ sh run.sh host fast
role is host
task is fast
upload_task, table_name:host_table_name_1583256848_2084
upload_task, namespace:host_table_namespace_1583256848_2084
Upload data config json: {'file': '/data/projects/fate/python/examples/min_test_task/../data/breast_a.csv', 'head': 1, 'partition': 10, 'work_mode': 1, 'table_name': 'host_table_name_1583256848_2084', 'namespace': 'host_table_namespace_1583256848_2084'}
Start task: ['python', '/data/projects/fate/python/examples/min_test_task/../../fate_flow/fate_flow_client.py', '-f', 'upload', '-c', '/data/projects/fate/python/examples/min_test_task/test/upload_host.config_1583256848_3983']
Upload output is {'data': {'board_url': 'http://192.168.1.192:8080/index.html#/dashboard?job_id=2020030401340924436620&role=local&party_id=0', 'job_dsl_path': '/data/projects/fate/python/jobs/2020030401340924436620/job_dsl.json', 'job_runtime_conf_path': '/data/projects/fate/python/jobs/2020030401340924436620/job_runtime_conf.json', 'logs_directory': '/data/projects/fate/python/logs/2020030401340924436620', 'namespace': 'host_table_namespace_1583256848_2084', 'table_name': 'host_table_name_1583256848_2084'}, 'jobId': '2020030401340924436620', 'retcode': 0, 'retmsg': 'success'}
Start task: ['python', '/data/projects/fate/python/examples/min_test_task/../../fate_flow/fate_flow_client.py', '-f', 'table_info', '-t', 'host_table_name_1583256848_2084', '-n', 'host_table_namespace_1583256848_2084']
{'data': {'count': 0, 'namespace': 'host_table_namespace_1583256848_2084', 'partition': 1, 'table_name': 'host_table_name_1583256848_2084'}, 'retcode': 0, 'retmsg': 'success'}
Upload Data, role: host, count: {'data': {'count': 0, 'namespace': 'host_table_namespace_1583256848_2084', 'partition': 1, 'table_name': 'host_table_name_1583256848_2084'}, 'retcode': 0, 'retmsg': 'success'}
The table name and namespace is needed by GUEST. To start a modeling task, please inform GUEST with the table name and namespace.
finish upload intersect data
*********************
*******finish!*******
```

**Comment by zhihuiwan** [comment]
Hello, you can check if there is an error message in ‘/data/projects/fate/python/logs/2020030401340924436620/local/0' or '/data/projects/fate/python/logs/fate_flow/ERROR.log'

**Comment by rxt2012kc** [comment]
The error log showed as follows:
```
  self.on_connect()
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/redis/connection.py", line 570, in on_connect
    if nativestr(self.read_response()) != 'OK':
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/redis/connection.py", line 638, in read_response
    raise response
redis.exceptions.ResponseError: Client sent AUTH, but no password is set
"2020-03-03 00:00:45,731 - data_access_app.py[line:32] - ERROR: push job into queue failed"
Traceback (most recent call last):
  File "/data/projects/fate/python/fate_flow/driver/job_controller.py", line 98, in submit_job
    RuntimeConfig.JOB_QUEUE.put_event(job_event)
  File "/data/projects/fate/python/fate_flow/manager/queue_manager.py", line 80, in put_event
    raise e
  File "/data/projects/fate/python/fate_flow/manager/queue_manager.py", line 75, in put_event
    ret = conn.lpush(self.queue_name, json.dumps(event))
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/redis/client.py", line 1554, in lpush
    return self.execute_command('LPUSH', name, *values)
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/redis/client.py", line 754, in execute_command
    connection.send_command(*args)
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/redis/connection.py", line 619, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/redis/connection.py", line 594, in send_packed_command
    self.connect()
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/redis/connection.py", line 502, in connect
    self.on_connect()
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/redis/connection.py", line 570, in on_connect
    if nativestr(self.read_response()) != 'OK':
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/redis/connection.py", line 638, in read_response
    raise response
redis.exceptions.ResponseError: Client sent AUTH, but no password is set
```
The redis process is showed as follows:
```
[app@hadoop-slave1 fate_flow]$ ps aux|grep redis
app       98604  0.0  0.0 112712   964 pts/1    S+   18:14   0:00 grep --color=auto redis
app      183604  0.1  0.0 153884  3300 pts/1    Sl   01:33   1:10 /data/projects/fate/common/redis/redis-5.0.2/bin/redis-server 0.0.0.0:6379
```
I don't know how to do next to deal with the redis problem, thanks very much

**Comment by rxt2012kc** [comment]
I restart the fate_flow module, it solve the problem. Thanks very much
