### ISSUE TITLE
starting fate_flow failed

### ISSUE THREAD

**Issue by xq92** [FederatedAI/FATE#1083]
I install Fate Cluster follow this guide：https://github.com/FederatedAI/FATE/blob/master/cluster-deploy/doc/Fate-cluster_deployment_guide_install_zh.md. 

When I come to 6.1，I run sh services.sh fate_flow start ，every model is started successfully but fate_flow. The error shows:

Traceback (most recent call last):
File "/home/data/projects/fate/python/fate_flow/fate_flow_server.py", line 93, in
session.init(mode=RuntimeConfig.WORK_MODE, backend=Backend.EGGROLL)
File "/home/data/projects/fate/python/arch/api/session.py", line 52, in init
session = build_session(job_id=job_id, work_mode=mode, backend=backend)
File "/home/data/projects/fate/python/arch/api/table/session.py", line 38, in build_session
session = session_impl.FateSessionImpl(eggroll_session, work_mode, persistent_engine)
File "/home/data/projects/fate/python/arch/api/table/eggroll/session_impl.py", line 33, in init
self._eggroll = eggroll_util.build_eggroll_runtime(work_mode=work_mode, eggroll_session=eggroll_session)
File "/home/data/projects/fate/python/arch/api/table/eggroll_util.py", line 44, in build_eggroll_runtime
return eggroll_init(eggroll_session)
File "/home/data/projects/fate/eggroll/python/eggroll/api/cluster/eggroll.py", line 79, in eggroll_init
eggroll_runtime = _EggRoll(eggroll_session=eggroll_session)
File "/home/data/projects/fate/eggroll/python/eggroll/api/cluster/eggroll.py", line 364, in init
self.session_stub.getOrCreateSession(self.eggroll_session.to_protobuf())
File "/home/data/projects/fate/common/python/venv/lib/python3.6/site-packages/grpc/_channel.py", line 533, in call
return _end_unary_response_blocking(state, call, False, None)
File "/home/data/projects/fate/common/python/venv/lib/python3.6/site-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking
raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
status = StatusCode.UNAVAILABLE
details = "OS Error"
debug_error_string = "{"created":"@1583482449.752061606","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"OS Error","grpc_status":14}"

I reinstall the EGGROLL module. And I restart the EGGROLL module successfully, but failed in checking the status ,just shown as this :
![image](https://user-images.githubusercontent.com/46565839/76181132-57cbc600-617d-11ea-8f7a-d81193624d8e.png)

What can I do to solve this issue?

**Comment by xq92** [comment]
I reinstall the EGGROLL module. And I restart the EGGROLL module successfully, but failed in checking the status ,just shown as this :
![image](https://user-images.githubusercontent.com/46565839/76182024-7b444000-6180-11ea-8e6c-35f6fdb51a4f.png)

**Comment by xq92** [comment]
And I restart the EGGROLL module successfully, but failed in checking the status ,it shows" service not running".
