### ISSUE TITLE
在主机中进行单机部署错误：service not running

### ISSUE THREAD

**Issue by zl3633** [FederatedAI/FATE#1174]
在主机中进行FATE单机部署，执行‘’source init.sh init“时，出现如下问题：

service.sh: 66: service.sh: [[: not found
service not running
service.sh: 48: service.sh: [[: not found
service already started. pid:
service.sh: 38: service.sh: [[: not found
service not running
service.sh: 33: service.sh: [[: not found
service.sh: 79: service.sh: [[: not found
service not running
service.sh: 33: service.sh: [[: not found
service.sh: 60: service.sh: [[: not found
service already started. pid:
service.sh: 33: service.sh: [[: not found
service.sh: 48: service.sh: [[: not found
service not running

之后在执行“bash ./federatedml/test/run_test.sh”时，有一个任务失败，重复出现如下error：

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fml_test/fate_standalone/standalone-fate-master-1.3.1/federatedml/test/../feature/test/sampler_test.py", line 138, in test_upsample
    sample_data, sample_ids = sampler.sample(self.table)
  File "/home/fml_test/fate_standalone/standalone-fate-master-1.3.1/federatedml/feature/sampler.py", line 233, in sample
    new_data_inst, sample_ids = self.__sample(data_inst)
  File "/home/fml_test/fate_standalone/standalone-fate-master-1.3.1/federatedml/feature/sampler.py", line 367, in __sample
    callback(self.tracker, "stratified", callback_sample_metrics, callback_original_metrics)
  File "/home/fml_test/fate_standalone/standalone-fate-master-1.3.1/federatedml/feature/sampler.py", line 562, in callback
    callback_metrics)
  File "/home/fml_test/fate_standalone/standalone-fate-master-1.3.1/fate_flow/manager/tracking.py", line 61, in log_metric_data
    job_level=False)
  File "/home/fml_test/fate_standalone/standalone-fate-master-1.3.1/fate_flow/manager/tracking.py", line 83, in save_metric_data_remote
    json_body=request_body)
  File "/home/fml_test/fate_standalone/standalone-fate-master-1.3.1/fate_flow/utils/api_utils.py", line 88, in local_api
    raise Exception('local request error: {}'.format(e))
_Exception: local request error: HTTPConnectionPool(host='192.168.203.23', port=9380): Max retries exceeded with url: /v1/tracking/jobid/pipeline/jobid_pipeline/guest/9999/metric_data/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4a08d9f860>: Failed to establish a new connection: [Errno 111] Connection refused'))_

请问该如何解决？

**Comment by zl3633** [comment]
netstat -apln|grep 8080
netstat -apln|grep 9360
netstat -apln|grep 9380

ports均没有占用

**Comment by zl3633** [comment]
补充一下：
netstat -apln|grep 8080
netstat -apln|grep 9360
netstat -apln|grep 9380

ports均没有占用

**Comment by uestcbean** [comment]
According to the error log: 

`service.sh: 48: service.sh: [[: not found`

I am guessing that if you set your defalut shell to bash and the problem would be fixed.
