### ISSUE TITLE
单机部署时训练超过7k的数据量在hetero-lr组件会出现lmdb.Error

### ISSUE THREAD

**Issue by ShiyaNiu** [FederatedAI/FATE#1699]
**Describe the bug**
使用fate-1.4.2在单机部署时更换进行示例的训练时，小于7k的数据量都可以成功训练和测试，但是更换为大于7k的数据量时在hetero-lr-0组件failed，出现lmdb.Error：mdb_txn_commit:Input/output error 。但是我查看了服务器磁盘空间足够。这应该是什么原因造成的？我使用的数据集是fate/data/default_credit_hetero_guest.csv和default_credit_hetero_host.csv.

>- task_executor.py[line:144]: mdb_txn_commit: Input/output error 
concurrent.futures.process._RemoteTraceback:  
""" 
Traceback (most recent call last): 
  File "/usr/local/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker 
    r = call_item.fn(*call_item.args, **call_item.kwargs) 
  File "/fate/arch/standalone/standalone/eggroll.py", line 343, in do_join 
    dst_txn.put(k_bytes, serialize(v3)) 
lmdb.Error: mdb_txn_commit: Input/output error 
"""   
  The above exception was the direct cause of the following exception:
 Traceback (most recent call last): 
 File "/fate/fate_flow/driver/task_executor.py", line 135, in run_task 
    run_object.run(component_parameters, task_run_args) 
File "/fate/federatedml/model_base.py", line 91, in run 
    this_data_output = func(*params)
File "/fate/federatedml/linear_model/logistic_regression/hetero_logistic_regression/hetero_lr_guest.py", line 77, in fit
    self.fit_binary(data_instances, validate_data)
File "/fate/federatedml/linear_model/logistic_regression/hetero_logistic_regression/hetero_lr_guest.py", line 123, in fit_binary
    batch_index
File "/fate/federatedml/optim/gradient/hetero_linear_model_gradient.py", line 177, in compute_gradient_procedure
    model_weights.fit_intercept)
 File "/fate/federatedml/optim/gradient/hetero_linear_model_gradient.py", line 112, in compute_gradient 
    lambda d, g: (d.features, g))
File "/fate/arch/api/utils/profile_util.py", line 32, in _fn 
    rtn = func(*args, **kwargs) 
  File "/fate/arch/api/impl/based_1x/table.py", line 140, in join 
    return DTable(self._dtable.join(other._dtable, func=func), session_id=self._session_id) 
  File "/fate/arch/standalone/standalone/eggroll.py", line 840, in join 
    result = r.result() 
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 425, in result 
    return self.__get_result() 
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result 
    raise self._exception 
lmdb.Error: mdb_txn_commit: Input/output error

运行配置文件算法参数如下：
>- {'HeteroLogisticParam': {'penalty': 'L2', 'tol': 0.0001, 'alpha': 0.01, 'optimizer': 'nesterov_momentum_sgd', 'batch_size': -1, 'learning_rate': 0.15, 'init_param': {'init_method': 'random_uniform', 'init_const': 1, 'fit_intercept': True, 'random_seed': None}, 'max_iter': 30, 'early_stop': 'weight_diff', 'encrypt_param': {'method': 'Paillier', 'key_length': 1024}, 'predict_param': {'threshold': 0.5}, 
'cv_param': {'n_splits': 5, 'mode': 'hetero', 'role': 'guest', 'shuffle': False, 'random_seed': 103, 'need_cv': False}, 'decay': 1, 'decay_sqrt': True, 'multi_class': 'ovr', 'validation_freqs': None, 'stepwise_param': {'score_name': 'AIC', 'mode': 'hetero', 'role': 'guest', 'direction': 'both', 'max_step': 10, 'nvmin': 2, 'nvmax': None, 'need_stepwise': False}, 'early_stopping_rounds': None, 'metrics': ['auc', 'ks'], 'use_first_metric_only': False, 'encrypted_mode_calculator_param': {'mode': 'strict', 're_encrypted_rate': 1}, 
'sqn_param': {'update_interval_L': 3, 'memory_M': 5, 'sample_size': 5000, 'random_seed': None}}, 'initiator': {'role': 'guest', 'party_id': 10000}, 'job_parameters': {'work_mode': 0, 'model_id': 'arbiter-10000#guest-10000#host-10000#model', 'model_version': '20200813032518087622203'}, 'role': {'guest': [10000], 'host': [10000], 'arbiter': [10000]}, 'config': '/fate/examples/federatedml-1.x-examples/hetero_logistic_regression/test_hetero_lr_train_job_conf.json', 'dsl': 'federatedml-1.x-examples/hetero_logistic_regression/test_hetero_lr_train_job_dsl.json', 'function': 'submit_job', 'local': {'role': 'guest', 'party_id': 10000}, 'CodePath': 'federatedml/linear_model/logistic_regression/hetero_logistic_regression/hetero_lr_guest.py/HeteroLRGuest', 'module': 'HeteroLR'}

**Comment by Yuchen-Li** [comment]
虽然不太清楚具体原因，但是看这个报错会不会是eggroll的容器空间不够导致的呢？

**Comment by ShiyaNiu** [comment]
I find it's my own fault because I solved the problem after rebuilding the  software environment.

**Comment by Junyi-99** [comment]
I am also facing this problem when using Docker.
