### ISSUE TITLE
自定义算法的时候，上传错误脚本的缓存好像无法清空

### ISSUE THREAD

**Issue by JianhuanZeng** [FederatedAI/FATE#1983]
**Describe the bug**
自定义算法运行的时候，在第 1 步：定义此模块将使用的参数对象的时候填错了，修改过后，运行还是报原来的错误，怀疑是缓存的原因。如何清除，运行更新后的参数对象脚本？

**To Reproduce**
```
# 第一次，粗心写错了
[ERROR] [2020-09-25 06:32:31,022] [9:140147291039488] - job_app.py[line:37]: name 'GMMParam' is not defined
Traceback (most recent call last):
  File "/data/projects/python/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/projects/python/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/projects/python/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/projects/python/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/data/projects/python/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/projects/python/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/data/projects/fate/python/fate_flow/apps/job_app.py", line 46, in submit_job
    job_id, job_dsl_path, job_runtime_conf_path, logs_directory, model_info, board_url = JobController.submit_job(request.json)
  File "/data/projects/fate/python/fate_flow/driver/job_controller.py", line 94, in submit_job
    train_runtime_conf=train_runtime_conf)
  File "/data/projects/fate/python/fate_flow/utils/job_utils.py", line 190, in get_job_dsl_parser
    mode=job_type)
  File "/data/projects/fate/python/fate_flow/driver/dsl_parser.py", line 642, in run
    self._init_component_setting(setting_conf_prefix, self.runtime_conf, default_runtime_conf_prefix)
  File "/data/projects/fate/python/fate_flow/driver/dsl_parser.py", line 165, in _init_component_setting
    name)
  File "/data/projects/fate/python/fate_flow/utils/parameter_util.py", line 41, in override_parameter
    param_obj = getattr(param_module, param_class)()
  File "/data/projects/fate/python/federatedml/param/hetero_gmm_param.py", line 78, in __init__
    super(GMMParam, self).__init__()
NameError: name 'GMMParam' is not defined

# 第二次，修改后，还是报第一次的错，但是最后一行super那里已经改过来了
[ERROR] [2020-09-25 07:04:01,956] [9:140147291039488] - job_app.py[line:37]: name 'GMMParam' is not defined
Traceback (most recent call last):
  File "/data/projects/python/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/projects/python/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/projects/python/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/projects/python/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/data/projects/python/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/projects/python/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/data/projects/fate/python/fate_flow/apps/job_app.py", line 46, in submit_job
    job_id, job_dsl_path, job_runtime_conf_path, logs_directory, model_info, board_url = JobController.submit_job(request.json)
  File "/data/projects/fate/python/fate_flow/driver/job_controller.py", line 94, in submit_job
    train_runtime_conf=train_runtime_conf)
  File "/data/projects/fate/python/fate_flow/utils/job_utils.py", line 190, in get_job_dsl_parser
    mode=job_type)
  File "/data/projects/fate/python/fate_flow/driver/dsl_parser.py", line 642, in run
    self._init_component_setting(setting_conf_prefix, self.runtime_conf, default_runtime_conf_prefix)
  File "/data/projects/fate/python/fate_flow/driver/dsl_parser.py", line 165, in _init_component_setting
    name)
  File "/data/projects/fate/python/fate_flow/utils/parameter_util.py", line 41, in override_parameter
    param_obj = getattr(param_module, param_class)()
  File "/data/projects/fate/python/federatedml/param/hetero_gmm_param.py", line 78, in __init__
    super(HeteroGMMParam, self).__init__()
NameError: name 'GMMParam' is not defined
```

**Additional context**

**Comment by weiwee** [comment]
try restart fateflow service
