### ISSUE TITLE
ValueError: features shape 2219 not equal to header shape 2746

### ISSUE THREAD

**Issue by Yao544303** [FederatedAI/FATE#2320]
**Describe the bug**
The data on host is 6270067 lines ,with 2747 columns,  i have checked it with spark 
<img width="80" alt="图片" src="https://user-images.githubusercontent.com/6713442/98915713-3a69ab80-2505-11eb-9c32-5cce3a809eb5.png">

but when i run hetero_lr ,the data_io on guest is success, but on host is failed, the log on guest 
```
[INFO] [2020-11-12 01:00:11,887] [9:140579414800128] - task_scheduler.py[line:394]: job 2020111200590322008164 component dataio_0 run on guest 9998 status is success
[INFO] [2020-11-12 01:00:11,891] [9:140579414800128] - task_scheduler.py[line:394]: job 2020111200590322008164 component dataio_0 run on host 10000 status is running
[INFO] [2020-11-12 01:00:11,922] [9:140575313811200] - job_controller.py[line:158]: job 2020111200590322008164 component dataio_0 host 10000 status failed
```

the error log on host ： 
```
==== detail start, at 20201112.0900xxx.xxx ====
104 Traceback (most recent call last):
105 File "./fate/eggroll/python/eggroll/core/utils.py", line 147, in wrapper
106 return func(*args, **kw)
107 File "./fate/eggroll/python/eggroll/roll_pair/egg_pair.py", line 227, in run_task
108 self._run_unary(map_values_wrapper, task)
109 File "./fate/eggroll/python/eggroll/roll_pair/egg_pair.py", line 113, in _run_unary
110 func(rb, key_serdes, value_serdes, wb)
111 File "./fate/eggroll/python/eggroll/roll_pair/egg_pair.py", line 226, in map_values_wrapper
112 output_writebatch.put(k_bytes, value_serdes.serialize(f(v)))
113 File "./fate/python/federatedml/util/data_io.py", line 244, in <lambda>
114 data_instance = input_data_features.mapValues(lambda features: self.to_instance(features))
115 File "./fate/python/federatedml/util/data_io.py", line 252, in to_instance
116 raise ValueError("features shape {} not equal to header shape {}".format(len(features), len(self.header)))
117 ValueError: features shape 2219 not equal to header shape 2746
118 
119 During handling of the above exception, another exception occurred:
120 
121 Traceback (most recent call last):
122 File "./fate/eggroll/python/eggroll/core/utils.py", line 147, in wrapper
123 return func(*args, **kw)
124 File "./fate/eggroll/python/eggroll/core/command/command_service.py", line 33, in call
125 kwargs=getattr(command_request, '_kwargs'))
126 File "./fate/eggroll/python/eggroll/core/command/command_router.py", line 94, in dispatch
127 raise e
128 File "./fate/eggroll/python/eggroll/core/command/command_router.py", line 91, in dispatch
129 call_result = _method(_instance, *deserialized_args)
130 File "./fate/eggroll/python/eggroll/core/utils.py", line 154, in wrapper
131 raise RuntimeError(msg)
132 RuntimeError: 
133 

```
is there any limition  for the data size ?

**Comment by Yonggie** [comment]
There's a chance that there's a blank line in the data, and FATE cannot handle that as a "skip line".
