### ISSUE TITLE
使用1.5.0 All in one 部署FATE集群，Mysqld无法启动【2003, "Can't connect to MySQL server】

### ISSUE THREAD

**Issue by SennriSyunnga** [FederatedAI/FATE#2325]
环境：ubuntu18
原本已安装过mysqld，手动停止了原mysql的服务。

在执行`deploy.sh`时，遇到了这样的提示：
```bash
java -XX:+UseG1GC -XX:+PrintGCDetails -XX:+PrintGCDateStamps -Xloggc:logs/eggroll/rollsite.gc.log -Dlog4j.configurationFile=/data/projects/fate/eggroll/conf/log4j2.properties -cp /data/projects/fate/eggroll/lib/*: com.webank.eggroll.core.Bootstrap --bootstraps com.webank.eggroll.rollsite.EggSiteBootstrap -c /data/projects/fate/eggroll/conf/eggroll.properties -p 9370 -s eggroll-host
service start failed
service not running

service not running
service start failed, please check /data/projects/fate/logs/error.log and /data/projects/fate/logs/console.log
service not running
```

errorlog内容如下
```bash
Traceback (most recent call last):
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/pymysql/connections.py", line 583, in connect
    **kwargs)
  File "/data/projects/fate/common/miniconda3/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/data/projects/fate/common/miniconda3/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/peewee.py", line 2817, in connect
    self._state.set_connection(self._connect())
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/playhouse/pool.py", line 155, in _connect
    conn = super(PooledDatabase, self)._connect()
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/peewee.py", line 3642, in _connect
    conn = mysql.connect(db=self.database, **self.connect_params)
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on ''xxx.xxx.xxx.xxx'' ([Errno 111] Connection refused)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/projects/fate/python/fate_flow/fate_flow_server.py", line 91, in <module>
    init_flow_db()
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/peewee.py", line 393, in inner
    with self:
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/peewee.py", line 2724, in __enter__
    self.db.connect()
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/playhouse/pool.py", line 108, in connect
    return super(PooledDatabase, self).connect(reuse_if_open)
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/peewee.py", line 2820, in connect
    self._initialize_connection(self._state.conn)
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/peewee.py", line 2666, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/peewee.py", line 179, in reraise
    raise value.with_traceback(tb)
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/peewee.py", line 2817, in connect
    self._state.set_connection(self._connect())
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/playhouse/pool.py", line 155, in _connect
    conn = super(PooledDatabase, self)._connect()
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/peewee.py", line 3642, in _connect
    conn = mysql.connect(db=self.database, **self.connect_params)
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
peewee.OperationalError: (2003, "Can't connect to MySQL server on ''xxx.xxx.xxx.xxx'' ([Errno 111] Connection refused)")
Traceback (most recent call last):
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/pymysql/connections.py", line 583, in connect
    **kwargs)
  File "/data/projects/fate/common/miniconda3/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/data/projects/fate/common/miniconda3/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/peewee.py", line 2817, in connect
    self._state.set_connection(self._connect())
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/playhouse/pool.py", line 155, in _connect
    conn = super(PooledDatabase, self)._connect()
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/peewee.py", line 3642, in _connect
    conn = mysql.connect(db=self.database, **self.connect_params)
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'xxx.xxx.xxx.xxx' ([Errno 111] Connection refused)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/projects/fate/python/fate_flow/fate_flow_server.py", line 91, in <module>
    init_flow_db()
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/peewee.py", line 393, in inner
    with self:
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/peewee.py", line 2724, in __enter__
    self.db.connect()
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/playhouse/pool.py", line 108, in connect
    return super(PooledDatabase, self).connect(reuse_if_open)
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/peewee.py", line 2820, in connect
    self._initialize_connection(self._state.conn)
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/peewee.py", line 2666, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/peewee.py", line 179, in reraise
    raise value.with_traceback(tb)
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/peewee.py", line 2817, in connect
    self._state.set_connection(self._connect())
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/playhouse/pool.py", line 155, in _connect
    conn = super(PooledDatabase, self)._connect()
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/peewee.py", line 3642, in _connect
    conn = mysql.connect(db=self.database, **self.connect_params)
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
peewee.OperationalError: (2003, "Can't connect to MySQL server on 'xxx.xxx.xxx.xxx' ([Errno 111] Connection refused)")

```
mysqld.log内容如下
```
2020-11-13T09:14:03.945889Z mysqld_safe Logging to '/data/projects/fate/common/mysql/mysql-8.0.13/logs/mysqld.log'.
2020-11-13T09:14:03.994002Z mysqld_safe Starting mysqld daemon with databases from /data/projects/fate/data/mysql
2020-11-13T09:14:04.987046Z 0 [System] [MY-010116] [Server] /data/projects/fate/common/mysql/mysql-8.0.13/bin/mysqld (mysqld 8.0.13) starting as process 10147
2020-11-13T09:14:04.997328Z 0 [Warning] [MY-013242] [Server] --character-set-server: 'utf8' is currently an alias for the character set UTF8MB3, but will be an alias for UTF8MB4 in a future release. Please consider using UTF8MB4 in order to be unambiguous.
2020-11-13T09:14:05.036838Z 1 [ERROR] [MY-011011] [Server] Failed to find valid data directory.
2020-11-13T09:14:05.037345Z 0 [ERROR] [MY-010020] [Server] Data Dictionary initialization failed.
2020-11-13T09:14:05.037399Z 0 [ERROR] [MY-010119] [Server] Aborting
2020-11-13T09:14:05.038999Z 0 [System] [MY-010910] [Server] /data/projects/fate/common/mysql/mysql-8.0.13/bin/mysqld: Shutdown complete (mysqld 8.0.13)  MySQL Community Server - GPL.
2020-11-13T09:14:05.081642Z mysqld_safe mysqld from pid file /data/projects/fate/common/mysql/mysql-8.0.13/run/mysqld.pid ended
```

经检查，在my.cnf里头实际上是有
`basedir=/data/projects/fate/common/mysql/mysql-8.0.13`
`datadir=/data/projects/fate/data/mysql`
经检查该路径存在
ls /data/projects/fate/data/mysql
仅有一个文件`binlog.index`

尝试使用了`sudo bin/mysqld --initialize-insecure --user=xxx`指令,无果。不使用sudo结果相同，没有错误提示，也没有变好。
虽然用户名用的不是app，但是权限是按照前文的要求设置的，并且改动了init和deploy脚本里头
`--user=app`的内容。

**Comment by SennriSyunnga** [comment]
workaround：
apt-get 卸载掉原先安装的mysql
另外后续会因为本机装过openjdk11而再报一个不能启动jvm的错误
卸载后也能暂时解决这个问题

**Comment by KleinXin** [comment]
请问，这里说的All in one是指KubeFATE吗？

**Comment by SennriSyunnga** [comment]
> 请问，这里说的All in one是指KubeFATE吗？

不是，native部署方式。

**Comment by KleinXin** [comment]
> > 请问，这里说的All in one是指KubeFATE吗？
> 
> 不是，native部署方式。

按照cluster方式部署，可以指定每台机器的IP而不是使用系统默认的192.168.0.x的IP吗？
我看部署脚本里还有192.168.0.88和192.168.0.99，是不是至少需要四台机器，才可以配集群？

**Comment by Song-xx** [comment]
你怎么解决的啊，我也遇到同样的问题。

**Comment by SennriSyunnga** [comment]
卸了原装MYSQL，只用集成的。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "WOW"<notifications@github.com&gt;; 
发送时间: 2021年1月12日(星期二) 下午3:47
收件人: "FederatedAI/FATE"<FATE@noreply.github.com&gt;; 
抄送: "倪彧祺"<nnnnnn_2657@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [FederatedAI/FATE] 使用1.5.0 All in one 部署FATE集群，Mysqld无法启动【2003, &quot;Can&#39;t connect to MySQL server】 (#2325)





 
你怎么解决的啊，我也遇到同样的问题。

**Comment by Song-xx** [comment]
> 卸了原装MYSQL，只用集成的。
> […](#)


谢谢回复，不过还是不行啊，还是遇到同样的问题，郁闷啊。

**Comment by Song-xx** [comment]
> > 卸了原装MYSQL，只用集成的。
> > […](#)
> 
> 谢谢回复，不过还是不行啊，还是遇到同样的问题，郁闷啊。

我用的是 kubefate安装多个机器的那种

**Comment by Song-xx** [comment]
> 卸了原装MYSQL，只用集成的。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "WOW"<notifications@github.com&gt;; 发送时间: 2021年1月12日(星期二) 下午3:47 收件人: "FederatedAI/FATE"<FATE@noreply.github.com&gt;; 抄送: "倪彧祺"<nnnnnn_2657@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 主题: Re: [FederatedAI/FATE] 使用1.5.0 All in one 部署FATE集群，Mysqld无法启动【2003, &quot;Can&#39;t connect to MySQL server】 (#2325) 你怎么解决的啊，我也遇到同样的问题。 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

谢谢回复，不过还是不行啊，还是遇到同样的问题，郁闷啊。我用的是kubefate在多个机器上安装的。

**Comment by yumiaoGitHub** [comment]
我遇到了同样的问题：
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on  ‘my ip’  (timed out)")
peewee.OperationalError: (2003, "Can't connect to MySQL server on ‘my ip’  (timed out)")
已经重新卸载mysql 并重新部署安装，查看端口3306正常运行，但是仍出现上述错误。感谢提供解决思路！
![image](https://user-images.githubusercontent.com/17609160/124580809-14718c80-de83-11eb-95c7-b9ce16dcb53f.png)

**Comment by SennriSyunnga** [comment]
> 我遇到了同样的问题：
> pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on ‘my ip’ (timed out)")
> peewee.OperationalError: (2003, "Can't connect to MySQL server on ‘my ip’ (timed out)")
> 已经重新卸载mysql 并重新部署安装，查看端口3306正常运行，但是仍出现上述错误。感谢提供解决思路！
> ![image](https://user-images.githubusercontent.com/17609160/124580809-14718c80-de83-11eb-95c7-b9ce16dcb53f.png)

偶尔也会在部署成功后遇到这类问题
基本上是停止mysqld相关进程、重启服务，懵懵懂懂地恢复了。
不过这里需要强调的是，出现类似问题用service.sh带的stop是不太够的
最好参考一下官方部署文档里用的那些ps -ef清除所有相关进程
