### ISSUE TITLE
多Host环境下模型推送失败

### ISSUE THREAD

**Issue by luyilong2015** [FederatedAI/FATE#2328]
**Describe the bug**
一个FATE1.5版的3节点的环境 ，1个guest，2个host，当完成模型创建后，执行以命令时
python fate_flow_client.py -f load -c examples/my_publish_load_model.json
总会有一个host报错，并且总是在配置文件中的最后一个host出错。
my_publish_load_model.json文件内容如下：
```
{
    "initiator": {
        "party_id": "7777",
        "role": "guest"
    },
    "role": {
        "guest": ["7777"],
        "host": ["18000","6666"],
        "arbiter": ["18000"]
    },
    "job_parameters": {
        "work_mode": 1,
        "model_id": "arbiter-18000#guest-7777#host-6666_18000#model", 
        "model_version": "202011161431553727383"
    }
}

```
报错信息如下：
```
{
    "data": {
        "detail": {
            "guest": {
                "7777": {
                    "retcode": 0,
                    "retmsg": "success"
                }
            },
            "host": {
                "18000": {
                    "retcode": 0,
                    "retmsg": "success"
                },
                "6666": {
                    "retcode": 123,
                    "retmsg": "model initialization error, please check if the model exists and the configuration of the FATEFLOW load model process is correct. "
                }
            }
        },
        "guest": {
            "7777": 0
        },
        "host": {
            "18000": 0,
            "6666": 123
        }
    },
    "jobId": "2020111617395690025527",
    "retcode": 101,
    "retmsg": "failed"
}

```
查看party id 6666的fate-flow日志有以下出错信息
```
[ERROR] [2020-11-16 17:39:57,486] [56661:139690159326976] - model_app.py[line:47]: [Errno 2] No such file or directory: '/data/projects/fate/model_local_cache/host#18000#arbiter-18000#guest-7777#host-6666_18000#model/202011161431553727383/define/define_meta.yaml'
Traceback (most recent call last):
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/data/projects/fate/python/fate_flow/apps/model_app.py", line 274, in transfer_model
    model_data = publish_model.download_model(request.json)
  File "/data/projects/fate/python/fate_flow/pipelined_model/publish_model.py", line 103, in download_model
    model_data = model.collect_models(in_bytes=True)
  File "/data/projects/fate/python/fate_flow/pipelined_model/pipelined_model.py", line 94, in collect_models
    with open(self.define_meta_path, "r", encoding="utf-8") as fr:
FileNotFoundError: [Errno 2] No such file or directory: '/data/projects/fate/model_local_cache/host#18000#arbiter-18000#guest-7777#host-6666_18000#model/202011161431553727383/define/define_meta.yaml'
```
 经查看6666的/data/projects/fate/model_local_cache目录 
的确不存在host#18000#arbiter-18000#guest-7777#host-6666_18000#model
但是存在host#6666#arbiter-18000#guest-7777#host-6666_18000#model
程序在party 6666上却调用属于party 18000的模型文件，造成多host时模型推送失败。

**Comment by 2294930685** [comment]
@luyilong2015 May I ask how you solved it? I also encountered this problem
