### ISSUE TITLE
OSError: federation get None from ('arbiter', 10000) with name HomoNNDefaultTransVar.HasConvergedTransVar.has_converged, tag fit.19

### ISSUE THREAD

**Issue by huisoftware** [FederatedAI/FATE#2373]
两方横向nn，guest是9999，host与arbiter是10000，模型是resnet，大约进行2小时或3小时或4小时，训练会出现题目中bug，反复尝试都会失败，

[ERROR] [2020-11-30 14:55:53,830] [85392:140273748260672] - task_executor.py[line:144]: federation get None from ('arbiter', 10000) with name HomoNNDefaultTransVar.HasConvergedTransVar.has_converged, tag fit.19
Traceback (most recent call last):
  File "/app/projects/fate/python/fate_flow/driver/task_executor.py", line 135, in run_task
    run_object.run(component_parameters, task_run_args)
  File "/app/projects/fate/python/federatedml/model_base.py", line 91, in run
    this_data_output = func(*params)
  File "/app/projects/fate/python/federatedml/nn/homo_nn/enter_point.py", line 189, in fit
    if self._is_converged(data, epoch_degree):
  File "/app/projects/fate/python/federatedml/nn/homo_nn/enter_point.py", line 150, in _is_converged
    is_converged = self.has_converged.get_converge_status(suffix=self._suffix())
  File "/app/projects/fate/python/federatedml/framework/homo/blocks/has_converged.py", line 43, in get_converge_status
    return self._broadcaster.get_parties(parties=self._server_parties, suffix=suffix)[0]
  File "/app/projects/fate/python/federatedml/transfer_variable/base_transfer_variable.py", line 133, in get_parties
    parties=parties)
  File "/app/projects/fate/python/arch/api/impl/based_2x/federation.py", line 78, in get
    raise EnvironmentError(f"federation get None from {party} with name {name}, tag {tag}")
OSError: federation get None from ('arbiter', 10000) with name HomoNNDefaultTransVar.HasConvergedTransVar.has_converged, tag fit.19

![image](https://user-images.githubusercontent.com/25874832/100601701-e3096f00-333d-11eb-91ab-2549e645fe16.png)
![image](https://user-images.githubusercontent.com/25874832/100601757-f61c3f00-333d-11eb-8a18-b32e66812271.png)
![image](https://user-images.githubusercontent.com/25874832/100601782-003e3d80-333e-11eb-80b4-1089ca7ae6e3.png)

报错出现在guest，host与arbiter没有报错
操作系统Red Hat Enterprise 7.5
FATE版本1.4.3
安装方式为普通安装，没有用docker，之前跑训练时间短的一些任务没问题。

**Comment by huisoftware** [comment]
我发现虽然host与arbiter没有报错，但是其日志都终止在guest报错的前3秒
