### ISSUE TITLE
单边测试下任务失败

### ISSUE THREAD

**Issue by sunshine1996** [FederatedAI/FATE#2416]
Traceback (most recent call last):
File "/data/projects/fate/eggroll/python/eggroll/roll_pair/__init__.py", line 30, in create_functor
return cloudpickle.loads(func_bin)
AttributeError: Can't get attribute 'SecureAddGuest.share' on <module 'federatedml.toy_example.secure_add_guest' from '/data/projects/fate/python/federatedml/toy_example/secure_add_guest.py'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/data/projects/fate/eggroll/python/eggroll/core/serdes/eggroll_serdes.py", line 30, in find_class
return super().find_class(module, name)
AttributeError: Can't get attribute 'SecureAddGuest.share' on <module 'federatedml.toy_example.secure_add_guest' from '/data/projects/fate/python/federatedml/toy_example/secure_add_guest.py'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/data/projects/fate/eggroll/python/eggroll/core/utils.py", line 146, in wrapper
return func(*args, **kw)
File "/data/projects/fate/eggroll/python/eggroll/roll_pair/egg_pair.py", line 260, in run_task
f = create_functor(functors[0]._body)
File "/data/projects/fate/eggroll/python/eggroll/roll_pair/__init__.py", line 32, in create_functor
return eggroll_pickle_loads(func_bin)
File "/data/projects/fate/eggroll/python/eggroll/core/serdes/eggroll_serdes.py", line 38, in eggroll_pickle_loads
return up.load()
File "/data/projects/fate/eggroll/python/eggroll/core/serdes/eggroll_serdes.py", line 32, in find_class
return getattr(importlib.import_module(module), name)
AttributeError: module 'federatedml.toy_example.secure_add_guest' has no attribute 'SecureAddGuest.share'

**Comment by sunshine1996** [comment]
我在  /data/projects/fate/eggroll/python/eggroll/core/serdes/eggroll_serdes.py 这个文件里 
加入下列内容就可以了，from federatedml.toy_example.secure_add_guest import SecureAddGuest
