### ISSUE TITLE
lmdb.MemoryError: Cannot allocate memory

### ISSUE THREAD

**Issue by ymsaputra** [FederatedAI/FATE#2643]
I have successfully installed FATE. However, when I try to run sh ./python/federatedml/test/run_test.sh with requiring memory allocation, I always get this kind of error:

Traceback (most recent call last):
  File "/home/Data/standalone-fate-master-1.5.0/python/federatedml/test/../util/test/data_io_test.py", line 279, in setUp
    self.table1 = session.parallelize(self.data, include_key=True, partition=16)
  File "/home/Data/standalone-fate-master-1.5.0/python/fate_arch/session/_session.py", line 277, in parallelize
    return get_latest_opened().computing.parallelize(data, partition=partition, include_key=include_key, **kwargs)
  File "/home/Data/standalone-fate-master-1.5.0/python/fate_arch/computing/standalone/_csession.py", line 54, in parallelize
    table = self._session.parallelize(data=data, partition=partition, include_key=include_key, **kwargs)
  File "/home/Data/standalone-fate-master-1.5.0/python/fate_arch/_standalone.py", line 291, in parallelize
    table.put_all(data)
  File "/home/Data/standalone-fate-master-1.5.0/python/fate_arch/_standalone.py", line 235, in put_all
    env = s.enter_context(self._get_env_for_partition(p, write=True))
  File "/home/Data/standalone-fate-master-1.5.0/python/fate_arch/_standalone.py", line 221, in _get_env_for_partition
    return _get_env(self._namespace, self._name, str(p), write=write)
  File "/home/Data/standalone-fate-master-1.5.0/python/fate_arch/_standalone.py", line 616, in _get_env
    return _open_env(_path, write=write)
  File "/home/Data/standalone-fate-master-1.5.0/python/fate_arch/_standalone.py", line 633, in _open_env
    raise e
  File "/home/Data/standalone-fate-master-1.5.0/python/fate_arch/_standalone.py", line 626, in _open_env
    map_size=10_737_418_240)
lmdb.MemoryError: /home/Data/standalone-fate-master-1.5.0/data/test_dataio_0.630400495002178/ccde6610-82d7-11eb-846e-9522b2cd674b/8: Cannot allocate memory

This also happens for other tests requiring memory allocations. For other tests, it works properly.

How to solve this issue?

**Comment by weiwee** [comment]
from error message, it seems lmdb filled to allocate memory, how many ram and disk you used to deploy `FATE`?

**Comment by ymsaputra** [comment]
Even when I run this simple example "python ./examples/toy_example/run_toy_example.py 10000 10000 0", it also makes a memory allocation error. When I check the system monitor, it is less than 100 MB for running that example. The computer has 88 GB of RAM.

To run FATE, I use virtual env. Does it make any effect?

**Comment by l1nq1** [comment]
Pls how did you solve it
