### ISSUE TITLE
使用自己的数据运行secure boost的二分类模型报错

### ISSUE THREAD

**Issue by ClawSeven** [FederatedAI/FATE#2655]
secure boost在运行6min后突然中断，报错信息如下：
请问是出于什么原因呢？

11
Traceback (most recent call last):
12
  File "./fate/python/fate_flow/operation/task_executor.py", line 174, in run_task
13
    run_object.run(component_parameters_on_party, task_run_args)
14
  File "./fate/python/federatedml/model_base.py", line 98, in run
15
    this_data_output = func(*real_param)
16
  File "./fate/python/federatedml/util/data_io.py", line 894, in transform
17
    return self.reader.read_data(data_inst, "transform")
18
  File "./fate/python/federatedml/util/data_io.py", line 148, in read_data
19
    data_instance = self.transform(input_data_features, input_data_labels)
20
  File "./fate/python/federatedml/util/io_check.py", line 31, in _func
21
    result = func(*args, **kwargs)
22
  File "./fate/python/federatedml/util/data_io.py", line 175, in transform
23
    data_instance = self.gen_data_instance(input_data_features, input_data_labels)
24
  File "./fate/python/federatedml/util/data_io.py", line 227, in gen_data_instance
25
    data_instance = input_data_features.mapValues(lambda features: self.to_instance(features))
26
  File "./fate/python/fate_arch/common/profile.py", line 282, in _fn
27
    rtn = func(*args, **kwargs)
28
  File "./fate/python/fate_arch/computing/standalone/_table.py", line 79, in mapValues
29
    return Table(self._table.mapValues(func))
30
  File "./fate/python/fate_arch/_standalone.py", line 133, in mapValues
31
    return self._unary(func, _do_map_values)
32
  File "./fate/python/fate_arch/_standalone.py", line 184, in _unary
33
    results = self._session._submit_unary(func, do_func, self._partitions, self._name, self._namespace)
34
  File "./fate/python/fate_arch/_standalone.py", line 319, in _submit_unary
35
    results = [r.result() for r in futures]
36
  File "./fate/python/fate_arch/_standalone.py", line 319, in <listcomp>
37
    results = [r.result() for r in futures]
38
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 432, in result
39
    return self.__get_result()
40
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
41
    raise self._exception
42
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

**Comment by mgqa34** [comment]
Standalone version is a demo not an industrial mode, so please do not run with large dataset with standalone mode
