### ISSUE TITLE
请问homo_nn怎么得到测试集上的评估结果

### ISSUE THREAD

**Issue by pangying1104** [FederatedAI/FATE#2666]
我不加validate_data或test_data，任务就能success，只能得的homo_nn模型在train_data上的测试结果。我一旦加了validate_data或test_data，任务就会failed，error信息如下：
![image](https://user-images.githubusercontent.com/15884567/111904164-5f0bfc00-8a80-11eb-8bb9-8731ceec8d0e.png)
![image](https://user-images.githubusercontent.com/15884567/111904180-76e38000-8a80-11eb-88f4-f4ea9042b4cd.png)

**Comment by SennriSyunnga** [comment]
一样不能跑
但是报的错不太一样：
```
[ERROR] [2021-08-16 14:11:03,893] [11279:140061869107008] - task_executor.py[line:196]: [federation.eggroll.remote.hash.9385a4f12a9bca0aa101.local_labels.fit.label_align[('arbiter', '10002')])]remote `None` to [('arbiter', '10002')]
Traceback (most recent call last):
  File "./fate/python/fate_flow/operation/task_executor.py", line 174, in run_task
    run_object.run(component_parameters_on_party, task_run_args)
  File "./fate/python/federatedml/model_base.py", line 101, in run
    this_data_output = func(*params)
  File "./fate/python/federatedml/nn/homo_nn/enter_point.py", line 203, in fit
    self._align_labels(data_inst)
  File "./fate/python/federatedml/nn/homo_nn/enter_point.py", line 170, in _align_labels
    _, self._label_align_mapping = HomoLabelEncoderClient().label_alignment(local_labels)
  File "./fate/python/federatedml/util/homo_label_encoder.py", line 15, in label_alignment
    self.transvar.local_labels.remote(class_set, role=consts.ARBITER, suffix=('label_align',))
  File "./fate/python/fate_arch/federation/transfer_variable/_transfer_variable.py", line 213, in remote
    return self.remote_parties(obj=obj, parties=parties, suffix=suffix)
  File "./fate/python/fate_arch/federation/transfer_variable/_transfer_variable.py", line 140, in remote_parties
    session.federation.remote(v=obj, name=name, tag=tag, parties=parties, gc=self._remote_gc)
  File "./fate/python/fate_arch/federation/eggroll/_federation.py", line 57, in remote
    _remote(v, name, tag, parties, self._rsc, gc)
  File "./fate/python/fate_arch/federation/eggroll/_federation.py", line 63, in _remote
    raise ValueError(f"[{log_str}]remote `None` to {parties}")
ValueError: [federation.eggroll.remote.hash.9385a4f12a9bca0aa101.local_labels.fit.label_align[('arbiter', '10002')])]remote `None` to [('arbiter', '10002')]
```
版本不同？我这是1.5.2
