### ISSUE TITLE
NameError: name 'mpa' is not defined

### ISSUE THREAD

**Issue by Milkve** [FederatedAI/FATE#2744]
**Describe the bug**
When I tried some homo secureboost pipeline examples, like [pipeline-homo-sbt-binary-with-predict.py](https://github.com/FederatedAI/FATE/blob/master/examples/pipeline/homo_sbt/pipeline-homo-sbt-binary-with-predict.py), the FATE board showed that `NameError: name 'mpa' is not defined`.
In CLI, it told me to check out the FATE board:
```
root@66242165a59e:/fate/examples/pipeline/homo_sbt# pipeline_script=pipeline-homo-sbt-binary-with-predict.py
root@66242165a59e:/fate/examples/pipeline/homo_sbt# python ${pipeline_script} 
2021-04-13 12:01:41.023722: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-04-13 12:01:41.023835: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-04-13 12:01:47.061 | INFO     | pipeline.utils.invoker.job_submitter:monitor_job_status:121 - Job id is 2021041312014588872320
                   Job is still waiting, time elapse: 0:00:02
2021-04-13 12:01:50Running component reader_1, time elapse: 0:00:08
2021-04-13 12:01:57Running component reader_0, time elapse: 0:00:16
2021-04-13 12:02:04Running component dataio_0, time elapse: 0:00:23
2021-04-13 12:02:11Running component dataio_1, time elapse: 0:00:30
2021-04-13 12:02:18Running component homo_secureboost_0, time elapse: 0:02:57
2021-04-13 12:04:46Running component evaluation_0, time elapse: 0:03:17
2021-04-13 12:05:07.239 | INFO     | pipeline.utils.invoker.job_submitter:monitor_job_status:129 - Job is success!!! Job id is 2021041312014588872320
2021-04-13 12:05:07.241 | INFO     | pipeline.utils.invoker.job_submitter:monitor_job_status:130 - Total time: 0:03:20
2021-04-13 12:05:14.805 | INFO     | pipeline.utils.invoker.job_submitter:monitor_job_status:121 - Job id is 2021041312051216963123
                   Job is still waiting, time elapse: 0:00:03
2021-04-13 12:05:19Running component reader_1, time elapse: 0:00:10
2021-04-13 12:05:25Running component dataio_0, time elapse: 0:00:16
2021-04-13 12:05:32Running component homo_secureboost_0, time elapse: 0:00:31
2021-04-13 12:05:49.966 | ERROR    | __main__:main:103 - An error has been caught in function 'main', process 'MainProcess' (71126), thread 'MainThread' (140338903152448):
Traceback (most recent call last):

  File "pipeline-homo-sbt-binary-with-predict.py", line 114, in <module>
    main()
    └ <function main at 0x7fa33253be18>

> File "pipeline-homo-sbt-binary-with-predict.py", line 103, in main
    predict_pipeline.predict(job_parameters)
    │                │       └ <pipeline.runtime.entity.JobParameters object at 0x7fa2c8beacf8>
    │                └ <function PipeLine.predict at 0x7fa2c8bca0d0>
    └ <pipeline.backend.pipeline.PipeLine object at 0x7fa2c8beacc0>

  File "/usr/local/lib/python3.6/site-packages/pipeline/backend/pipeline.py", line 501, in predict
    self._initiator.party_id)
    │    │          └ 10000
    │    └ namespace(party_id=10000, role='guest')
    └ <pipeline.backend.pipeline.PipeLine object at 0x7fa2c8beacc0>
  File "/usr/local/lib/python3.6/site-packages/pipeline/utils/invoker/job_submitter.py", line 136, in monitor_job_status
    raise ValueError(f"Job is failed, please check out job {job_id} by fate board or fate_flow cli")

ValueError: Job is failed, please check out job 2021041312051216963123 by fate board or fate_flow cli
Traceback (most recent call last):
  File "pipeline-homo-sbt-binary-with-predict.py", line 114, in <module>
    main()
  File "pipeline-homo-sbt-binary-with-predict.py", line 103, in main
    predict_pipeline.predict(job_parameters)
  File "/usr/local/lib/python3.6/site-packages/loguru/_logger.py", line 1220, in catch_wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipeline/backend/pipeline.py", line 501, in predict
    self._initiator.party_id)
  File "/usr/local/lib/python3.6/site-packages/pipeline/utils/invoker/job_submitter.py", line 136, in monitor_job_status
    raise ValueError(f"Job is failed, please check out job {job_id} by fate board or fate_flow cli")
ValueError: Job is failed, please check out job 2021041312051216963123 by fate board or fate_flow cli
root@66242165a59e:/fate/examples/pipeline/homo_sbt# pipeline_script=pipeline-homo-sbt-binary-with-predict.py
```
And what FATE board's feedback was:
```
1
[ERROR] [2021-04-13 12:05:44,701] [76032:139781429630784] - task_executor.py[line:191]: name 'mpa' is not defined
2
Traceback (most recent call last):
3
  File "./fate/python/fate_flow/operation/task_executor.py", line 168, in run_task
4
    run_object.run(component_parameters_on_party, task_run_args)
5
  File "./fate/python/federatedml/model_base.py", line 101, in run
6
    this_data_output = func(*params)
7
  File "./fate/python/federatedml/ensemble/boosting/boosting_core/boosting.py", line 530, in load_model
8
    self.set_model_param(model_param)
9
  File "./fate/python/federatedml/ensemble/boosting/homo/homo_secureboost_client.py", line 159, in set_model_param
10
    self.classes_ = list(mpa(int, model_param.classes_))
11
NameError: name 'mpa' is not defined
```

**To Reproduce**
1. [Stand-alone Deployment](https://github.com/FederatedAI/FATE/tree/master/standalone-deploy)
2. Follow the [Pipeline Examples](https://github.com/FederatedAI/FATE/blob/master/examples/pipeline/README.rst) steps 1~4
3. Modify some lines in
https://github.com/FederatedAI/FATE/blob/178f04d1a58181359d6550b4673d4b4dc72a778f/examples/pipeline/demo/pipeline-upload.py#L46-L60
Change `breast_hetero_guest` and `breast_hetero_host` to `breast_homo_guest` and `breast_homo_host` in these lines respectively.
4. Follow the [Homo SecureBoost Pipeline Example Usage Guide.](https://github.com/FederatedAI/FATE/blob/master/examples/pipeline/homo_sbt/README.md)
```
root@66242165a59e:/fate/examples/pipeline/homo_sbt# pipeline_script=pipeline-homo-sbt-binary-with-predict.py
root@66242165a59e:/fate/examples/pipeline/homo_sbt# python ${pipeline_script}
```
5. See errors.

**Expected behavior**
A good result with job id in FATE board.

**Screenshots**
![image](https://user-images.githubusercontent.com/45092129/114555080-f0dee180-9c99-11eb-91c4-d2bad54d03fc.png)
Job 20 is training, successfully finished, and job 23 is predicting, failed.
Job 20:
![image](https://user-images.githubusercontent.com/45092129/114555508-59c65980-9c9a-11eb-9a2f-ba09f7121df9.png)
Job 23:
![image](https://user-images.githubusercontent.com/45092129/114555828-a9a52080-9c9a-11eb-9238-731506f739d2.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu Server 18.04, on VMWare
 - Network of VM: bridged network
 - FATE Stand-alone Version 1.6.0

**Additional context**
If need any other context about the problem, I'm willing to provide with.

**Comment by talkingwallace** [comment]
This a typo in homo-sbt. Rename 'mpa' to 'map' in homo_secureboost_client.py line 159.
Thanks for your prompt report, we've fixed this problem in the master branch.

**Comment by mgqa34** [comment]
Code already merge into master,  if user use release package of fate-v1.6.0，should be update into master's code.
