### ISSUE TITLE
Evaluation module absent when using a predict conf to run homo nn model and others bug

### ISSUE THREAD

**Issue by SennriSyunnga** [FederatedAI/FATE#2975]
**Describe the bug**
When I finished a simple rnn model training, i try to add an eval data to the train conf json.
Then something wrong happended, train job failed in the homo_nn part:
```py
[ERROR] [2021-08-16 14:11:03,893] [11279:140061869107008] - task_executor.py[line:196]: [federation.eggroll.remote.hash.9385a4f12a9bca0aa101.local_labels.fit.label_align[('arbiter', '10002')])]remote `None` to [('arbiter', '10002')]
Traceback (most recent call last):
  File "./fate/python/fate_flow/operation/task_executor.py", line 174, in run_task
    run_object.run(component_parameters_on_party, task_run_args)
  File "./fate/python/federatedml/model_base.py", line 101, in run
    this_data_output = func(*params)
  File "./fate/python/federatedml/nn/homo_nn/enter_point.py", line 203, in fit
    self._align_labels(data_inst)
  File "./fate/python/federatedml/nn/homo_nn/enter_point.py", line 170, in _align_labels
    _, self._label_align_mapping = HomoLabelEncoderClient().label_alignment(local_labels)
  File "./fate/python/federatedml/util/homo_label_encoder.py", line 15, in label_alignment
    self.transvar.local_labels.remote(class_set, role=consts.ARBITER, suffix=('label_align',))
  File "./fate/python/fate_arch/federation/transfer_variable/_transfer_variable.py", line 213, in remote
    return self.remote_parties(obj=obj, parties=parties, suffix=suffix)
  File "./fate/python/fate_arch/federation/transfer_variable/_transfer_variable.py", line 140, in remote_parties
    session.federation.remote(v=obj, name=name, tag=tag, parties=parties, gc=self._remote_gc)
  File "./fate/python/fate_arch/federation/eggroll/_federation.py", line 57, in remote
    _remote(v, name, tag, parties, self._rsc, gc)
  File "./fate/python/fate_arch/federation/eggroll/_federation.py", line 63, in _remote
    raise ValueError(f"[{log_str}]remote `None` to {parties}")
ValueError: [federation.eggroll.remote.hash.9385a4f12a9bca0aa101.local_labels.fit.label_align[('arbiter', '10002')])]remote `None` to [('arbiter', '10002')]
```
It confused me a lot, i never saw this log before.
What's more, when i tried to use a predict conf to make a workaround,
another problem surprised me:
The evaluation module is absent from dsl graph ( in fate-board), while the original train dsl file indeed has it.
Can somebody tell me is there any problems in my json file?
Or just a bug in code implementation？
Thanks a lot!
**To Reproduce**
the content is just like this:
```json
{
  "initiator": {
    "role": "guest",
    "party_id": 10001
  },
  "job_parameters": {
    "work_mode": 1
  },
  "role": {
    "guest": [
      10001
    ],
    "host": [
      10002
    ],
    "arbiter": [
      10002
    ]
  },
  "role_parameters": {
    "guest": {
      "args": {
        "data": {
          "train_data": [
            {
              "name": "breast_homo_guest",
              "namespace": "experiment"
            }
          ],
          "eval_data":[
            {
              "name": "breast_homo_test",
              "namespace": "experiment"
            }
          ]
        }
      },
      "dataio_0": {
        "with_label": [
          true
        ],
        "label_name": [
          "y"
        ],
        "label_type": [
          "int"
        ],
        "output_format": [
          "dense"
        ]
      }
    },
    "host": {
      "args": {
        "data": {
          "train_data": [
            {
              "name": "breast_homo_host",
              "namespace": "experiment"
            }
          ],
          "eval_data":[
            {
              "name": "breast_homo_test",
              "namespace": "experiment"
            }
          ]
        }
      },
      "dataio_0": {
        "with_label": [
          true
        ],
        "label_name": [
          "y"
        ],
        "label_type": [
          "int"
        ],
        "output_format": [
          "dense"
        ]
      }
    }
  },
  "algorithm_parameters": {
    "homo_nn_0": {
      "config_type": "keras",
      "nn_define": {
        "class_name": "Sequential",
        "config": {
          "name": "sequential",
          "layers": [
            {
              "class_name": "RepeatVector",
              "config": {
                "name":"rp",
                "n":1
              }
            },
            {
              "class_name": "LSTM",
              "config": {
                "name":"lstm",
                "units":32
              }
            },
            {
              "class_name": "Dense",
              "config": {
                "name": "dense",
                "trainable": true,
                "dtype": "float32",
                "units": 64,
                "activation": "relu"
              }
            },
            {
              "class_name": "Dense",
              "config": {
                "name": "dense_2",
                "trainable": true,
                "dtype": "float32",
                "units": 1,
                "activation": "sigmoid"
              }
            }
          ]
        },
        "keras_version": "2.2.4-tf",
        "backend": "tensorflow"
      },
      "batch_size": -1,
      "optimizer": {
        "optimizer": "Adam",
        "learning_rate": 0.05
      },
      "early_stop": {
        "early_stop": "diff",
        "eps": 1e-4
      },
      "loss": "binary_crossentropy",
      "metrics": [
        "accuracy",
        "AUC"
      ],
      "max_iter": 10
    }
  }
}
```
The dsl file is like:
```json
{
  "components": {
    "dataio_0": {
      "module": "DataIO",
      "input": {
        "data": {
          "data": [
            "args.train_data"
          ]
        }
      },
      "output": {
        "data": [
          "train"
        ],
        "model": [
          "dataio"
        ]
      }
    },
    "dataio_1": {
      "module": "DataIO",
      "input": {
        "data": {
          "data": [
            "args.eval_data"
          ]
        },
        "model": [
          "dataio_0.dataio"
        ]
      },
      "output": {
        "data": [
          "eval"
        ],
        "model": [
          "dataio"
        ]
      }
    },
    "feature_scale_0": {
      "module": "FeatureScale",
      "input": {
        "data": {
          "data": [
            "dataio_0.train"
          ]
        }
      },
      "output": {
        "data": [
          "train"
        ],
        "model": [
          "feature_scale"
        ]
      }
    },
    "feature_scale_1": {
      "module": "FeatureScale",
      "input": {
        "data": {
          "data": [
            "dataio_1.eval"
          ]
        },
        "model": [
          "feature_scale_0.feature_scale"
        ]
      },
      "output": {
        "data": [
          "eval"
        ],
        "model": [
          "feature_scale"
        ]
      }
    },
    "homo_nn_0": {
      "module": "HomoNN",
      "input": {
        "data": {
          "train_data": [
            "feature_scale_0.train"
          ],
          "eval_data": [
            "feature_scale_1.eval"
          ]
        }
      },
      "output": {
        "data": [
          "train"
        ],
        "model": [
          "homo_nn"
        ]
      }
    },
    "evaluation_0": {
      "module": "Evaluation",
      "input": {
        "data": {
          "data": [
            "homo_nn_0.train"
          ]
        }
      }
    }
  }
}

```
**Expected behavior**

**Screenshots**

![image1](https://user-images.githubusercontent.com/39991122/129528689-88c5248a-5d9d-46e1-8b3e-c3b8ba57afbe.png)

![image](https://user-images.githubusercontent.com/39991122/129528678-202abf22-6545-47ff-b988-61029ff4ed54.png)

**Comment by SennriSyunnga** [comment]
Besides, I notice that the model details json you receive from fate contains parts of raw string content instead of k-v map 
such as "nnDefine" and optimizer "args".
Well, they are weird among others, maybe.
```json
{
    "code": 200,
    "data": {
        "data": {
            "aggregateIter": 0,
            "header": [
                "x0",
                "x1",
                "x2",
                "x3",
                "x4",
                "x5",
                "x6",
                "x7",
                "x8",
                "x9",
                "x10",
                "x11",
                "x12",
                "x13",
                "x14",
                "x15",
                "x16",
                "x17",
                "x18",
                "x19",
                "x20",
                "x21",
                "x22",
                "x23",
                "x24",
                "x25",
                "x26",
                "x27",
                "x28",
                "x29"
            ],
            "isConverged": false,
            "labelMapping": [
                {
                    "label": "0",
                    "mapped": "0"
                },
                {
                    "label": "1",
                    "mapped": "1"
                }
            ],
            "lossHistory": [],
            "savedModelBytes": { SKIPPED },
        "meta": {
            "meta_data": {
                "aggregateIter": 10,
                "params": {
                    "aggregateEveryNEpoch": 1,
                    "batchSize": -1,
                    "configType": "keras",
                    "earlyStop": {
                        "earlyStop": "diff",
                        "eps": 1.0E-4
                    },
                    "encodeLabel": false,
                    "loss": "binary_crossentropy",
                    "maxIter": 10,
                    "metrics": [
                        "accuracy",
                        "AUC"
                    ],
                    "nnDefine": [
                        "{\"class_name\": \"Sequential\", \"config\": {\"name\": \"sequential\", \"layers\": [{\"class_name\": \"RepeatVector\", \"config\": {\"name\": \"rp\", \"n\": 1}}, {\"class_name\": \"LSTM\", \"config\": {\"name\": \"lstm\", \"units\": 32}}, {\"class_name\": \"Dense\", \"config\": {\"name\": \"dense\", \"trainable\": true, \"dtype\": \"float32\", \"units\": 64, \"activation\": \"relu\"}}, {\"class_name\": \"Dense\", \"config\": {\"name\": \"dense_2\", \"trainable\": true, \"dtype\": \"float32\", \"units\": 1, \"activation\": \"sigmoid\"}}]}, \"keras_version\": \"2.2.4-tf\", \"backend\": \"tensorflow\"}"
                    ],
                    "optimizer": {
                        "args": "{\"learning_rate\": 0.05}",
                        "optimizer": "Adam"
                    },
                    "secureAggregate": true
                }
            },
            "module_name": "HomoNN"
        },
        "retcode": 0,
        "retmsg": "success"
    },
    "msg": "OK"
}
```
