### ISSUE TITLE
Failed to run hetero_logistic_regression in cluster server.

### ISSUE THREAD

**Issue by caimantian007** [FederatedAI/FATE#300]
Hello here,
I am following the guide to installe the cluster version of FATE, I have installed two parties (host and guest). and when i run the test scripts as the following:
/home/fate/workspace/FATE/examples/hetero_logistic_regression
Host server:  ./run_logistic_regression_cluster.sh host jobname1002 10000 9999 10001
Guest server: ./run_logistic_regression_cluster.sh guest jobname1002 10000 9999 10001

Both host and guest are failed due to "_pickle.UnpicklingError: invalid load key, 'm'.".

Here is the status_tracer_decorator error log:
"2019-07-20 10:38:51,500 - status_tracer_decorator.py[line:73] - INFO: job status is failed"
"2019-07-20 10:38:51,502 - status_tracer_decorator.py[line:74] - INFO: Traceback (most recent call last):
  File "/home/fate/workspace/FATE/workflow/status_tracer_decorator.py", line 69, in wrapper
    res = func(self, *args, **kwargs)
  File "/home/fate/workspace/FATE/workflow/workflow.py", line 883, in run
    self.workflow_param.data_input_namespace)
  File "/home/fate/workspace/FATE/workflow/workflow.py", line 761, in gen_data_instance
    mode=mode)
  File "/home/fate/workspace/FATE/federatedml/util/data_io.py", line 93, in read_data
    data_shape = data_overview.get_data_shape(input_data)
  File "/home/fate/workspace/FATE/federatedml/statistic/data_overview.py", line 58, in get_data_shape
    one_feature = features.__next__()
  File "/home/fate/workspace/FATE/arch/api/cluster/eggroll.py", line 518, in __next__
    return _EggRoll._deserialize_operand(self._next_item, include_key=True, use_serialize=self._use_serialize)
  File "/home/fate/workspace/FATE/arch/api/cluster/eggroll.py", line 310, in _deserialize_operand
    operand.value)) if include_key else _EggRoll.value_serdes.deserialize(operand.value)
  File "/home/fate/workspace/FATE/arch/api/utils/eggroll_serdes.py", line 57, in deserialize
    return p_loads(_bytes)
_pickle.UnpicklingError: invalid load key, 'm'.

The OS of the server is.  3.10.0-957.el7.x86_64

**Comment by zazd** [comment]
try delete arch/utils/pickle.py
