### ISSUE TITLE
Cannot successfully cluster-deploy 1.7.0 allinone

### ISSUE THREAD

**Issue by NookLook2014** [FederatedAI/FATE#3469]
### Env
OS: CentOS Linux release 7.9.2009 (Core)
Pkg：fate_cluster_install_1.7.0_release-c7-u18.tar.gz
Install method: cluster-deploy/doc/fate_on_eggroll/fate-allinone_deployment_guide.zh.md

Note: All preparations have been finished and passed the check script. 

### Replicate
After  installation of a single-party host. I execure:
"flow test toy -gid 9998 -hid 9998"

Then the following errors occured:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
keyring 23.2.1 requires SecretStorage>=3.2, which is not installed.
fate-test 0.1 requires pandas>=1.1.5, which is not installed.
**keyring 23.2.1 requires importlib-metadata>=3.6, but you have importlib-metadata 1.7.0 which is incompatible.
markdown 3.3.6 requires importlib-metadata>=4.4, but you have importlib-metadata 1.7.0 which is incompatible.**

### Trials
I tried to upgrade importlib-metadata, but the following error occurs:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/projects/fate/common/python/venv/bin/flow", line 33, in <module>
    sys.exit(load_entry_point('fate-client==0.1', 'console_scripts', 'flow')())
  File "/data/projects/fate/common/python/venv/bin/flow", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 194, in load
    module = import_module(match.group('module'))
  File "/data/projects/fate/common/miniconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/fate_client-0.1-py3.6.egg/flow_client/flow.py", line 20, in <module>
    from ruamel import yaml
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/ruamel.yaml-0.16.13-py3.6.egg/ruamel/__init__.py", line 1, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3238, in <module>
    @_call_aside
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3222, in _call_aside
    f(*args, **kwargs)
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3251, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 569, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 582, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 770, in resolve
    raise DistributionNotFound(req, requirers)
**pkg_resources.DistributionNotFound: The 'importlib-metadata<2.0.0,>=1.6.0' distribution was not found and is required by poetry**

Does any successfully deployed the new version? 
Should i use centos 7.2 ?

**Comment by paulbaogang** [comment]
Hello, you need to execute source /data/projects/fate/bin/init_env.sh before you deploy and run toy. The version in the information is higher than the version provided by the deployment package. For example, the keyring is 21.8.0 and the markdown is 3.3. 5. Has there been any manual upgrade or installation? It is recommended to clean up the environment and redeploy it.

**Comment by NookLook2014** [comment]
> 
1. I didn't notice that "source /data/projects/fate/bin/init_env.sh "before  you deploy, if you mean deploy is install fate.
2. It's obvious that i executed "source ..." before i run this toy example. 
Thanks for your reply, i'll try to redeploy it.

**Comment by paulbaogang** [comment]
execute source /data/projects/fate/bin/init_env.sh before run toy, mainly to solve the problem of why the version of the dependent package is higher than the version in the deployment package. You can re-pull the package, and then also clean up the files in the /data/temp directory.

**Comment by NookLook2014** [comment]
Successfully deployed on CentOS 7.4, thanks a lot!
