### ISSUE TITLE
Toy test error: Cannot allocate memory 

### ISSUE THREAD

**Issue by ThornsOoO** [FederatedAI/FATE#3519]
在安装1.7.0镜像后进行toy测试。出现报错
lmdb.MemoryError: /data/projects/fate/data/202112070925038649660_secure_add_example_0_0_guest_10000/26262630-5740-11ec-afef-0242ac110002/2: Cannot allocate memory

另外在进行任何测试时  打开浏览器输入127.0.0.1:8080或本地ip：8080均无法打开fateboard

设备内存32G 

toy test job 202112070925038649660 is running
toy test job 202112070925038649660 is failed
[ERROR] [2021-12-07 09:30:16,653] [202112070925038649660] [2882:274907579520] - [task_executor._run_] [line:243]: /data/projects/fate/data/202112070925038649660_secure_add_example_0_0_guest_10000/26262630-5740-11ec-afef-0242ac110002/2: Cannot allocate memory
Traceback (most recent call last):
File "/data/projects/fate/fateflow/python/fate_flow/worker/task_executor.py", line 195, in _run_
cpn_output = run_object.run(cpn_input)
File "/data/projects/fate/fate/python/federatedml/toy_example/secure_add_guest.py", line 107, in run
self.sync_share_to_host()
File "/data/projects/fate/fate/python/federatedml/toy_example/secure_add_guest.py", line 85, in sync_share_to_host
idx=0)
File "/data/projects/fate/fate/python/fate_arch/federation/transfer_variable.py", line 279, in remote
return self.remote_parties(obj=obj, parties=parties, suffix=suffix)
File "/data/projects/fate/fate/python/fate_arch/federation/transfer_variable.py", line 193, in remote_parties
v=obj, name=name, tag=tag, parties=parties, gc=self._remote_gc
File "/data/projects/fate/fate/python/fate_arch/federation/standalone/_federation.py", line 39, in remote
return self._federation.remote(v=v, name=name, tag=tag, parties=parties)
File "/data/projects/fate/fate/python/fate_arch/_standalone.py", line 565, in remote
name=saved_name, namespace=v.namespace, need_cleanup=False
File "/data/projects/fate/fate/python/fate_arch/_standalone.py", line 281, in save_as
dup.put_all(self.collect())
File "/data/projects/fate/fate/python/fate_arch/_standalone.py", line 301, in put_all
for k, v in kv_list:
File "/data/projects/fate/fate/python/fate_arch/_standalone.py", line 104, in collect
env = s.enter_context(self._get_env_for_partition(p))
File "/data/projects/fate/fate/python/fate_arch/_standalone.py", line 285, in _get_env_for_partition
return _get_env(self._namespace, self._name, str(p), write=write)
File "/data/projects/fate/fate/python/fate_arch/_standalone.py", line 800, in _get_env
return _open_env(_path, write=write)
File "/data/projects/fate/fate/python/fate_arch/_standalone.py", line 824, in _open_env
raise e
File "/data/projects/fate/fate/python/fate_arch/_standalone.py", line 816, in _open_env
map_size=10_737_418_240,
lmdb.MemoryError: /data/projects/fate/data/202112070925038649660_secure_add_example_0_0_guest_10000/26262630-5740-11ec-afef-0242ac110002/2: Cannot allocate memory

**Comment by ThornsOoO** [comment]
![1638871139(1)](https://user-images.githubusercontent.com/24326352/145007997-3992dcbd-bf22-4d89-a536-a4b5d9454cd9.png)
