### ISSUE TITLE
cluster-deployment issue

### ISSUE THREAD

**Issue by Foipngoc** [FederatedAI/FATE#3833]
使用allInOne部署，完毕后测试toy test失败，检查日志发现mysql 缺少远程登录权限:

` Caused by: java.sql.SQLException: Cannot create PoolableConnectionFactory (Access denied for user 'fate'@'ubuntu-fata-1' (using password: YES))
	at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:669)
	at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:669)
	at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:544)
	at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:544)
	at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:753)
	at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:753)
        at com.webank.eggroll.core.util.JdbcTemplate.withStatement(JdbcTemplate.scala:82)
	at com.webank.eggroll.core.util.JdbcTemplate.query(JdbcTemplate.scala:109)
	at com.webank.eggroll.core.util.JdbcTemplate.query(JdbcTemplate.scala:109)
        ...more`

追踪mysql的部署脚本，可以发现由mysql-install/deploy.sh脚手架生成的初始sql文件：insert-node.sql中，对fate用户的赋权不够：
第三行：
`GRANT ALL ON fate_flow.* TO fate@'10.10.11.216';`
此处改为
``GRANT ALL ON *.* TO fate@'10.10.11.216';``
就可以使eggroll正常登录了。

或者可以通过其他途径调整，望指教

**Comment by Foipngoc** [comment]
另：版本号为 1.7.0

**Comment by paulbaogang** [comment]
{
echo "CREATE DATABASE IF NOT EXISTS ${fate_flow_dbname};"
echo "CREATE USER ${mysql_user}@'${clustermanager_ip%:*}' IDENTIFIED BY '${mysql_pass}';"
echo "GRANT ALL ON ${fate_flow_dbname}.* TO ${mysql_user}@'${clustermanager_ip%:*}';"
echo "GRANT ALL ON ${eggroll_dbname}.* TO ${mysql_user}@'${clustermanager_ip%:*}';"
echo "use ${eggroll_dbname};"
echo "INSERT INTO server_node (host, port, node_type, status) values ('${clustermanager_ip%:*}', '${clustermanager_ip#*:}', 'CLUSTER_MANAGER', 'HEALTHY');"
for temp in ${nodemanager_ips[*]}
do
echo "INSERT INTO server_node (host, port, node_type, status) values ('${temp%:*}', '${temp#*:}', 'NODE_MANAGER', 'HEALTHY');"
if [  ${temp%:*} != ${clustermanager_ip%:*} ]
then
  echo "CREATE USER ${mysql_user}@'${temp%:*}' IDENTIFIED BY '${mysql_pass}';"
  echo "GRANT ALL ON ${fate_flow_dbname}.* TO ${mysql_user}@'${temp%:*}';"
  echo "GRANT ALL ON ${eggroll_dbname}.* TO ${mysql_user}@'${temp%:*}';"
fi
done

} >  ${pbase}/${pname}/${mysql_path}/${role_name}-${mysql_version}/sql/insert-node.sql

脚本里对两个库都加了权限，理论上生成的文件会包括这两个授权，看下insert-node.sql语句是否包含？另外也可以登录mysql查看下fate用户的授权：SHOW GRANTS FOR 'fate'@'10.10.11.216‘；

**Comment by zhengjujing** [comment]
fate1.7.1性能怎样,100W两方各100维,lr和xgb大概要多长时间
