### ISSUE TITLE
FATE1.7.0单边测试报错，list index out of range

### ISSUE THREAD

**Issue by stevenqyx** [FederatedAI/FATE#3885]
[ERROR] [2022-04-11 10:23:43,804] [Server] [13392:140545598932736] - [api_utils.server_error_response] [line:49]: list index out of range
Traceback (most recent call last):
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/data/projects/fate/fateflow/python/fate_flow/scheduling_apps/party_app.py", line 42, in check_dependence
    status = DependenceManager.check_job_dependence(job)
  File "/data/projects/fate/fateflow/python/fate_flow/manager/dependence_manager.py", line 113, in check_job_dependence
    fate_flow_version_provider_info)
  File "/data/projects/fate/fateflow/python/fate_flow/manager/dependence_manager.py", line 63, in check_upload
    flow_provider = ComponentProvider(**list(fate_flow_version_provider_info.values())[0])
IndexError: list index out of range

job一直在wating状态

**Comment by zhihuiwan** [comment]
请问下您是使用fate on spark模式吗？

**Comment by stevenqyx** [comment]
是的，问题已经解决了，是pulsar配置的问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FederatedAI/FATE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月28日(星期四) 晚上8:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [FederatedAI/FATE] FATE1.7.0单边测试报错，list index out of range (Issue #3885)





 
请问下您是使用fate on spark模式吗？
