### ISSUE TITLE
How to run examples/pipline/interect/*.py?

### ISSUE THREAD

**Issue by qxzhou1010** [FederatedAI/FATE#3921]
I have installed the FATE in my MacOS and passed the test case, just like `flow test toy -gid 10000 -hid 10000`.
I want to run the code in examples/pipline/interect/. I follow the README.md in `examples/pipline/interect/`.
  
```
Users can run a pipeline job directly:

    python ${pipeline_script}
```
However, the errors occurs:
```
2022-04-19 16:03:48.965 | INFO     | pipeline.utils.invoker.job_submitter:monitor_job_status:123 - Job id is 202204191603472444490
                   Job is still waiting, time elapse: 0:00:01
2022-04-19 16:03:51Running component reader_0, time elapse: 0:00:03
2022-04-19 16:03:55.140 | ERROR    | __main__:main:67 - An error has been caught in function 'main', process 'MainProcess' (11286), thread 'MainThread' (4593049088):
Traceback (most recent call last):

  File "pipeline-intersect-rsa.py", line 78, in <module>
    main()
    └ <function main at 0x7f89c1dc6e18>

> File "pipeline-intersect-rsa.py", line 67, in main
    pipeline.fit()
    │        └ <function PipeLine.fit at 0x7f89d0e24a60>
    └ <pipeline.backend.pipeline.PipeLine object at 0x7f89d0e2d630>

  File "/Users/xxx/fate_all/FATE/fate-env/lib/python3.6/site-packages/fate_client-0.1-py3.6.egg/pipeline/backend/pipeline.py", line 549, in fit
    self._initiator.party_id)
    │    │          └ 9999
    │    └ namespace(party_id=9999, role='guest')
    └ <pipeline.backend.pipeline.PipeLine object at 0x7f89d0e2d630>
  File "/Users/xxx/fate_all/FATE/fate-env/lib/python3.6/site-packages/fate_client-0.1-py3.6.egg/pipeline/utils/invoker/job_submitter.py", line 138, in monitor_job_status
    raise ValueError(f"Job is failed, please check out job {job_id} by fate board or fate_flow cli")

ValueError: Job is failed, please check out job 202204191603472444490 by fate board or fate_flow cli
Traceback (most recent call last):
  File "pipeline-intersect-rsa.py", line 78, in <module>
    main()
  File "pipeline-intersect-rsa.py", line 67, in main
    pipeline.fit()
  File "/Users/xxx/fate_all/FATE/fate-env/lib/python3.6/site-packages/loguru/_logger.py", line 1220, in catch_wrapper
    return function(*args, **kwargs)
  File "/Users/xxx/fate_all/FATE/fate-env/lib/python3.6/site-packages/fate_client-0.1-py3.6.egg/pipeline/backend/pipeline.py", line 549, in fit
    self._initiator.party_id)
  File "/Users/xxx/fate_all/FATE/fate-env/lib/python3.6/site-packages/fate_client-0.1-py3.6.egg/pipeline/utils/invoker/job_submitter.py", line 138, in monitor_job_status
    raise ValueError(f"Job is failed, please check out job {job_id} by fate board or fate_flow cli")
ValueError: Job is failed, please check out job 202204191603472444490 by fate board or fate_flow cli
```
**How to fix this error?**

**Comment by mgqa34** [comment]
Make sure the example data is already uploaded
