### ISSUE TITLE
自定义组件无法运行

### ISSUE THREAD

**Issue by turkeymz** [FederatedAI/FATE#3966]
# New Algorithm

根据步骤自定义组件，（mate/param/核心代码）
但在实际运行时候卡住无法运行，检擦日志发现是fate_flow在计算状态时长度为0
请问这个应该怎么解决？

# 日志
```
[INFO] [2022-05-09 06:51:16,365] [202205090318518103400] [32:140455706732288] - [dag_scheduler.schedule_running_job] [line:404]: scheduling running job
[INFO] [2022-05-09 06:51:16,365] [202205090318518103400] [32:140455706732288] - [task_scheduler.schedule] [line:35]: scheduling job tasks
[INFO] [2022-05-09 06:51:16,367] [202205090318518103400] [32:140455706732288] - [task_scheduler.schedule] [line:93]: finish scheduling job tasks
[ERROR] [2022-05-09 06:51:16,367] [202205090318518103400] [32:140455706732288] - [dag_scheduler.run_do] [line:224]: calculate job status failed, all task status: dict_values([])
Traceback (most recent call last):
  File "/data/projects/fate/fateflow/python/fate_flow/scheduler/dag_scheduler.py", line 222, in run_do
    self.schedule_running_job(job=job)
  File "/data/projects/fate/fateflow/python/fate_flow/scheduler/dag_scheduler.py", line 411, in schedule_running_job
    new_job_status = cls.calculate_job_status(task_scheduling_status_code=task_scheduling_status_code, tasks_status=tasks_status.values())
  File "/data/projects/fate/fateflow/python/fate_flow/scheduler/dag_scheduler.py", line 564, in calculate_job_status
    raise Exception("calculate job status failed, all task status: {}".format(tasks_status))
Exception: calculate job status failed, all task status: dict_values([])
[ERROR] [2022-05-09 06:51:16,367] [202205090318518103400] [32:140455706732288] - [dag_scheduler.run_do] [line:225]: schedule job failed
```

**Comment by mgqa34** [comment]
Please give more information like job_dsl.json. Maybe there are no valid fields in dsl["components"]

**Comment by turkeymz** [comment]
> Please give more information like job_dsl.json. Maybe there are no valid fields in dsl["components"]

你好，这是我请求/v1/job/submit的请求体。
组件的核心逻辑继续引用了1.6的，其余的mate等针对1.8文档做了修改并放在对应位置
```
{
    "job_runtime_conf": {
        "job_parameters": {
            "common": {
                "work_mode": 1
            }
        },
        "dsl_version": 2,
        "component_parameters": {
            "role": {
                "local": {
                    "0": {
                        "upload_0": {
                            "db_type": "ORACLE",
                            "storage_address": null,
                            "destroy": null,
                            "params": [
                                "ASS_TABLE_INFO_ID_",
                                "CREATE_BY_",
                                "CREATE_DEP_ID_",
                                "CREATE_TIME_",
                                "DATA_EXTRA_TAG_",
                                "DATA_ID_",
                                "LESSEE_INFO_ID_",
                                "LIB_LABEL_CODE_",
                                "LIB_LABEL_NAME_",
                                "STATUS_",
                                "TASK_ID_",
                                "TYPE_",
                                "UPDATE_BY_",
                                "UPDATE_TIME_",
                                "USER_GROUP_ID_"
                            ],
                            "partition": 16,
                            "port": 1521,
                            "passwd": "EXDB_SQ",
                            "host": "192.168.4.201",
                            "name": "implement_A_RES_TABLE",
                            "namespace": "implement_A_RES_TABLE",
                            "id": "USER_GROUP_LABEL_RES_ID_",
                            "storage_engine": null,
                            "user": "EXDB_SQ",
                            "db": "ORCL",
                            "table": "A_RES_TABLE"
                        }
                    }
                }
            }
        },
        "role": {
            "local": [
                0
            ]
        },
        "initiator": {
            "role": "local",
            "party_id": 0
        }
    },
    "job_dsl": {
        "components": {
            "upload_0": {
                "module": "UploadFromDB"
            }
        }
    }
}
```

**Comment by turkeymz** [comment]
> Please give more information like job_dsl.json. Maybe there are no valid fields in dsl["components"]
老师，我依次打印了dag_scheduler中TaskScheduler.schedule的结果。他们分别是：
task_scheduling_status_code：2
auto_rerun_tasks：[]
tasks：dict_values([])

请问是我的组件有什么漏了？导致出现任务为空的错误吗？

**Comment by turkeymz** [comment]
@dylan-fan 老师您好？请问能帮忙看看这个问题吗？或者需要更详细的资料，我可以压缩起来Email？

**Comment by zhihuiwan** [comment]
方便查询一下任务的信息吗？flow task query -j xxx

**Comment by turkeymz** [comment]
> 方便查询一下任务的信息吗？flow task query -j xxx

这边找源码找到了，少了个on_local。
建议完善一下开发问题，但第五步的protobuf还是没看明白meta和param的参数依据是什么？
看到meta有算法参数属性，param也有算法参数属性

**Comment by turkeymz** [comment]
> 



> > > 方便查询一下任务的信息吗？flow task query -j xxx
> > 
> > 
> > 这边找源码找到了，少了个on_local。 建议完善一下开发文档，但第五步的protobuf还是没看明白meta和param的参数依据是什么？ 看到meta有算法参数属性，param也有算法参数属性
> 
> meta代表的是不变量，比如用户的配置，param更多是训练过程中模型生成的参数，比如模型权重，实际收敛次数这些；如果不需要，可以不定义

好的，收到。谢谢老师。
但还是建议完善一下文档，因为这里的meta和上面定义的meta.py的意思似乎又不一样。
然后fate能不能出一个社区论坛，我发现我这种错误只是开发问题，非产品bug。
但我官方微信社区群里连问专家几天都没有人回应，推荐出一个社区让人方面找到解决方案

再次谢谢老师解答，我关掉bug了

**Comment by mgqa34** [comment]
> > 
> 
> > > > 方便查询一下任务的信息吗？flow task query -j xxx
> > > 
> > > 
> > > 这边找源码找到了，少了个on_local。 建议完善一下开发文档，但第五步的protobuf还是没看明白meta和param的参数依据是什么？ 看到meta有算法参数属性，param也有算法参数属性
> > 
> > 
> > meta代表的是不变量，比如用户的配置，param更多是训练过程中模型生成的参数，比如模型权重，实际收敛次数这些；如果不需要，可以不定义
> 
> 好的，收到。谢谢老师。 但还是建议完善一下文档，因为这里的meta和上面定义的meta.py的意思似乎又不一样。 然后fate能不能出一个社区论坛，我发现我这种错误只是开发问题，非产品bug。 但我官方微信社区群里连问专家几天都没有人回应，推荐出一个社区让人方面找到解决方案
> 
> 再次谢谢老师解答，可以close issue

感谢您的提议，方便的话，可以提一个文档修改优化的pr哈，因为开发文档是fate的主要开发同学开发的，很多概念比较熟悉，但可能对于陌生开发者来说有些不足。
