### ISSUE TITLE
Fate_1.8.0 跑secureboost_cross_validation_binary预测任务报错

### ISSUE THREAD

**Issue by FranisiL** [FederatedAI/FATE#4075]
**Describe the bug**

1. secureboost_cross_validation_binary预测任务报错

**To Reproduce**
1. 使用给定模版：test_secureboost_cross_validation_binary_conf.json、test_secureboost_cross_validation_dsl.json跑正常训练任务，使用跑完的模型跑预测任务，通过`flow model get-predict-dsl ` `flow model get-predict-conf` 下载预测所需的dsl、conf文件来跑预测任务，通过 `flow job submit -d -c`来执行提交预测任务，预测任务在hetero_secure_boost_0节点报错
2. 报错信息如下
`[INFO] [2022-07-01 08:24:06,641] [202207010823023086500] [64728:139764175443776] - [task_executor._run_] [line:145]: task input dsl {'data': {'test_data': ['intersection_0.data']}, 'model': ['pipeline.hetero_secure_boost_0.model']}
[INFO] [2022-07-01 08:24:06,641] [202207010823023086500] [64728:139764175443776] - [tracker_client.get_output_data_info] [line:265]: Request read job 202207010823023086500 task 202207010823023086500_hetero_secure_boost_0 0 on guest 9999 data data info
[INFO] [2022-07-01 08:24:06,657] [202207010823023086500] [64728:139764175443776] - [task_executor.get_task_run_args] [line:339]: load computing table use 4
[INFO] [2022-07-01 08:24:06,714] [202207010823023086500] [64728:139764175443776] - [task_executor._run_] [line:156]: task input args {'data': {'intersection_0': {'test_data': [<fate_arch.computing.eggroll._table.Table object at 0x7f1d10fa8c88>]}}, 'model': {'hetero_secure_boost_0': {}}}
[INFO] [2022-07-01 08:24:06,716] [202207010823023086500] [64728:139764175443776] - [task_executor._run_] [line:194]: profile logging is disabled
[WARNING] [2022-07-01 08:24:06,719] [202207010823023086500] [64728:139764175443776] - [base_param._warn_to_deprecate_param] [line:375]: boosting_param's validation_freqs will be deprecated in future release; please use callback_param's 'validation_freqs' instead.
[ERROR] [2022-07-01 08:24:06,720] [202207010823023086500] [64728:139764175443776] - [task_executor._run_] [line:243]: Train_data should be configured in cross-validate task or stepwise task
Traceback (most recent call last):
  File "/data/projects/fate/fateflow/python/fate_flow/worker/task_executor.py", line 195, in _run_
    cpn_output = run_object.run(cpn_input)
  File "/data/projects/fate/fate/python/federatedml/model_base.py", line 236, in run
    self._run(cpn_input=cpn_input)
  File "/data/projects/fate/fate/python/federatedml/model_base.py", line 299, in _run
    datasets=cpn_input.datasets, models=cpn_input.models, cpn=self
  File "/data/projects/fate/fate/python/federatedml/util/component_properties.py", line 299, in extract_running_rules
    datasets, cpn
  File "/data/projects/fate/fate/python/federatedml/util/component_properties.py", line 248, in extract_input_data
    self._abnormal_dsl_config_detect()
  File "/data/projects/fate/fate/python/federatedml/util/component_properties.py", line 178, in _abnormal_dsl_config_detect
  File "/data/projects/fate/fate/python/federatedml/util/component_properties.py", line 178, in _abnormal_dsl_config_detect
    "Train_data should be configured in cross-validate "
    "Train_data should be configured in cross-validate "
federatedml.util.component_properties.DSLConfigError: Train_data should be configured in cross-validate task or stepwise task
[INFO] [2022-07-01 08:24:06,721] [202207010823023086500] [64728:139764175443776] - [task_base_worker.report_task_info_to_driver] [line:124]: report TaskExecutor 202207010823023086500_hetero_secure_boost_0 0 guest 9999 to driver:
{'job_id': '202207010823023086500', 'component_name': 'hetero_secure_boost_0', 'task_id': '202207010823023086500_hetero_secure_boost_0', 'task_version': '0', 'role': 'guest', 'party_id': '9999', 'run_ip': 'xxx.xxx.xxx.xxx', 'run_pid': 64728, 'party_status': 'failed', 'src_fate_ver': '1.8.0', 'src_role': '', 'src_party_id': '', 'end_time': 1656663846721, 'elapsed': 3408}
[INFO] [2022-07-01 08:24:06,721] [202207010823023086500] [64728:139764175443776] - [control_client.report_task] [line:41]: request update job 202207010823023086500 task 202207010823023086500_hetero_secure_boost_0 0 on guest 9999
[INFO] [2022-07-01 08:24:06,763] [202207010823023086500] [64728:139764175443776] - [task_executor._run_] [line:254]: finish hetero_secure_boost_0 202207010823023086500_hetero_secure_boost_0 0 on guest 9999 with failed
[INFO] [2022-07-01 08:24:06,764] [202207010823023086500] [64728:139764175443776] - [base_worker.run] [line:123]: worker TaskExecutor, process role: ProcessRole.WORKER, pid: 64728, elapsed: 4025 ms`

**Expected behavior**
1. 正常应该可以顺利跑完预测任务
**Screenshots**

**Desktop (please complete the following information):**
 - Browser [e.g. chrome,]
 - 使用Docker部署
 `
  images 
  federatedai/client:1.8.0-release   
  federatedai/fateboard:1.8.0-release
  federatedai/python:1.8.0-release   
  federatedai/eggroll:1.8.0-release  
  federatedai/eggroll:1.8.0-release  
  federatedai/eggroll:1.8.0-release  
  mysql:8.0.28
`

**Comment by talkingwallace** [comment]
![image](https://user-images.githubusercontent.com/10768970/177113939-f0561e2b-60f7-45f6-a377-8ff917ed190b.png)
看样子是数据配置有问题 可以看看DSL吗

**Comment by FranisiL** [comment]
> ![image](https://user-images.githubusercontent.com/10768970/177113939-f0561e2b-60f7-45f6-a377-8ff917ed190b.png) 看样子是数据配置有问题 可以看看DSL吗
dsl如下
`{
    "components": {
        "reader_0": {
            "module": "Reader",
            "output": {
                "data": [
                    "data"
                ]
            },
            "CodePath": "Reader"
        },
        "data_transform_0": {
            "module": "DataTransform",
            "input": {
                "model": [
                    "pipeline.data_transform_0.model"
                ],
                "data": {
                    "data": [
                        "reader_0.data"
                    ]
                }
            },
            "output": {
                "data": [
                    "data"
                ]
            },
            "CodePath": "DataTransform"
        },
        "intersection_0": {
            "module": "Intersection",
            "output": {
                "data": [
                    "data"
                ]
            },
            "input": {
                "data": {
                    "data": [
                        "data_transform_0.data"
                    ]
                }
            },
            "CodePath": "IntersectGuest"
        },
        "hetero_secure_boost_0": {
            "module": "HeteroSecureBoost",
            "input": {
                "model": [
                    "pipeline.hetero_secure_boost_0.model"
                ],
                "data": {
                    "test_data": [
                        "intersection_0.data"
                    ]
                }
            },
            "output": {
                "data": [
                    "data"
                ]
            },
            "CodePath": "HeteroSecureBoostingTreeGuest"
        }
    }
}`

**Comment by mgqa34** [comment]
Cross validation does not support predict, it only evaluates data performance and will not generate model outputs.

**Comment by FranisiL** [comment]
好的，了解了
