### ISSUE TITLE
The feature binning method:if this module have to be run,bin_indexes and bin_names is [].so have the ERROR.

### ISSUE THREAD

**Issue by KagerJin** [FederatedAI/FATE#4210]
[ERROR] [2022-08-03 15:03:02,609] [202208031501390085770] [2852:4727107008] - [task_executor._run_] [line:243]: 'x9'
Traceback (most recent call last):
  File "../FATE-1.7.2/python/fate_flow/worker/task_executor.py", line 195, in _run_
    cpn_output = run_object.run(cpn_input)
  File "../FATE-1.8.0/python/federatedml/model_base.py", line 236, in run
    self._run(cpn_input=cpn_input)
  File "../FATE-1.8.0/python/federatedml/model_base.py", line 311, in _run
    this_data_output = func(*real_param)
  File "../FATE-1.8.0/python/federatedml/feature/hetero_feature_selection/base_feature_selection.py", line 353, in fit
    self._filter(data_instances, method, suffix=str(filter_idx))
  File "../FATE-1.8.0/python/federatedml/feature/hetero_feature_selection/base_feature_selection.py", line 277, in _filter
    self.curt_select_properties = this_filter.fit(data_instances, suffix).selection_properties
  File "../FATE-1.8.0/python/federatedml/feature/feature_selection/iso_model_filter.py", line 157, in fit
    self._guest_fit(suffix)
  File "../FATE-1.8.0/python/federatedml/feature/feature_selection/iv_filter.py", line 79, in _guest_fit
    self._fix_with_value_obj(value_obj, suffix)
  File "../FATE-1.8.0/python/federatedml/feature/feature_selection/iso_model_filter.py", line 171, in _fix_with_value_obj
    all_feature_values = value_obj.get_partial_values(self.selection_properties.select_col_names)
  File "../FATE-1.8.0/python/federatedml/feature/feature_selection/model_adapter/isometric_model.py", line 104, in get_partial_values
    col_indices = [col_name_map[x] for x in select_col_names]
  File "../FATE-1.8.0/python/federatedml/feature/feature_selection/model_adapter/isometric_model.py", line 104, in <listcomp>
    col_indices = [col_name_map[x] for x in select_col_names]
KeyError: 'x9'

**Comment by mgqa34** [comment]
If you want to use binning as a filter in selection component ,make sure that all selecting feature columns should be included in binning component's iv calculating process.
