### ISSUE TITLE
ValueError：Number of features of Dtable is 0

### ISSUE THREAD

**Issue by Chuang007** [FederatedAI/FATE#4350]
用测试数据没有问题，用自己的数据报错ValueError：Number of features of Dtable is 0是为什么呢？

**Comment by talkingwallace** [comment]
有详细的报错么

**Comment by Chuang007** [comment]
> 有详细的报错么

[ERROR] [2022-09-29 11:17:12,394] [4033:140057865889600] - task_executor.py[line:191]: Number of features of DTable is 0: <fate_arch.computing.standalone._table.Table object at 0x7f6193df0080>
 Traceback (most recent call last):
   File "./fate/python/fate_flow/operation/task_executor.py", line 168, in run_task
     run_object.run(component_parameters_on_party, task_run_args)
   File "./fate/python/federatedml/model_base.py", line 101, in run
     this_data_output = func(*params)
   File "./fate/python/federatedml/linear_model/logistic_regression/hetero_logistic_regression/hetero_lr_guest.py", line 66, in fit
     self._abnormal_detection(data_instances)
   File "./fate/python/federatedml/linear_model/linear_model_base.py", line 135, in _abnormal_detection
     abnormal_detection.empty_feature_detection(data_instances)
   File "./fate/python/federatedml/util/abnormal_detection.py", line 35, in empty_feature_detection
     raise ValueError(f"Number of features of DTable is 0: {data_instances}")
 ValueError: Number of features of DTable is 0: <fate_arch.computing.standalone._table.Table object at 0x7f6193df0080>

**Comment by mgqa34** [comment]
请确认guest方的特征数据存在，guest数据应该包含y&X

**Comment by Chuang007** [comment]
> 请确认guest方的特征数据存在，guest数据应该包含y&X

好的，感谢，确实如此
