### ISSUE TITLE
raise ValueError(f"Count of data_instance is 0: {data_instances}")

### ISSUE THREAD

**Issue by Chuang007** [FederatedAI/FATE#4352]
Traceback (most recent call last):
12
  File "/data/projects/fate/python/fate_flow/operation/task_executor.py", line 168, in run_task
13
    run_object.run(component_parameters_on_party, task_run_args)
14
  File "/data/projects/fate/python/federatedml/model_base.py", line 101, in run
15
    this_data_output = func(*params)
16
  File "/data/projects/fate/python/federatedml/linear_model/logistic_regression/hetero_logistic_regression/hetero_lr_guest.py", line 66, in fit
17
    self._abnormal_detection(data_instances)
18
  File "/data/projects/fate/python/federatedml/linear_model/linear_model_base.py", line 134, in _abnormal_detection
19
    abnormal_detection.empty_table_detection(data_instances)
20
  File "/data/projects/fate/python/federatedml/util/abnormal_detection.py", line 29, in empty_table_detection
21
    raise ValueError(f"Count of data_instance is 0: {data_instances}")
22
ValueError: Count of data_instance is 0: <fate_arch.computing.eggroll._table.Table object at 0x7f7555f33a58>
23
[INFO] [2022-09-29 15:42:18,320] [12272:140142826792768] - task_executor.py[line:313]: report task 2022092915411697145369_hetero_lr_0 0 guest 8887 to driver
24
[INFO] [2022-09-29 15:42:18,320] [12272:140142826792768] - control_client.py[line:42]: request update job 2022092915411697145369 task 2022092915411697145369_hetero_lr_0 0 on guest 8887
25
[INFO] [2022-09-29 15:42:18,363] [12272:140142826792768] - task_executor.py[line:202]: task 2022092915411697145369_hetero_lr_0 guest 8887 start time: 2022-09-29 15:42:15
26
[INFO] [2022-09-29 15:42:18,364] [12272:140142826792768] - task_executor.py[line:204]: task 2022092915411697145369_hetero_lr_0 guest 8887 end time: 2022-09-29 15:42:18
27
[INFO] [2022-09-29 15:42:18,364] [12272:140142826792768] - task_executor.py[line:206]: task 2022092915411697145369_hetero_lr_0 guest 8887 takes 3.144s
28
[INFO] [2022-09-29 15:42:18,364] [12272:140142826792768] - task_executor.py[line:209]: Finish 2022092915411697145369 hetero_lr_0 2022092915411697145369_hetero_lr_0 0 guest 8887 task failed
29
[INFO] [2022-09-29 15:42:18,364] [12272:140142826792768] - task_executor.py[line:313]: report task 2022092915411697145369_hetero_lr_0 0 guest 8887 to driver
30
[INFO] [2022-09-29 15:42:18,364] [12272:140142826792768] - control_client.py[line:42]: request update job 2022092915411697145369 task 2022092915411697145369_hetero_lr_0 0 on guest 8887

**Comment by Chuang007** [comment]
> Input data of guest party in hetero_lr component is empty, have a check at hetero_lr's upstream component's data output.

好的，谢谢
