### ISSUE TITLE
failed of homo_nn pipiline examples

### ISSUE THREAD

**Issue by Jason-wwww** [FederatedAI/FATE#4402]
**Describe the bug**
Failed while run `python ${pipeline_script}` under the folder `examples/pipeline/homo_nn`.

Output of log are as follows:
`root@b7f4830af662:/data/projects/fate/examples/pipeline/homo_nn# python pipeline_homo_nn_single_layer.py
2022-10-27 05:23:14.454988: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-10-27 05:23:16.018002: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-10-27 05:23:16.018052: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-10-27 05:23:16.181231: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-10-27 05:23:19.273994: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2022-10-27 05:23:19.274233: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2022-10-27 05:23:19.274265: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2022-10-27 05:23:22.928514: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-10-27 05:23:22.930443: W tensorflow/stream_executor/cuda/cuda_driver.cc:263] failed call to cuInit: UNKNOWN ERROR (303)
2022-10-27 05:23:22.930504: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] no NVIDIA GPU device is present: /dev/nvidia0 does not exist
2022-10-27 05:23:22.934063: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-10-27 05:23:25.004 | INFO     | pipeline.utils.invoker.job_submitter:monitor_job_status:83 - Job id is 202210270523231248410
                  Job is still waiting, time elapse: 0:00:01
2022-10-27 05:23:28Running component reader_0, time elapse: 0:00:10
2022-10-27 05:23:38.234 | ERROR    | __main__:run_homo_nn_pipeline:86 - An error has been caught in function 'run_homo_nn_pipeline', process 'MainProcess' (95060), thread 'MainThread' (140638048089920):
Traceback (most recent call last):

  File "pipeline_homo_nn_single_layer.py", line 137, in <module>
    main()
    └ <function main at 0x7fe8d8d7b1f0>

  File "pipeline_homo_nn_single_layer.py", line 42, in main
    run_homo_nn_pipeline(config, namespace, dataset.breast, homo_nn_0, 1)
    │                    │       │          │       │       └ <pipeline.component.homo_nn.HomoNN object at 0x7fe86b57a670>
    │                    │       │          │       └ <property object at 0x7fe8d8bfae00>
    │                    │       │          └ <class '__main__.dataset'>
    │                    │       └ ''
    │                    └ '../../config.yaml'
    └ <function run_homo_nn_pipeline at 0x7fe86b571700>

> File "pipeline_homo_nn_single_layer.py", line 86, in run_homo_nn_pipeline
    pipeline.fit()
    │        └ <function PipeLine.fit at 0x7fe8d77fb790>
    └ <pipeline.backend.pipeline.PipeLine object at 0x7fe864140340>

  File "/usr/local/lib/python3.8/site-packages/pipeline/backend/pipeline.py", line 573, in fit
    self._fit_status = self._job_invoker.monitor_job_status(self._train_job_id,
    │    │             │    │            │                  │    └ '202210270523231248410'
    │    │             │    │            │                  └ <pipeline.backend.pipeline.PipeLine object at 0x7fe864140340>
    │    │             │    │            └ <function JobInvoker.monitor_job_status at 0x7fe8d7871af0>
    │    │             │    └ <pipeline.utils.invoker.job_submitter.JobInvoker object at 0x7fe864140460>
    │    │             └ <pipeline.backend.pipeline.PipeLine object at 0x7fe864140340>
    │    └ None
    └ <pipeline.backend.pipeline.PipeLine object at 0x7fe864140340>
  File "/usr/local/lib/python3.8/site-packages/pipeline/utils/invoker/job_submitter.py", line 94, in monitor_job_status
    raise ValueError(f"Job is failed, please check out job {job_id} by fate board or fate_flow cli")

ValueError: Job is failed, please check out job 202210270523231248410 by fate board or fate_flow cli
Traceback (most recent call last):
  File "pipeline_homo_nn_single_layer.py", line 137, in <module>
    main()
  File "pipeline_homo_nn_single_layer.py", line 42, in main
    run_homo_nn_pipeline(config, namespace, dataset.breast, homo_nn_0, 1)
  File "pipeline_homo_nn_single_layer.py", line 86, in run_homo_nn_pipeline
    pipeline.fit()
  File "/usr/local/lib/python3.8/site-packages/loguru/_logger.py", line 1226, in catch_wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pipeline/backend/pipeline.py", line 573, in fit
    self._fit_status = self._job_invoker.monitor_job_status(self._train_job_id,
  File "/usr/local/lib/python3.8/site-packages/pipeline/utils/invoker/job_submitter.py", line 94, in monitor_job_status
    raise ValueError(f"Job is failed, please check out job {job_id} by fate board or fate_flow cli")
ValueError: Job is failed, please check out job 202210270523231248410 by fate board or fate_flow cli`

**Desktop (please complete the following information):**
 - OS: ubuntu18.04
 - Kubefate Version 1.9.0

**Comment by mgqa34** [comment]
Please show the error messages  of job "202210270523231248410" where fate_flow server is deployed.

**Comment by Jason-wwww** [comment]
> Please show the error messages of job "202210270523231248410" where fate_flow server is deployed.

I have pasted the full error log, pls refer the above.

**Comment by mgqa34** [comment]
> > Please show the error messages of job "202210270523231248410" where fate_flow server is deployed.
> 
> I have pasted the full error log, pls refer the above.

The error log you pasted is client side's error, not server side.

**Comment by amyseoj1** [comment]
> 

Hello, I have the same issue. Did you manage to resolve ?

**Comment by amyseoj1** [comment]
> > Please show the error messages of job "202210270523231248410" where fate_flow server is deployed.
> 
> I have pasted the full error log, pls refer the above.

Hello, I have the same issue. Did you manage to resolve ?
