### ISSUE TITLE
pyarrow连不上hdfs_fate on spark1.9

### ISSUE THREAD

**Issue by RicardoNing** [FederatedAI/FATE#4425]
Bug: [ERROR] - [task_executor._run_] [line:265]: Prior attempt to load libhdfs failed

本人有严格按照官网指示进行部署，但不清楚是否依赖关系存在问题，先提供以下可能有用信息：
1. 如图
![image](https://user-images.githubusercontent.com/51332003/200786383-c5bc3a76-f99a-4681-af34-094ae3cd8a02.png)

具体bug信息：
1
[ERROR] [2022-11-08 19:41:22,903] [202211081941144659660] [106289:139876149192512] - [task_executor._run_] [line:265]: Prior attempt to load libhdfs failed
2
Traceback (most recent call last):
3
  File "/data/projects/fate/fateflow/python/fate_flow/worker/task_executor.py", line 209, in _run_
4
    cpn_output = run_object.run(cpn_input)
5
  File "/data/projects/fate/fateflow/python/fate_flow/components/_base.py", line 156, in run
6
    self._run(cpn_input=cpn_input)
7
  File "/data/projects/fate/fateflow/python/fate_flow/components/upload.py", line 234, in _run
8
    self.table = storage_session.create_table(address=address, origin=StorageTableOrigin.UPLOAD, **self.parameters)
9
  File "/data/projects/fate/fate/python/fate_arch/storage/_session.py", line 39, in create_table
10
    table = self.table(address=address, name=name, namespace=namespace, partitions=partitions, **kwargs)
11
  File "/data/projects/fate/fate/python/fate_arch/storage/hdfs/_session.py", line 29, in table
12
    return StorageTable(address=address, name=name, namespace=namespace,
13
  File "/data/projects/fate/fate/python/fate_arch/storage/hdfs/_table.py", line 55, in __init__
14
    self._hdfs_client = fs.HadoopFileSystem.from_uri(self.path)
15
  File "pyarrow/_hdfs.pyx", line 126, in pyarrow._hdfs.HadoopFileSystem.from_uri
16
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
17
  File "pyarrow/error.pxi", line 114, in pyarrow.lib.check_status
18
OSError: Prior attempt to load libhdfs failed

**Comment by RicardoNing** [comment]
> hadoop用的是哪个版本哪？app用户的环境变量贴下？

1hadoop 是3.2
2环境变量如下
2.1
![image](https://user-images.githubusercontent.com/51332003/200997947-dcd00df9-3295-4f53-9c33-651417a8f110.png)
2.2
![image](https://user-images.githubusercontent.com/51332003/200998046-02782e87-2628-466c-bd84-e5a1326a0d5c.png)

方便话可加我微信：RicardoNjw

**Comment by paulbaogang** [comment]
hadoop 3.2.0版本应该是有点问题，hadoop/lib/native目录没有libhdfs.so文件，换3.3.1版本试试，测试了下换版本可以上传

**Comment by NingJingwen** [comment]
> hadoop 3.2.0版本应该是有点问题，hadoop/lib/native目录没有libhdfs.so文件，换3.3.1版本试试，测试了下换版本可以上传

你切换版本后有遇到resourcemanager都是standby的情况吗
