### ISSUE TITLE
Object of type float32 is not JSON serializable when compiling HomoNN pipeline

### ISSUE THREAD

**Issue by hari5g900** [FederatedAI/FATE#4468]
**Describe the bug**

Following [these ](https://fate.readthedocs.io/en/latest/tutorial/pipeline/pipeline_tutorial_homo_nn/#homo-nn) instructions to test out homo NN pipeline. I have a two party federation 8888 and 10000 running on different physical machines in the same subnet. I can run the hetero_secure_boost example notebook without issue from 8888.

I'm running into a type-error when running pipeline.compile();
`TypeError: Object of type float32 is not JSON serializable`

**To Reproduce**
Upload breast_homo_host/guest csv to each party using pipeline_tutorial_upload notebook
Then,
```
from pipeline.backend.pipeline import PipeLine
from pipeline.component import DataTransform
from pipeline.component import Reader
from pipeline.component import HomoNN
from pipeline.interface import Data

pipeline = PipeLine() \
        .set_initiator(role='guest', party_id=8888) \
        .set_roles(guest=8888, host=[10000], arbiter=10000)

reader_0 = Reader(name="reader_0")
# set guest parameter
reader_0.get_party_instance(role='guest', party_id=8888).component_param(
    table={"name": "breast_homo_guest", "namespace": "experiment"})
# set host parameter
reader_0.get_party_instance(role='host', party_id=10000).component_param(
    table={"name": "breast_homo_host", "namespace": "experiment"})

data_transform_0 = DataTransform(name="data_transform_0", with_label=True)
# set guest parameter
data_transform_0.get_party_instance(role='guest', party_id=8888).component_param(
    with_label=True)
data_transform_0.get_party_instance(role='host', party_id=[10000]).component_param(
    with_label=True)

homo_nn_0 = HomoNN(
    name="homo_nn_0", 
    max_iter=10, 
    batch_size=-1, 
    early_stop={"early_stop": "diff", "eps": 0.0001})
from tensorflow.keras.layers import Dense
homo_nn_0.add(
    Dense(units=1, input_shape=(10,), activation="sigmoid"))

from tensorflow.keras import optimizers
homo_nn_0.compile(
    optimizer=optimizers.Adam(learning_rate=0.05), 
    metrics=["accuracy", "AUC"],
    loss="binary_crossentropy")

pipeline.add_component(reader_0)
pipeline.add_component(data_transform_0, data=Data(data=reader_0.output.data))
pipeline.add_component(homo_nn_0, data=Data(train_data=data_transform_0.output.data))

pipeline.compile();
```
Full error:
```

2022-11-21 15:00:01.766 | ERROR    | __main__:<module>:1 - An error has been caught in function '<module>', process 'MainProcess' (668), thread 'MainThread' (139635126028096):
Traceback (most recent call last):

  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': 'Entry point for launching an IPython kernel.\n\nThis is separate from the ipykernel pack...
           │         └ <code object <module> at 0x7eff55f27a80, file "/usr/local/lib/python3.8/site-packages/ipykernel_launcher.py", line 1>
           └ <function _run_code at 0x7eff55ef4dc0>
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': 'Entry point for launching an IPython kernel.\n\nThis is separate from the ipykernel pack...
         └ <code object <module> at 0x7eff55f27a80, file "/usr/local/lib/python3.8/site-packages/ipykernel_launcher.py", line 1>
  File "/usr/local/lib/python3.8/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
    │   └ <bound method Application.launch_instance of <class 'ipykernel.kernelapp.IPKernelApp'>>
    └ <module 'ipykernel.kernelapp' from '/usr/local/lib/python3.8/site-packages/ipykernel/kernelapp.py'>
  File "/usr/local/lib/python3.8/site-packages/traitlets/config/application.py", line 978, in launch_instance
    app.start()
    │   └ <function IPKernelApp.start at 0x7eff518f51f0>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x7eff56019be0>
  File "/usr/local/lib/python3.8/site-packages/ipykernel/kernelapp.py", line 712, in start
    self.io_loop.start()
    │    │       └ <function BaseAsyncIOLoop.start at 0x7eff53809790>
    │    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7eff51918280>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x7eff56019be0>
  File "/usr/local/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 215, in start
    self.asyncio_loop.run_forever()
    │    │            └ <function BaseEventLoop.run_forever at 0x7eff5572bc10>
    │    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7eff51918280>
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7eff55730790>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7eff55825550>
    └ <Handle <TaskWakeupMethWrapper object at 0x7eff531d53a0>(<Future finis...300>, ...],))>)>
  File "/usr/local/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskWakeupMethWrapper object at 0x7eff531d53a0>(<Future finis...300>, ...],))>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskWakeupMethWrapper object at 0x7eff531d53a0>(<Future finis...300>, ...],))>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskWakeupMethWrapper object at 0x7eff531d53a0>(<Future finis...300>, ...],))>)>
  File "/usr/local/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
          │    └ <function Kernel.process_one at 0x7eff524d9430>
          └ <ipykernel.ipkernel.IPythonKernel object at 0x7eff51918e20>
  File "/usr/local/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 499, in process_one
    await dispatch(*args)
          │         └ ([<zmq.sugar.frame.Frame object at 0x7eff508d8bf0>, <zmq.sugar.frame.Frame object at 0x7eff5005ba90>, <zmq.sugar.frame.Frame ...
          └ <bound method Kernel.dispatch_shell of <ipykernel.ipkernel.IPythonKernel object at 0x7eff51918e20>>
  File "/usr/local/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
    await result
          └ <coroutine object Kernel.execute_request at 0x7eff5191a740>
  File "/usr/local/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
                          └ <coroutine object IPythonKernel.do_execute at 0x7eff5191abc0>
  File "/usr/local/lib/python3.8/site-packages/ipykernel/ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
          │     └ <function ZMQInteractiveShell.run_cell at 0x7eff51959a60>
          └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x7eff508a3b50>
  File "/usr/local/lib/python3.8/site-packages/ipykernel/zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
                             │       └ {'store_history': True, 'silent': False, 'cell_id': None}
                             └ ('pipeline.compile();',)
  File "/usr/local/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2885, in run_cell
    result = self._run_cell(
             │    └ <function InteractiveShell._run_cell at 0x7eff5309ea60>
             └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x7eff508a3b50>
  File "/usr/local/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2940, in _run_cell
    return runner(coro)
           │      └ <coroutine object InteractiveShell.run_cell_async at 0x7eff5191a940>
           └ <function _pseudo_sync_runner at 0x7eff5308f4c0>
  File "/usr/local/lib/python3.8/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
    │    └ <method 'send' of 'coroutine' objects>
    └ <coroutine object InteractiveShell.run_cell_async at 0x7eff5191a940>
  File "/usr/local/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3139, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
                       │    │             │        │     └ '/tmp/ipykernel_668/2135560493.py'
                       │    │             │        └ [<_ast.Expr object at 0x7eff531de100>]
                       │    │             └ <_ast.Module object at 0x7eff531de190>
                       │    └ <function InteractiveShell.run_ast_nodes at 0x7eff5309ed30>
                       └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x7eff508a3b50>
  File "/usr/local/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3318, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
             │    │        │     │              └ False
             │    │        │     └ <ExecutionResult object at 7eff531dee80, execution_count=8 error_before_exec=None error_in_exec=None info=<ExecutionInfo obje...
             │    │        └ <code object <module> at 0x7efe3c1f42f0, file "/tmp/ipykernel_668/2135560493.py", line 1>
             │    └ <function InteractiveShell.run_code at 0x7eff5309edc0>
             └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x7eff508a3b50>
  File "/usr/local/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3378, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
         │         │    │               │    └ {'__name__': '__main__', '__doc__': 'Automatically created module for IPython interactive environment', '__package__': None, ...
         │         │    │               └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x7eff508a3b50>
         │         │    └ <property object at 0x7eff530944f0>
         │         └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x7eff508a3b50>
         └ <code object <module> at 0x7efe3c1f42f0, file "/tmp/ipykernel_668/2135560493.py", line 1>

> File "/tmp/ipykernel_668/2135560493.py", line 1, in <module>
    pipeline.compile();
    │        └ <function PipeLine.compile at 0x7eff531cae50>
    └ <pipeline.backend.pipeline.PipeLine object at 0x7eff531d5820>

  File "/usr/local/lib/python3.8/site-packages/pipeline/backend/pipeline.py", line 416, in compile
    self._train_conf = self._construct_train_conf()
    │    │             │    └ <function PipeLine._construct_train_conf at 0x7eff531ca790>
    │    │             └ <pipeline.backend.pipeline.PipeLine object at 0x7eff531d5820>
    │    └ {'dsl_version': 2, 'initiator': {'role': 'guest', 'party_id': 8888}, 'role': {'guest': [8888], 'host': [10000], 'arbiter': [1...
    └ <pipeline.backend.pipeline.PipeLine object at 0x7eff531d5820>
  File "/usr/local/lib/python3.8/site-packages/pipeline/backend/pipeline.py", line 383, in _construct_train_conf
    LOGGER.debug(f"self._train_conf: \n {json.dumps(self._train_conf, indent=4, ensure_ascii=False)}")
    │      └ <function Logger.debug at 0x7eff4875eaf0>
    └ <loguru.logger handlers=[(id=1, level=20, sink=stderr), (id=2, level=20, sink='/usr/local/lib/python3.8/site-packages/pipelin...
  File "/usr/local/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
           └ <class 'json.encoder.JSONEncoder'>
  File "/usr/local/lib/python3.8/json/encoder.py", line 201, in encode
    chunks = list(chunks)
                  └ <generator object _make_iterencode.<locals>._iterencode at 0x7efe3fae47b0>
  File "/usr/local/lib/python3.8/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
               │                │  └ 0
               │                └ {'dsl_version': 2, 'initiator': {'role': 'guest', 'party_id': 8888}, 'role': {'guest': [8888], 'host': [10000], 'arbiter': [1...
               └ <function _make_iterencode.<locals>._iterencode_dict at 0x7eff531d3e50>
  File "/usr/local/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
               └ <generator object _make_iterencode.<locals>._iterencode_dict at 0x7efe3fae4b30>
  File "/usr/local/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
               └ <generator object _make_iterencode.<locals>._iterencode_dict at 0x7efe3fae4ac0>
  File "/usr/local/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
               └ <generator object _make_iterencode.<locals>._iterencode_dict at 0x7efe3fae4ba0>
  [Previous line repeated 2 more times]
  File "/usr/local/lib/python3.8/json/encoder.py", line 438, in _iterencode
    o = _default(o)
        │        └ 0.05
        └ <bound method JSONEncoder.default of <json.encoder.JSONEncoder object at 0x7eff531dee20>>
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '

TypeError: Object of type float32 is not JSON serializable
---------------------------------------------------------------------------
```
```
TypeError                                 Traceback (most recent call last)
Cell In [8], line 1
----> 1 pipeline.compile()

File /usr/local/lib/python3.8/site-packages/loguru/_logger.py:1226, in Logger.catch.<locals>.Catcher.__call__.<locals>.catch_wrapper(*args, **kwargs)
   1224 def catch_wrapper(*args, **kwargs):
   1225     with catcher:
-> 1226         return function(*args, **kwargs)
   1227     return default

File /usr/local/lib/python3.8/site-packages/pipeline/backend/pipeline.py:416, in PipeLine.compile(self)
    413 @LOGGER.catch(reraise=True)
    414 def compile(self):
    415     self._construct_train_dsl()
--> 416     self._train_conf = self._construct_train_conf()
    417     if self._stage == "predict":
    418         predict_pipeline = self._predict_pipeline[0]["pipeline"]

File /usr/local/lib/python3.8/site-packages/pipeline/backend/pipeline.py:383, in PipeLine._construct_train_conf(self)
    379             self._train_conf["component_parameters"]["role"] = {}
    380         self._train_conf["component_parameters"]["role"] = tools.merge_dict(
    381             role_param_conf, self._train_conf["component_parameters"]["role"])
--> 383 LOGGER.debug(f"self._train_conf: \n {json.dumps(self._train_conf, indent=4, ensure_ascii=False)}")
    384 return self._train_conf

File /usr/local/lib/python3.8/json/__init__.py:234, in dumps(obj, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, default, sort_keys, **kw)
    232 if cls is None:
    233     cls = JSONEncoder
--> 234 return cls(
    235     skipkeys=skipkeys, ensure_ascii=ensure_ascii,
    236     check_circular=check_circular, allow_nan=allow_nan, indent=indent,
    237     separators=separators, default=default, sort_keys=sort_keys,
    238     **kw).encode(obj)

File /usr/local/lib/python3.8/json/encoder.py:201, in JSONEncoder.encode(self, o)
    199 chunks = self.iterencode(o, _one_shot=True)
    200 if not isinstance(chunks, (list, tuple)):
--> 201     chunks = list(chunks)
    202 return ''.join(chunks)

File /usr/local/lib/python3.8/json/encoder.py:431, in _make_iterencode.<locals>._iterencode(o, _current_indent_level)
    429     yield from _iterencode_list(o, _current_indent_level)
    430 elif isinstance(o, dict):
--> 431     yield from _iterencode_dict(o, _current_indent_level)
    432 else:
    433     if markers is not None:

File /usr/local/lib/python3.8/json/encoder.py:405, in _make_iterencode.<locals>._iterencode_dict(dct, _current_indent_level)
    403         else:
    404             chunks = _iterencode(value, _current_indent_level)
--> 405         yield from chunks
    406 if newline_indent is not None:
    407     _current_indent_level -= 1

File /usr/local/lib/python3.8/json/encoder.py:405, in _make_iterencode.<locals>._iterencode_dict(dct, _current_indent_level)
    403         else:
    404             chunks = _iterencode(value, _current_indent_level)
--> 405         yield from chunks
    406 if newline_indent is not None:
    407     _current_indent_level -= 1

    [... skipping similar frames: _make_iterencode.<locals>._iterencode_dict at line 405 (2 times)]

File /usr/local/lib/python3.8/json/encoder.py:405, in _make_iterencode.<locals>._iterencode_dict(dct, _current_indent_level)
    403         else:
    404             chunks = _iterencode(value, _current_indent_level)
--> 405         yield from chunks
    406 if newline_indent is not None:
    407     _current_indent_level -= 1

File /usr/local/lib/python3.8/json/encoder.py:438, in _make_iterencode.<locals>._iterencode(o, _current_indent_level)
    436         raise ValueError("Circular reference detected")
    437     markers[markerid] = o
--> 438 o = _default(o)
    439 yield from _iterencode(o, _current_indent_level)
    440 if markers is not None:

File /usr/local/lib/python3.8/json/encoder.py:179, in JSONEncoder.default(self, o)
    160 def default(self, o):
    161     """Implement this method in a subclass such that it returns
    162     a serializable object for ``o``, or calls the base implementation
    163     (to raise a ``TypeError``).
   (...)
    177 
    178     """
--> 179     raise TypeError(f'Object of type {o.__class__.__name__} '
    180                     f'is not JSON serializable')

TypeError: Object of type float32 is not JSON serializable
```

**Desktop (please complete the following information):**
 - OS: Windows 
 - Servers: Ubuntu servers running kubeFATE v1.9.0
 - Browser: Chrome

**Comment by talkingwallace** [comment]
Thanks for your feedback,  I ll check this problem soon.

**Comment by talkingwallace** [comment]
hi！I can compile and submit your pipeline, everything seems OK. What is your tf/keras version?
![image](https://user-images.githubusercontent.com/10768970/203514470-f8623e70-223a-44c0-abb1-868e99b857af.png)

**Comment by pamystri** [comment]
Hi,

we are using the below:

root@client-0:/data/projects/fate# pip list | egrep -i "tensor|keras"
keras                        2.11.0
tensorboard                  2.11.0
tensorboard-data-server      0.6.1
tensorboard-plugin-wit       1.8.1
tensorflow                   2.11.0
tensorflow-estimator         2.11.0
tensorflow-io-gcs-filesystem 0.28.0

**Comment by talkingwallace** [comment]
hi! It seems that your tf version is not the same as the requirement.txt(in fate/python). Could you please re-install your environment following requirement.txt? Thanks!
