### ISSUE TITLE
ModuleNotFoundError: No module named 'fate_arch'

### ISSUE THREAD

**Issue by sweetboxwwy** [FederatedAI/FATE#4469]
源码部署单机版https://github.com/FederatedAI/FATE/blob/master/deploy/standalone-deploy/doc/standalone_fate_source_code_deployment_guide.zh.md

执行第6步 bash bin/service.sh start 报错

Traceback (most recent call last):
  File "/home/wangwy/PycharmProjects/Docker/FATE/fateflow/python/fate_flow/fate_flow_server.py", line 17, in <module>
    import fate_flow as _
  File "/home/wangwy/PycharmProjects/Docker/FATE/fateflow/python/fate_flow/__init__.py", line 18, in <module>
    from fate_flow.entity.types import ProcessRole
  File "/home/wangwy/PycharmProjects/Docker/FATE/fateflow/python/fate_flow/entity/__init__.py", line 16, in <module>
    from ._base import BaseEntity
  File "/home/wangwy/PycharmProjects/Docker/FATE/fateflow/python/fate_flow/entity/_base.py", line 16, in <module>
    from fate_arch.common import BaseType
ModuleNotFoundError: No module named 'fate_arch'
~

**Comment by sweetboxwwy** [comment]
> 请确认已经执行 source bin/init_env.sh，即第6步一开始要求执行的命令，如果还有问题，请echo $PYTHONPATH看下是否source没生效

已经执行了source这句，但是echo $PYTHONPATH的结果是：
其中FATE_PROJECT_BASE = /home/username/PycharmProjects/Docker/FATE

/home/username/PycharmProjects/Docker/FATE/python:/home/username/PycharmProjects/Docker/FATE/fateflow/python
