### ISSUE TITLE
example hetero nn algorithm error

### ISSUE THREAD

**Issue by nkhklholyf** [FederatedAI/FATE#4473]
尝试 hetero nn 算法，examples/pipeline/hetero_nn/pipeline-hetero-nn-train-binary.py 这个代码改了一下维度，使用 examples/data/default_credit_hetero 数据集，但是运行一段时间后报错

Traceback (most recent call last):
  File "/data/projects/fate/fateflow/python/fate_flow/worker/task_executor.py", line 209, in _run_
    cpn_output = run_object.run(cpn_input)
  File "/data/projects/fate/fate/python/federatedml/model_base.py", line 239, in run
    self._run(cpn_input=cpn_input)
  File "/data/projects/fate/fate/python/federatedml/model_base.py", line 318, in _run
    this_data_output = func(*params)
  File "/data/projects/fate/fate/python/federatedml/nn/hetero_nn/hetero_nn_guest.py", line 106, in fit
    batch_loss = self.model.train(self.data_x[batch_idx], self.data_y[batch_idx], cur_epoch, batch_idx)
  File "/data/projects/fate/fate/python/federatedml/nn/hetero_nn/model/hetero_nn_model.py", line 135, in train
    selective_ids, gradients, loss = self.top_model.train_and_get_backward_gradient(interactive_output, y)
  File "/data/projects/fate/fate/python/federatedml/nn/hetero_nn/model/hetero_nn_top_model.py", line 120, in train_and_get_backward_gradient
    input_gradient = self._model.get_input_gradients(x, y)[0]
  File "/data/projects/fate/fate/python/federatedml/nn/backend/tf_keras/nn_model.py", line 116, in get_input_gradients
    X = tf.constant(X)
  File "/data/projects/fate/env/python/venv/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 267, in constant
    return _constant_impl(value, dtype, shape, name, verify_shape=False,
  File "/data/projects/fate/env/python/venv/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 279, in _constant_impl
    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)
  File "/data/projects/fate/env/python/venv/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 304, in _constant_eager_impl
    t = convert_to_eager_tensor(value, ctx, dtype)
  File "/data/projects/fate/env/python/venv/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 102, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type float).

**Comment by mgqa34** [comment]
请附上修改后的pipeline文件，用于问题的复现

**Comment by nkhklholyf** [comment]
问题好像解决了，指定初始化方法就行了，如果使用 keras 默认的随机初始化好像容易出错
