### ISSUE TITLE
unsupported operand type(s) for /=: 'NoneType' and 'int'

### ISSUE THREAD

**Issue by Acecai** [FederatedAI/FATE#4524]
**Describe the bug**
```

[INFO] [2022-12-13 09:59:36,519] [202212130926415047440] [35619:140507320919872] - [homo_lr_host.fit] [line:122]: n_iters: 30, is_converge: False

[INFO] [2022-12-13 10:00:33,537] [202212130926415047440] [35619:140507320919872] - [checkpoint.save] [line:82]: Checkpoint saved. path: ./fate/fateflow/model_local_cache/host#9998#arbiter-10000#guest-9999#host-9998_10000#model/202212130926415047440/checkpoint/homo_lr_0/30#step_name

[INFO] [2022-12-13 10:00:34,085] [202212130926415047440] [35619:140507320919872] - [homo_lr_host.fit] [line:122]: n_iters: 31, is_converge: False

[ERROR] [2022-12-13 10:01:25,313] [202212130926415047440] [35619:140507320919872] - [task_executor._run_] [line:243]: unsupported operand type(s) for /=: 'NoneType' and 'int'

Traceback (most recent call last):

  File "./fate/fateflow/python/fate_flow/worker/task_executor.py", line 195, in _run_

    cpn_output = run_object.run(cpn_input)

  File "./fate/fate/python/federatedml/model_base.py", line 209, in run

    method(cpn_input)

  File "./fate/fate/python/federatedml/model_base.py", line 247, in _run

    this_data_output = func(*params)

  File "./fate/fate/python/federatedml/linear_model/logistic_regression/homo_logistic_regression/homo_lr_host.py", line 137, in fit

    grad /= n

TypeError: unsupported operand type(s) for /=: 'NoneType' and 'int'

[INFO] [2022-12-13 10:01:25,315] [202212130926415047440] [35619:140507320919872] - [task_base_worker.report_task_info_to_driver] [line:124]: report TaskExecutor 202212130926415047440_homo_lr_0 0 host 9998 to driver:

{'job_id': '202212130926415047440', 'component_name': 'homo_lr_0', 'task_id': '202212130926415047440_homo_lr_0', 'task_version': '0', 'role': 'host', 'party_id': '9998', 'run_ip': 'xxx.xxx', 'run_pid': 35619, 'party_status': 'failed', 'src_role': '', 'src_party_id': '', 'end_time': 1670925685315, 'elapsed': 1850712}

[INFO] [2022-12-13 10:01:25,315] [202212130926415047440] [35619:140507320919872] - [control_client.report_task] [line:41]: request update job 202212130926415047440 task 202212130926415047440_homo_lr_0 0 on host 9998

[INFO] [2022-12-13 10:01:25,431] [202212130926415047440] [35619:140507320919872] - [task_executor._run_] [line:254]: finish homo_lr_0 202212130926415047440_homo_lr_0 0 on host 9998 with failed

[INFO] [2022-12-13 10:01:25,432] [202212130926415047440] [35619:140507320919872] - [base_worker.run] [line:122]: worker TaskExecutor, process role: ProcessRole.WORKER, pid: 35619, elapsed: 1851427 ms

```
**Expected behavior**
when train a homo_lr model among 3 partys, this bug is reported on one of two host partys in the 31 epoch.  

**Screenshots**
![image](https://user-images.githubusercontent.com/12414008/207311996-3be542ad-8b0f-4f57-925f-e49ddb175ab7.png)

**Desktop (please complete the following information):**
 - OS: centos
 
**Additional context**
kubeFate : v1.7.2

**Comment by dylan-fan** [comment]
应该某一方在这一轮传输除了问题，返回了None

**Comment by Acecai** [comment]
本人将数据配置成partition*batch_size的整数倍后，不再发生该问题
