### ISSUE TITLE
A process in the process pool was terminated abruptly while the future was running or pending.

### ISSUE THREAD

**Issue by amyseoj1** [FederatedAI/FATE#4579]
Hello, How should I fix this error ? 

[ERROR] [2023-01-09 17:06:08,146] [202301091521353992680] [41925:274922721280] - [task_executor._run_] [line:265]: A process in the process pool was terminated abruptly while the future was running or pending.
2
Traceback (most recent call last):
4
    cpn_output = run_object.run(cpn_input)
5
  File "/data/projects/fate/fate/python/federatedml/model_base.py", line 239, in run
6
    self._run(cpn_input=cpn_input)
7
  File "/data/projects/fate/fate/python/federatedml/model_base.py", line 315, in _run
8
    this_data_output = func(*real_param)
9
  File "/data/projects/fate/fate/python/federatedml/util/data_transform.py", line 1042, in fit
10
    data_inst = self.transformer.read_data(data, "fit")
11
  File "/data/projects/fate/fate/python/federatedml/util/data_transform.py", line 192, in read_data
12
    data_instance = self.fit(input_data, input_data_features, input_data_labels, input_data_match_id)
13
  File "/data/projects/fate/fate/python/federatedml/util/data_transform.py", line 205, in fit
14
    data_instance = self.gen_data_instance(input_data_features, input_data_labels, input_data_match_id)
15
  File "/data/projects/fate/fate/python/federatedml/util/data_transform.py", line 266, in gen_data_instance
16
    data_instance = input_data_features.mapValues(lambda features: self.to_instance(features))
17
  File "/data/projects/fate/fate/python/fate_arch/common/profile.py", line 318, in _fn
18
    rtn = func(*args, **kwargs)
19
  File "/data/projects/fate/fate/python/fate_arch/computing/standalone/_table.py", line 104, in mapValues
20
    return Table(self._table.mapValues(func))
21
  File "/data/projects/fate/fate/python/fate_arch/_standalone.py", line 155, in mapValues
22
    return self._unary(func, _do_map_values)
23
  File "/data/projects/fate/fate/python/fate_arch/_standalone.py", line 257, in _unary
24
    results = self._session._submit_unary(
25
  File "/data/projects/fate/fate/python/fate_arch/_standalone.py", line 440, in _submit_unary
26
    results = [r.result() for r in futures]
27
  File "/data/projects/fate/fate/python/fate_arch/_standalone.py", line 440, in <listcomp>
28
    results = [r.result() for r in futures]
29
  File "/data/projects/fate/env/python/miniconda/lib/python3.8/concurrent/futures/_base.py", line 444, in result
30
    return self.__get_result()
31
  File "/data/projects/fate/env/python/miniconda/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
32
    raise self._exception
33
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
34

**Comment by talkingwallace** [comment]
May I ask if this error can be reproduced stably, and under what circumstances will it appear?

**Comment by amyseoj1** [comment]
Hello, 
I cannot reproduce this error stably. I am running FATE v 1.9.0 on Mac M1 Max, and this error occurs at data_transform_0 upon completion of reader_0. This is a rare case, because job fails at reader_0 most of the time. Does the standalone version support Apple Silicon ?
<img width="301" alt="Screenshot 2023-01-11 at 02 04 07" src="https://user-images.githubusercontent.com/73941975/211701038-23bc3f06-0716-4297-bb46-06e192ed79fa.png">
