### ISSUE TITLE
Standalone部署模式下pipeline upload data报错

### ISSUE THREAD

**Issue by exitNA** [FederatedAI/FATE#4590]
**Describe the bug**
windows 10系统下，使用docker启动standalone模式，按照[pipeline upload data](https://github.com/FederatedAI/FATE/blob/master/doc/tutorial/pipeline/pipeline_tutorial_upload.ipynb) 运行上传数据，报如下错误
`
ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', None, 10053, None)
`
**To Reproduce**
1. windows terminal里执行`docker run --rm -it --name fate_local -p 8080:8080 -p 9380:9380 -p 9360:9360 federatedai/standalone_fate:1.10.0`启动fate
2. git克隆fate代码
3. 创建demo目录并进入
4. 创建upt.py，拷贝python代码 [pipeline_tutorial_upload.ipynb](https://github.com/FederatedAI/FATE/blob/master/doc/tutorial/pipeline/pipeline_tutorial_upload.ipynb)
5. 按顺序执行代码，报错
```
 UPLOADING:||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||100.00%2023-01-16 10:17:31.149 | ERROR    | __main__:<module>:27 - An error has been caught in function '<module>', process 'MainProcess' (18732), thread 'MainThread' (3188):
Traceback (most recent call last):

  File "D:\opt\mamba\lib\site-packages\pipeline\utils\invoker\job_submitter.py", line 61, in upload_data
    raise ValueError

ValueError


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

> File "D:\work\fate-demo\upt.py", line 27, in <module>
    pipeline_upload.upload(drop=1)
    │               └ <function PipeLine.upload at 0x00000274A2625A20>
    └ <pipeline.backend.pipeline.PipeLine object at 0x0000027495A39F60>

  File "D:\opt\mamba\lib\site-packages\pipeline\backend\pipeline.py", line 664, in upload
    self._train_job_id, detail_info = self._job_invoker.upload_data(upload_conf, int(drop))
    │    │                            │    │            │           │                └ 1
    │    │                            │    │            │           └ {'file': 'D:/repo/FATE\\examples/data/breast_hetero_guest.csv', 'table_name': 'breast_hetero_guest', 'namespace': 'experiment...
    │    │                            │    │            └ <function JobInvoker.upload_data at 0x00000274A2620F70>
    │    │                            │    └ <pipeline.utils.invoker.job_submitter.JobInvoker object at 0x0000027495A3A2C0>
    │    │                            └ <pipeline.backend.pipeline.PipeLine object at 0x0000027495A39F60>
    │    └ None
    └ <pipeline.backend.pipeline.PipeLine object at 0x0000027495A39F60>

  File "D:\opt\mamba\lib\site-packages\pipeline\utils\invoker\job_submitter.py", line 69, in upload_data
    raise ValueError("job submit failed, err msg: {}".format(result))
                                                             └ {'retcode': 100, 'retmsg': "('Connection aborted.', ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', None, 10053, None))...

ValueError: job submit failed, err msg: {'retcode': 100, 'retmsg': "('Connection aborted.', ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', None, 10053, None))", 'traceback': ['Traceback (most recent call last):\n', '  File "D:\\opt\\mamba\\lib\\site-packages\\urllib3\\connectionpool.py", line 703, in urlopen\n    httplib_response = self._make_request(\n', '  File "D:\\opt\\mamba\\lib\\site-packages\\urllib3\\connectionpool.py", line 398, in _make_request\n    conn.request(method, url, **httplib_request_kw)\n', '  File "D:\\opt\\mamba\\lib\\site-packages\\urllib3\\connection.py", line 239, in request\n    super(HTTPConnection, self).request(method, url, body=body, headers=headers)\n', '  File "D:\\opt\\mamba\\lib\\http\\client.py", line 1282, in request\n    self._send_request(method, url, body, headers, encode_chunked)\n', '  File "D:\\opt\\mamba\\lib\\http\\client.py", line 1328, in _send_request\n    self.endheaders(body, encode_chunked=encode_chunked)\n', '  File "D:\\opt\\mamba\\lib\\http\\client.py", line 1277, in endheaders\n    self._send_output(message_body, encode_chunked=encode_chunked)\n', '  File "D:\\opt\\mamba\\lib\\http\\client.py", line 1076, in _send_output\n    self.send(chunk)\n', '  File "D:\\opt\\mamba\\lib\\http\\client.py", line 998, in send\n    self.sock.sendall(data)\n', 'ConnectionAbortedError: [WinError 10053] 你的主机中的软件中止了一个已建立的连接。\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "D:\\opt\\mamba\\lib\\site-packages\\requests\\adapters.py", line 489, in send\n    resp = conn.urlopen(\n', '  File "D:\\opt\\mamba\\lib\\site-packages\\urllib3\\connectionpool.py", line 787, in urlopen\n    retries = retries.increment(\n', '  File "D:\\opt\\mamba\\lib\\site-packages\\urllib3\\util\\retry.py", line 550, in increment\n    raise six.reraise(type(error), error, _stacktrace)\n', '  File "D:\\opt\\mamba\\lib\\site-packages\\urllib3\\packages\\six.py", line 769, in reraise\n    raise value.with_traceback(tb)\n', '  File "D:\\opt\\mamba\\lib\\site-packages\\urllib3\\connectionpool.py", line 703, in urlopen\n    httplib_response = self._make_request(\n', '  File "D:\\opt\\mamba\\lib\\site-packages\\urllib3\\connectionpool.py", line 398, in _make_request\n    conn.request(method, url, **httplib_request_kw)\n', '  File "D:\\opt\\mamba\\lib\\site-packages\\urllib3\\connection.py", line 239, in request\n    super(HTTPConnection, self).request(method, url, body=body, headers=headers)\n', '  File "D:\\opt\\mamba\\lib\\http\\client.py", line 1282, in request\n    self._send_request(method, url, body, headers, encode_chunked)\n', '  File "D:\\opt\\mamba\\lib\\http\\client.py", line 1328, in _send_request\n    self.endheaders(body, encode_chunked=encode_chunked)\n', '  File "D:\\opt\\mamba\\lib\\http\\client.py", line 1277, in endheaders\n    self._send_output(message_body, encode_chunked=encode_chunked)\n', '  File "D:\\opt\\mamba\\lib\\http\\client.py", line 1076, in _send_output\n    self.send(chunk)\n', '  File "D:\\opt\\mamba\\lib\\http\\client.py", line 998, in send\n    self.sock.sendall(data)\n', "urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', None, 10053, None))\n", '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "D:\\opt\\mamba\\lib\\site-packages\\flow_sdk\\client\\base.py", line 81, in _request\n    response = self._http.send(prepped, stream=stream)\n', '  File "D:\\opt\\mamba\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "D:\\opt\\mamba\\lib\\site-packages\\requests\\adapters.py", line 547, in send\n    raise ConnectionError(err, request=request)\n', "requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionAbortedError(10053, '你的主机中的软件中止 了一个已建立的连接。', None, 10053, None))\n"]}
Traceback (most recent call last):
  File "D:\opt\mamba\lib\site-packages\pipeline\utils\invoker\job_submitter.py", line 61, in upload_data
    raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\work\fate-demo\upt.py", line 27, in <module>
    pipeline_upload.upload(drop=1)
  File "D:\opt\mamba\lib\site-packages\loguru\_logger.py", line 1226, in catch_wrapper
    return function(*args, **kwargs)
  File "D:\opt\mamba\lib\site-packages\pipeline\backend\pipeline.py", line 664, in upload
    self._train_job_id, detail_info = self._job_invoker.upload_data(upload_conf, int(drop))
  File "D:\opt\mamba\lib\site-packages\pipeline\utils\invoker\job_submitter.py", line 69, in upload_data
    raise ValueError("job submit failed, err msg: {}".format(result))
ValueError: job submit failed, err msg: {'retcode': 100, 'retmsg': "('Connection aborted.', ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', None, 10053, None))", 'traceback': ['Traceback (most recent call last):\n', '  File "D:\\opt\\mamba\\lib\\site-packages\\urllib3\\connectionpool.py", line 703, in urlopen\n    httplib_response = self._make_request(\n', '  File "D:\\opt\\mamba\\lib\\site-packages\\urllib3\\connectionpool.py", line 398, in _make_request\n    conn.request(method, url, **httplib_request_kw)\n', '  File "D:\\opt\\mamba\\lib\\site-packages\\urllib3\\connection.py", line 239, in request\n    super(HTTPConnection, self).request(method, url, body=body, headers=headers)\n', '  File "D:\\opt\\mamba\\lib\\http\\client.py", line 1282, in request\n    self._send_request(method, url, body, headers, encode_chunked)\n', '  File "D:\\opt\\mamba\\lib\\http\\client.py", line 1328, in _send_request\n    self.endheaders(body, encode_chunked=encode_chunked)\n', '  File "D:\\opt\\mamba\\lib\\http\\client.py", line 1277, in endheaders\n    self._send_output(message_body, encode_chunked=encode_chunked)\n', '  File "D:\\opt\\mamba\\lib\\http\\client.py", line 1076, in _send_output\n    self.send(chunk)\n', '  File "D:\\opt\\mamba\\lib\\http\\client.py", line 998, in send\n    self.sock.sendall(data)\n', 'ConnectionAbortedError: [WinError 10053] 你的主机中的软件中止了一个已建立的连接。\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "D:\\opt\\mamba\\lib\\site-packages\\requests\\adapters.py", line 489, in send\n    resp = conn.urlopen(\n', '  File "D:\\opt\\mamba\\lib\\site-packages\\urllib3\\connectionpool.py", line 787, in urlopen\n    retries = retries.increment(\n', '  File "D:\\opt\\mamba\\lib\\site-packages\\urllib3\\util\\retry.py", line 550, in increment\n    raise six.reraise(type(error), error, _stacktrace)\n', '  File "D:\\opt\\mamba\\lib\\site-packages\\urllib3\\packages\\six.py", line 769, in reraise\n    raise value.with_traceback(tb)\n', '  File "D:\\opt\\mamba\\lib\\site-packages\\urllib3\\connectionpool.py", line 703, in urlopen\n    httplib_response = self._make_request(\n', '  File "D:\\opt\\mamba\\lib\\site-packages\\urllib3\\connectionpool.py", line 398, in _make_request\n    conn.request(method, url, **httplib_request_kw)\n', '  File "D:\\opt\\mamba\\lib\\site-packages\\urllib3\\connection.py", line 239, in request\n    super(HTTPConnection, self).request(method, url, body=body, headers=headers)\n', '  File "D:\\opt\\mamba\\lib\\http\\client.py", line 1282, in request\n    self._send_request(method, url, body, headers, encode_chunked)\n', '  File "D:\\opt\\mamba\\lib\\http\\client.py", line 1328, in _send_request\n    self.endheaders(body, encode_chunked=encode_chunked)\n', '  File "D:\\opt\\mamba\\lib\\http\\client.py", line 1277, in endheaders\n    self._send_output(message_body, encode_chunked=encode_chunked)\n', '  File "D:\\opt\\mamba\\lib\\http\\client.py", line 1076, in _send_output\n    self.send(chunk)\n', '  File "D:\\opt\\mamba\\lib\\http\\client.py", line 998, in send\n    self.sock.sendall(data)\n', "urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', None, 10053, None))\n", '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "D:\\opt\\mamba\\lib\\site-packages\\flow_sdk\\client\\base.py", line 81, in _request\n    response = self._http.send(prepped, stream=stream)\n', '  File "D:\\opt\\mamba\\lib\\site-packages\\requests\\sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n', '  File "D:\\opt\\mamba\\lib\\site-packages\\requests\\adapters.py", line 547, in send\n    raise ConnectionError(err, request=request)\n', "requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionAbortedError(10053, '你的主机中的软件中止 了一个已建立的连接。', None, 10053, None))\n"]}
```
**upt.py代码**
```python
import os
from pipeline.backend.pipeline import PipeLine


pipeline_upload = PipeLine().set_initiator(role='guest', party_id=9999).set_roles(guest=9999)
partition = 4
dense_data_guest = {"name": "breast_hetero_guest", "namespace": f"experiment"}
dense_data_host = {"name": "breast_hetero_host", "namespace": f"experiment"}
tag_data = {"name": "breast_hetero_host", "namespace": f"experiment"}

data_base = "D:/repo/FATE"

pipeline_upload.add_upload_data(file=os.path.join(data_base, "examples/data/breast_hetero_guest.csv"),
                                table_name=dense_data_guest["name"],             # table name
                                namespace=dense_data_guest["namespace"],         # namespace
                                head=1, partition=partition)               # data info

pipeline_upload.add_upload_data(file=os.path.join(data_base, "examples/data/breast_hetero_host.csv"),
                                table_name=dense_data_host["name"],
                                namespace=dense_data_host["namespace"],
                                head=1, partition=partition)

pipeline_upload.add_upload_data(file=os.path.join(data_base, "examples/data/breast_hetero_host.csv"),
                                table_name=tag_data["name"],
                                namespace=tag_data["namespace"],
                                head=1, partition=partition)
pipeline_upload.upload(drop=1)
```
**Desktop (please complete the following information):**
 - OS: windows 10
 - Version: federatedai/standalone_fate:1.10.0
 - client: python 3.10, notebook

**Comment by mgqa34** [comment]
看起来是与flow建立的连接请求有问题，通过flow data upload -c 指令上传数据是否ok呢？

**Comment by exitNA** [comment]
现在发现在容器里执行代码可以成功，在容器外执行失败，因该是9380端口没有映射到宿主机上。
