### ISSUE TITLE
在纵向联邦分箱时，guest端不报错，host端报：TypeError: Object of type int64 is not JSON serializable

### ISSUE THREAD

**Issue by paw-zhao** [FederatedAI/FATE#4742]
Traceback (most recent call last):
  File "/data/projects/fate/fateflow/python/fate_flow/worker/task_executor.py", line 209, in _run_
    cpn_output = run_object.run(cpn_input)
  File "/data/projects/fate/fate/python/federatedml/model_base.py", line 239, in run
    self._run(cpn_input=cpn_input)
  File "/data/projects/fate/fate/python/federatedml/model_base.py", line 332, in _run
    self.save_summary()

    self.tracker.log_component_summary(summary_data=self.summary())
    File "/data/projects/fate/fate/python/federatedml/model_base.py", line 145, in log_component_summary
    return self._tracker.log_component_summary(summary_data=summary_data)
  File "/data/projects/fate/fateflow/python/fate_flow/scheduling_apps/client/tracker_client.py", line 289, in log_component_summary
    response = api_utils.local_api(job_id=self.job_id,
  File "/data/projects/fate/fateflow/python/fate_flow/utils/api_utils.py", line 165, in local_api
    return federated_api(
  File "/data/projects/fate/fateflow/python/fate_flow/utils/api_utils.py", line 144, in federated_api
    return federated_coordination_on_http(**kwargs)
  File "/data/projects/fate/fateflow/python/fate_flow/utils/api_utils.py", line 244, in federated_coordination_on_http
    raise e
  File "/data/projects/fate/fateflow/python/fate_flow/utils/api_utils.py", line 236, in federated_coordination_on_http
    response = request(
  File "/data/projects/fate/fateflow/python/fate_flow/utils/requests_utils.py", line 38, in request
    prepped = requests.Request(**kwargs).prepare()
  File "/data/projects/fate/common/python/venv/lib/python3.8/site-packages/requests/models.py", line 257, in prepare
    p.prepare(
    self.prepare_body(data, files, json)
    body = complexjson.dumps(json)
  File "/data/projects/common/miniconda3/lib/python3.8/json/__init__.py", line 234, in dumps
  File "/data/projects/common/miniconda3/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
    return json.JSONEncoder.default(self, obj)
  File "/data/projects/common/miniconda3/lib/python3.8/json/encoder.py", line 179, in default

TypeError: Object of type int64 is not JSON serializable

**Comment by mgqa34** [comment]
请问这个是哪个组件的summary报错？

**Comment by mgqa34** [comment]
请问是哪一个版本呢？ 另外是否方便贴一下任务的相关配置，我们尝试复现下
