### ISSUE TITLE
模型导出后，import再导入报错

### ISSUE THREAD

**Issue by DingDante** [FederatedAI/FATE#4842]
报错 {
            "retcode": 100,
             "retmsg": "ValueError(\"invalid literal for int() with base 10: 'False'\")"
        }

配置文件
       {
    "role": "guest",
    "party_id": 9999,
    "model_id": "guest-9999#host-10000#model",
    "model_version": "202305151600464531880",
    "file": "/root/standalone_fate_install_1.10.0_release/fateflow/temp/guest#9999#guest-9999#host-10000#model_202305151600464531880.zip",
    "force_update": false
}

**Comment by zhihuiwan** [comment]
可以看看具体报错日志，logs/fate_flow/ERROR.log里面

**Comment by DingDante** [comment]
> 可以看看具体报错日志，logs/fate_flow/ERROR.log里面

[ERROR] [2023-05-22 20:56:12,552] [Server] [2909:140654896551680] - [api_utils.server_error_response] [line:94]: invalid literal for int() with base 10: 'False'
Traceback (most recent call last):
  File "/root/standalone_fate_install_1.10.0_release/env/python/venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/standalone_fate_install_1.10.0_release/env/python/venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/root/standalone_fate_install_1.10.0_release/fateflow/python/fate_flow/utils/api_utils.py", line 394, in decorated_function
    return func(*_args, **_kwargs)
  File "/root/standalone_fate_install_1.10.0_release/fateflow/python/fate_flow/apps/model_app.py", line 334, in operate_model
    force_update = bool(int(request_config.get('force_update', 0)))
ValueError: invalid literal for int() with base 10: 'False'
[ERROR] [2023-05-22 21:06:36,075] [Server] [2909:140654374008576] - [api_utils.server_error_response] [line:94]: invalid literal for int() with base 10: 'False'
Traceback (most recent call last):
  File "/root/standalone_fate_install_1.10.0_release/env/python/venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/standalone_fate_install_1.10.0_release/env/python/venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/root/standalone_fate_install_1.10.0_release/fateflow/python/fate_flow/utils/api_utils.py", line 394, in decorated_function
    return func(*_args, **_kwargs)
  File "/root/standalone_fate_install_1.10.0_release/fateflow/python/fate_flow/apps/model_app.py", line 334, in operate_model
    force_update = bool(int(request_config.get('force_update', 0)))
ValueError: invalid literal for int() with base 10: 'False'
这里是不是需要在import.json中删掉"force_update": false呢，
