### ISSUE TITLE
BUG: Hetero FTL job failed in federated FATE cluster (spark+pulsar)

### ISSUE THREAD

**Issue by ArtiPyHeart** [FederatedAI/FATE#4859]
**Describe the bug**
The Hetero FTL job example in FATE/examples/dsl/v2/hetero_ftl/ cannot finish hetero ftl module after submit FTL job.
<img width="317" alt="图片" src="https://github.com/FederatedAI/FATE/assets/24668142/57858323-6f16-479a-94a2-58b6c21cdac5">

**Version**
FATE: v.1.10.0
with tensorflow == 2.9.3

**To Reproduce**
1. Deploy two FATE clusters to k8s using KubeFATE cluster-spark-pulsar.yaml manifest
2. upload example data from FATE/examples/data
3. submit test_ftl_conf.json and test_ftl_dsl.json from FATE/examples/dsl/v2/hetero_ftl/
4. See error on FATE board

**First Time Error**
At first, I got a kwargs error as following:

```shell
[ERROR] [2023-05-25 04:03:51,730] [202305250352299319300] [15503:139784135386944] - [task_executor._run_] [line:265]: '<' not supported between instances of 'str' and 'int'
Traceback (most recent call last):
  File "/data/projects/fate/fateflow/python/fate_flow/worker/task_executor.py", line 209, in _run_
    cpn_output = run_object.run(cpn_input)
  File "/data/projects/fate/fate/python/federatedml/model_base.py", line 239, in run
    self._run(cpn_input=cpn_input)
  File "/data/projects/fate/fate/python/federatedml/model_base.py", line 318, in _run
    this_data_output = func(*params)
  File "/data/projects/fate/fate/python/federatedml/transfer_learning/hetero_ftl/ftl_guest.py", line 288, in fit
    self.initialize_nn(input_shape=self.x_shape)
  File "/data/projects/fate/fate/python/federatedml/transfer_learning/hetero_ftl/ftl_base.py", line 217, in initialize_nn
    self.nn = self.nn_builder(loss=loss, nn_define=self.nn_define, optimizer=self.optimizer, metrics=None,
  File "/data/projects/fate/fate/python/federatedml/transfer_learning/hetero_ftl/backend/tf_keras/nn_model.py", line 79, in build_keras
    keras_model.compile(loss=loss, optimizer=optimizer, metrics=metrics)
  File "/data/projects/fate/fate/python/federatedml/transfer_learning/hetero_ftl/backend/tf_keras/nn_model.py", line 92, in compile
    optimizer_instance = getattr(tf.keras.optimizers, optimizer.optimizer)(
  File "/data/projects/python/venv/lib/python3.8/site-packages/keras/optimizers/optimizer_v2/adam.py", line 110, in __init__
    super(Adam, self).__init__(name, **kwargs)
  File "/data/projects/python/venv/lib/python3.8/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 355, in __init__
    if kwargs[k] is not None and kwargs[k] < 0:
TypeError: '<' not supported between instances of 'str' and 'int'
```

I saw the kwargs error and found that FATE transformed all optimizer.kwargs into string and countered the above error, then I tried to transform back all params with Python literal_eval. However more error appeared as following:

**Second Time Error**
After I tried to fix the str kwargs error, I ran into another error:
```shell
[ERROR] [2023-05-25 07:25:25,972] [202305250722493247010] [9303:140527495038784] - [task_executor._run_] [line:265]: Attempt to convert a value ({'learning_rate': 0.01, 'decay': 0.0, 'beta_1': 0.9, 'beta_2': 0.999, 'epsilon': 1e-07, 'amsgrad': False}) with an unsupported type (<class 'dict'>) to a Tensor.
Traceback (most recent call last):
  File "/data/projects/fate/fateflow/python/fate_flow/worker/task_executor.py", line 209, in _run_
    cpn_output = run_object.run(cpn_input)
  File "/data/projects/fate/fate/python/federatedml/model_base.py", line 239, in run
    self._run(cpn_input=cpn_input)
  File "/data/projects/fate/fate/python/federatedml/model_base.py", line 318, in _run
    this_data_output = func(*params)
  File "/data/projects/fate/fate/python/federatedml/transfer_learning/hetero_ftl/ftl_guest.py", line 319, in fit
    self.update_nn_weights(grads, data_loader, epoch_idx, decay=self.comm_eff)
  File "/data/projects/fate/fate/python/federatedml/transfer_learning/hetero_ftl/ftl_base.py", line 273, in update_nn_weights
    self.nn.apply_gradients(weight_grads)
  File "/data/projects/fate/fate/python/federatedml/transfer_learning/hetero_ftl/backend/tf_keras/nn_model.py", line 131, in apply_gradients
    self._model.optimizer.apply_gradients(
  File "/data/projects/python/venv/lib/python3.8/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 646, in apply_gradients
    self._create_all_weights(var_list)
  File "/data/projects/python/venv/lib/python3.8/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 859, in _create_all_weights
    self._create_hypers()
  File "/data/projects/python/venv/lib/python3.8/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 1020, in _create_hypers
    self._hyper[name] = self.add_weight(
  File "/data/projects/python/venv/lib/python3.8/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 1233, in add_weight
    variable = self._add_variable_with_custom_getter(
  File "/data/projects/python/venv/lib/python3.8/site-packages/tensorflow/python/training/tracking/base.py", line 873, in _add_variable_with_custom_getter
    new_variable = getter(
  File "/data/projects/python/venv/lib/python3.8/site-packages/keras/engine/base_layer_utils.py", line 126, in make_variable
    return tf.compat.v1.Variable(
  File "/data/projects/python/venv/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/data/projects/python/venv/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 102, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
ValueError: Attempt to convert a value ({'learning_rate': 0.01, 'decay': 0.0, 'beta_1': 0.9, 'beta_2': 0.999, 'epsilon': 1e-07, 'amsgrad': False}) with an unsupported type (<class 'dict'>) to a Tensor.
```

It seems that keras said wrong parameters are given to create a Tensor. And hetero FTL job stopped due to above error. Is Hetero FTL working any more? Please have a check, thanks.

**Comment by hjc5484855** [comment]
我也遇到了相同的问题，fate单机版的可以运行成功。KubeFATE部署的版本不行
