### ISSUE TITLE
'FileLock' object has no attribute '_lock_file' in fate-1.11.2

### ISSUE THREAD

**Issue by qxzhou1010** [FederatedAI/FATE#4974]
I deployed **fate-1.11.2** according to the standalone deployment method from source code, and then tried to run any file under examples/piplines/, and this error would appear. How to solve it?

```
[ERROR] [2023-07-06 09:05:54,927] [202307060905491678210] [6392:140173808956352] - [task_executor._run_] [line:266]: create table meta failed:AttributeError("'FileLock' object has no attribute '_lock_file'")
Traceback (most recent call last):
  File "/workspace/fate-all/fate_1_11_2/FATE/fateflow/python/fate_flow/worker/task_executor.py", line 123, in _run_
    previous_components_parameters = tracker_client.get_model_run_parameters()
  File "/workspace/fate-all/fate_1_11_2/FATE/fateflow/python/fate_flow/scheduling_apps/client/tracker_client.py", line 229, in get_model_run_parameters
    raise Exception(f"create table meta failed:{response['retmsg']}")
Exception: create table meta failed:AttributeError("'FileLock' object has no attribute '_lock_file'")
[ERROR] [2023-07-06 09:05:54,928] [202307060905491678210] [6392:140173808956352] - [task_executor._run_] [line:272]: local variable 'sess' referenced before assignment
Traceback (most recent call last):
  File "/workspace/fate-all/fate_1_11_2/FATE/fateflow/python/fate_flow/worker/task_executor.py", line 123, in _run_
    previous_components_parameters = tracker_client.get_model_run_parameters()
  File "/workspace/fate-all/fate_1_11_2/FATE/fateflow/python/fate_flow/scheduling_apps/client/tracker_client.py", line 229, in get_model_run_parameters
    raise Exception(f"create table meta failed:{response['retmsg']}")
Exception: create table meta failed:AttributeError("'FileLock' object has no attribute '_lock_file'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/fate-all/fate_1_11_2/FATE/fateflow/python/fate_flow/worker/task_executor.py", line 269, in _run_
    sess.destroy_all_sessions()
UnboundLocalError: local variable 'sess' referenced before assignment
```

**Comment by zhihuiwan** [comment]
https://github.com/FederatedAI/FATE/blob/master/python/requirements.txt#L45

**Comment by qxzhou1010** [comment]
Thank you for your reply. Before submitting this issue, I have confirmed that the version of `filelock` meets the requirements.

```
Name: filelock
Version: 3.3.1
Summary: A platform independent file lock.
Home-page: https://github.com/tox-dev/py-filelock
Author: Benedikt Schmitt
Author-email: benedikt@benediktschmitt.de
License: Unlicense
Location: /workspace/fate-all/fate_1_11_2/FATE/fate-env/lib/python3.8/site-packages
Requires: 
Required-by: huggingface-hub, poetry, torch, transformers, triton, virtualenv
```

**Comment by qxzhou1010** [comment]
Also, as far as I know, many people have encountered the same problem as me when deploying **fate-1.11.2.** And **it is impossible to complete the training and prediction of FATE-LLM according to the documents FATE provided.** In addition, the training of FATE-LLM should require GPU support, but in , the cpu version of pytorch is provided in `
python/requirements-graph-nn.txt`

```
--find-links https://data.pyg.org/whl/torch-1.13.0+cpu.html

pyg-lib==0.1.0+pt113cpu
torch-scatter==2.1.0+pt113cpu
torch-sparse==0.6.16+pt113cpu
torch-cluster==1.6.0+pt113cpu
torch-spline-conv==1.2.1+pt113cpu
torch-geometric==2.2.0
```

**Comment by zhihuiwan** [comment]
Check if there are multiple python environments.

**Comment by qxzhou1010** [comment]
I'm pretty sure there aren't multiple python environments here. In fact, I tried the same deployment method on fate-1.9, and it turned out that the relevant code can run smoothly. Therefore, the problem should be on fate-1.11.2 itself, please confirm the deployment document and whether you can provide the corresponding docker image.

**Comment by qxzhou1010** [comment]
Till today I still haven't solved this problem, please help me.

**Comment by sagewe** [comment]
try pin the filelock version to 3.10 some as that suggest in https://github.com/microsoft/nni/issues/5523, if the problem still exists, fell free to reopen this issue.
