### ISSUE TITLE
meet a bug when running logistic regression example

### ISSUE THREAD

**Issue by ijnmklpo** [FederatedAI/FATE#502]
Hi, I met a python bug when runing "homo_logistic_regression" example.It is shown blow:
```shell
sh-4.2$ python /data/projects/FATE/fate_flow/fate_flow_client.py -f submit_job -c /data/projects/FATE/examples/federatedml-1.0-examples/homo_logistic_regression/test_homolr_evaluate_job_conf.json -d /data/projects/FATE/examples/federatedml-1.0-examples/homo_logistic_regression/test_homolr_evaluate_job_dsl.json
Traceback (most recent call last):
  File "/data/projects/FATE/fate_flow/fate_flow_client.py", line 17, in <module>
    import argparse
  File "/data/projects/common/miniconda3/lib/python3.7/argparse.py", line 87, in <module>
    import re as _re
  File "/data/projects/common/miniconda3/lib/python3.7/re.py", line 125, in <module>
    import functools
  File "/data/projects/common/miniconda3/lib/python3.7/functools.py", line 21, in <module>
    from collections import namedtuple
  File "/data/projects/common/miniconda3/lib/python3.7/collections/__init__.py", line 21, in <module>
    from operator import itemgetter as _itemgetter, eq as _eq
ImportError: cannot import name 'itemgetter' from 'operator' (/data/projects/FATE/fate_flow/operator/__init__.py)
```

I dont know where is the missing lib from, FATE project or standard python libs？And how can I solve the problem?

**Comment by dylan-fan** [comment]
https://github.com/FederatedAI/FATE/issues/518

**Comment by ijnmklpo** [comment]
ok, thank you
