### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by SJTUHGX** [FederatedAI/FATE#5199]
Docker container stand-alone deployment of FATE v1.11.0 uses the command
"flow job submit -c /example/dsl/v2/hetero_secureboost/test_secureboost_train_binary_conf.json -d example/dsl/v2/hetero_secureboost/test_secureboost_train_dsl.json" 
when trying to train an error:
[ERROR] [2023-09-18 07:18:33,160] [202309180718271572560] [298730:139823363282752] - [task_executor._run_] [line:265]: can not found table name: breast_hetero_guest namespace: experiment
Traceback (most recent call last):
File "/data/projects/fate/fateflow/python/fate_flow/worker/task_executor.py", line 209, in _run_
cpn_output = run_object.run(cpn_input)
File "/data/projects/fate/fateflow/python/fate_flow/components/_base.py", line 156, in run
self._run(cpn_input=cpn_input)
File "/data/projects/fate/fateflow/python/fate_flow/components/reader.py", line 86, in _run) = self.convert_check(
File "/data/projects/fate/fateflow/python/fate_flow/components/reader.py", line 202, in convert_check
return data_utils.convert_output(input_name, input_namespace, output_name, output_namespace, computing_engine,
File "/data/projects/fate/fateflow/python/fate_flow/utils/data_utils.py", line 71, in convert_output
raise RuntimeError(
RuntimeError: can not found table name: breast_hetero_guest namespace: experiment

**Comment by mgqa34** [comment]
需要先上传数据，[使用cli上传数据指引](https://github.com/FederatedAI/FATE/blob/master/doc/tutorial/dsl_conf/upload_data_guide.md#upload-command)
