### ISSUE TITLE
toy测试错误

### ISSUE THREAD

**Issue by Repo-Zhuang** [FederatedAI/FATE#5216]
Toy测试出现一下错误
`(fate_lab) (base) root@zhuangjiehang:~/zjh_workplace/FATE# flow test toy -gid 10000 -hid 10000`
```toy test job 202310081037450232660 is waiting
toy test job 202310081037450232660 is waiting
toy test job 202310081037450232660 is waiting
toy test job 202310081037450232660 is running
toy test job 202310081037450232660 is running
toy test job 202310081037450232660 is running
toy test job 202310081037450232660 is running
toy test job 202310081037450232660 is success
Traceback (most recent call last):
  File "/root/anaconda3/envs/FATE/lib/python3.8/tarfile.py", line 1854, in gzopen
    t = cls.taropen(name, mode, fileobj, **kwargs)
  File "/root/anaconda3/envs/FATE/lib/python3.8/tarfile.py", line 1831, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/root/anaconda3/envs/FATE/lib/python3.8/tarfile.py", line 1694, in __init__
    self.firstmember = self.next()
  File "/root/anaconda3/envs/FATE/lib/python3.8/tarfile.py", line 2578, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/root/anaconda3/envs/FATE/lib/python3.8/tarfile.py", line 1282, in fromtarfile
    buf = tarfile.fileobj.read(BLOCKSIZE)
  File "/root/anaconda3/envs/FATE/lib/python3.8/gzip.py", line 292, in read
    return self._buffer.read(size)
  File "/root/anaconda3/envs/FATE/lib/python3.8/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/root/anaconda3/envs/FATE/lib/python3.8/gzip.py", line 479, in read
    if not self._read_gzip_header():
  File "/root/anaconda3/envs/FATE/lib/python3.8/gzip.py", line 427, in _read_gzip_header
    raise BadGzipFile('Not a gzipped file (%r)' % magic)
gzip.BadGzipFile: Not a gzipped file (b'{"')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/zjh_workplace/FATE/fate_lab/bin/flow", line 33, in <module>
    sys.exit(load_entry_point('fate-client==1.11.3.post1', 'console_scripts', 'flow')())
  File "/root/zjh_workplace/FATE/fate_lab/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/root/zjh_workplace/FATE/fate_lab/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/root/zjh_workplace/FATE/fate_lab/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/zjh_workplace/FATE/fate_lab/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/zjh_workplace/FATE/fate_lab/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/zjh_workplace/FATE/fate_lab/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/root/zjh_workplace/FATE/fate_lab/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/zjh_workplace/FATE/fate_lab/lib/python3.8/site-packages/fate_client-1.11.3.post1-py3.8.egg/flow_client/flow_cli/commands/test.py", line 61, in toy
    check_log(flow_sdk, kwargs["guest_party_id"], job_id, job_status)
  File "/root/zjh_workplace/FATE/fate_lab/lib/python3.8/site-packages/fate_client-1.11.3.post1-py3.8.egg/flow_client/flow_cli/commands/test.py", line 72, in check_log
    r = flow_sdk.job.log(job_id=job_id, output_path="./logs/toy")
  File "/root/zjh_workplace/FATE/fate_lab/lib/python3.8/site-packages/fate_client-1.11.3.post1-py3.8.egg/flow_sdk/client/api/job.py", line 86, in log
    download_from_request(http_response=response, tar_file_name=tar_file_name, extract_dir=extract_dir)
  File "/root/zjh_workplace/FATE/fate_lab/lib/python3.8/site-packages/fate_client-1.11.3.post1-py3.8.egg/flow_sdk/utils.py", line 39, in download_from_request
    tar = tarfile.open(tar_file_name, "r:gz")
  File "/root/anaconda3/envs/FATE/lib/python3.8/tarfile.py", line 1801, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/root/anaconda3/envs/FATE/lib/python3.8/tarfile.py", line 1858, in gzopen
    raise ReadError("not a gzip file")
tarfile.ReadError: not a gzip file

**Comment by mgqa34** [comment]
任务执行成功了，日志下载失败，可以手工使用flow cli看看是否可以执行成功，或者在fateflow/logs/fateflow/ERROR.log看下是否有相关错误日志。

**Comment by Repo-Zhuang** [comment]
你好，我在fateflow下没有找到logs文件夹

**Comment by Repo-Zhuang** [comment]
另外我还有几个问题：
1. 在[9.1 配置Java环境](https://github.com/FederatedAI/FATE/blob/master/deploy/standalone-deploy/doc/standalone_fate_source_code_deployment_guide.zh.md#91-%E9%85%8D%E7%BD%AEjava%E7%8E%AF%E5%A2%83)中


```
wget https://dlcdn.apache.org/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.tar.gz
```
中maven链接失效，现在好像版本只有3.8.8以上。

2. 我在执行[9.3 启动fateboard](https://github.com/FederatedAI/FATE/blob/master/deploy/standalone-deploy/doc/standalone_fate_source_code_deployment_guide.zh.md#93-%E5%90%AF%E5%8A%A8fateboard)
```
cd ${FATE_PROJECT_BASE}/fateboard
bash service.sh status
bash service.sh start
```
显示
```
(fate_lab) (base) root@zhuangjiehang:~/zjh_workplace/FATE/fateboard# bash ./bin/service.sh status
./bin/service.sh: line 26: cd: /root/zjh_workplace/FATE/fateboard/bin/conf: No such file or directory
file not found:/root/zjh_workplace/FATE/fateboard/bin/init_env.sh
```
我的`/root/zjh_workplace/FATE/fateboard/bin`目录并没有`init_env.sh`，只有`service.sh`
