### ISSUE TITLE
error in egg module when running the example of secureboost

### ISSUE THREAD

**Issue by Wolverinehhh** [FederatedAI/FATE#535]
when I run the examples/hetero_secureboosting_tree/run_secureboost_cluster.sh using release 0.3, it is an error reported in the egg/logs/fate-egg.log:
[ERROR] 2019-09-02T10:50:06,385 [grpcServiceExecutor-2] [GrpcServerWrapper:53] – java.lang.NullPointerException
at com.webank.ai.fate.api.core.BasicMeta$Endpoint$Builder.setIp(BasicMeta.java:649)
at com.webank.ai.fate.eggroll.egg.api.grpc.server.NodeServiceImpl.lambda$getProcessor$0(NodeServiceImpl.java:55)
at com.webank.ai.fate.core.api.grpc.server.GrpcServerWrapper.wrapGrpcServerRunnable(GrpcServerWrapper.java:51)
at com.webank.ai.fate.eggroll.egg.api.grpc.server.NodeServiceImpl.getProcessor(NodeServiceImpl.java:51)
at com.webank.ai.fate.api.eggroll.egg.NodeServiceGrpc$MethodHandlers.invoke(NodeServiceGrpc.java:419)
at io.grpc.stub.ServerCall$UnaryServerCallHandler$UnaryServerCallListener.onHanlfClose(ServerCalls.java:171)
at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283)
at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:710)
at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)

**Comment by Wolverinehhh** [comment]
using release 0.3
