### ISSUE TITLE
使用model loader返回错误NameError: name 'get_homo_param_meta' is not defined

### ISSUE THREAD

**Issue by zzy484** [FederatedAI/FATE#5445]
用model loader返回如下错误： 
[ERROR] [2024-01-10 11:38:02,887] [202401101137461851290] [11623:140184702924608] - [task_executor._run_] [line:266]: name 'get_homo_param_meta' is not defined
2
Traceback (most recent call last):
3
  File "/data/projects/fate/fateflow/python/fate_flow/worker/task_executor.py", line 210, in _run_
4
    cpn_output = run_object.run(cpn_input)
5
  File "/data/projects/fate/fate/python/federatedml/model_base.py", line 239, in run
6
    self._run(cpn_input=cpn_input)
7
  File "/data/projects/fate/fate/python/federatedml/model_base.py", line 318, in _run
8
    this_data_output = func(*params)
9
  File "/data/projects/fate/fate/python/federatedml/nn/homo/client.py", line 175, in fit
10
    self.trainer_inst, model, optimizer, loss_fn, extra_data, self.optimizer, self.loss, self.warm_start_iter = init(
11
  File "/data/projects/fate/fate/python/federatedml/nn/homo/_init.py", line 43, in init
12
    param, meta = get_homo_param_meta(loaded_model)
13
NameError: name 'get_homo_param_meta' is not defined

是什么原因呢

**Comment by talkingwallace** [comment]
请问这是哪个版本？

**Comment by zzy484** [comment]
> 请问这是哪个版本？

1.11.3

**Comment by mgqa34** [comment]
> > 请问这是哪个版本？
> 
> 1.11.3

1.11.4应该已经对该问题进行了修复，可以考虑升级，或者更新该文件
