### ISSUE TITLE
Problem with building fate_client

### ISSUE THREAD

**Issue by asdfsx** [FederatedAI/FATE#5449]
Fate_Client has a dependency named networkx. 
When build fate_client with python3.8, the networkx should specify version `3.1`. 
Because the latest version `3.2.1` only support python 3.9 or later. 

By the way, why not upgrade the python version to 3.9 or later?

**Comment by dylan-fan** [comment]
you can update python to 3.9 and test. Maybe it is ok

**Comment by asdfsx** [comment]
By the way, how to upload example data using `examples/data/upload_config/min_test_data_testsuite.yaml`? It seems `flow data upload -c ` doesn't support yaml right now.

```
/opt/python3/bin/flow data upload -c examples/data/upload_config/min_test_data_testsuite.yaml
Traceback (most recent call last):
  ......
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/python3/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/python3/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/python3/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/python3/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/python3/lib/python3.8/site-packages/fate_client-2.0.0-py3.8.egg/fate_client/flow_cli/commands/data.py", line 44, in upload
    config_data = preprocess(**kwargs)
  File "/opt/python3/lib/python3.8/site-packages/fate_client-2.0.0-py3.8.egg/fate_client/flow_cli/utils/cli_utils.py", line 68, in preprocess
    config_data = json.load(conf_fp)
  File "/opt/python3/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/opt/python3/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/opt/python3/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/python3/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by asdfsx** [comment]
May be I should execute `pip install requirements.txt` before `python setup.py install`
setup.py may install networkx 3.2.1
