### ISSUE TITLE
No module named 'federatedml.param.param' when run 'run_ftl_ct_standalone.sh'

### ISSUE THREAD

**Issue by shikanon** [FederatedAI/FATE#549]
**Describe the bug**
When I run the script `run_ftl_ct_standalone.sh`, it raise ModuleNotFoundError. Like this:
```
Traceback (most recent call last):
  File "run_arbiter.py", line 19, in <module>
    from workflow.hetero_ftl_workflow.hetero_arbiter_workflow import FTLArbiterWorkFlow
  File "/fate/workflow/hetero_ftl_workflow/hetero_arbiter_workflow.py", line 19, in <module>
    from federatedml.ftl.hetero_ftl.hetero_ftl_arbiter import HeteroFTLArbiter
  File "/fate/federatedml/ftl/hetero_ftl/hetero_ftl_arbiter.py", line 24, in <module>
    from federatedml.param.param import FTLModelParam
ModuleNotFoundError: No module named 'federatedml.param.param'
```

**To Reproduce**
1. Go to folder `hetero_ftl`
2. Run the script `sh run_ftl_ct_standalone.sh 123`
3. See error on `arbiter.log`

**Comment by zengjice** [comment]
hello,
Please provide the version of the FATE you deployed. And you can check the PYTHONPATH.
