### ISSUE TITLE
homo_* algorithm report an error in v1.7.2,  but hetero_* algorithm can run successfully

### ISSUE THREAD

**Issue by hjdongcn** [FederatedAI/FATE#5501]
I am very confused. Running all the pipeline/homo_* algorithms in the examples folder will report the same error in reader_0 or DataTransform, but the pipeline hetero_* algorithm can run successfully.

2024-02-23 16:10:45.120167: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-02-23 16:10:50.245 | INFO     | pipeline.utils.invoker.job_submitter:monitor_job_status:123 - Job id is 202402231610480302760
                   Job is still waiting, time elapse: 0:00:00
2024-02-23 16:10:51Running component reader_0, time elapse: 0:00:06
2024-02-23 16:10:59Running component reader_1, time elapse: 0:00:14
2024-02-23 16:11:07.798 | ERROR    | __main__:main:132 - An error has been caught in function 'main', process 'MainProcess' (3893), thread 'MainThread' (140195080955712):
Traceback (most recent call last):

  File "/home/FATE-1.7.2/examples/pipeline/homo_onehot/pipeline-homo-onehot-test.py", line 146, in <module>
    main()
    └ <function main at 0x7f81b5f5ff28>

> File "/home/FATE-1.7.2/examples/pipeline/homo_onehot/pipeline-homo-onehot-test.py", line 132, in main
    pipeline.fit()
    │        └ <function PipeLine.fit at 0x7f81a1f799d8>
    └ <pipeline.backend.pipeline.PipeLine object at 0x7f81a1f71da0>

  File "/opt/app-root/lib/python3.6/site-packages/fate_client-1.7.2-py3.6.egg/pipeline/backend/pipeline.py", line 572, in fit
    self._initiator.party_id)
    │    │          └ 9999
    │    └ namespace(party_id=9999, role='guest')
    └ <pipeline.backend.pipeline.PipeLine object at 0x7f81a1f71da0>
  File "/opt/app-root/lib/python3.6/site-packages/fate_client-1.7.2-py3.6.egg/pipeline/utils/invoker/job_submitter.py", line 138, in monitor_job_status
    raise ValueError(f"Job is failed, please check out job {job_id} by fate board or fate_flow cli")

ValueError: Job is failed, please check out job 202402231610480302760 by fate board or fate_flow cli
Traceback (most recent call last):
  File "/home/FATE-1.7.2/examples/pipeline/homo_onehot/pipeline-homo-onehot-test.py", line 146, in <module>
    main()
  File "/home/FATE-1.7.2/examples/pipeline/homo_onehot/pipeline-homo-onehot-test.py", line 132, in main
    pipeline.fit()
  File "/opt/app-root/lib/python3.6/site-packages/loguru/_logger.py", line 1220, in catch_wrapper
    return function(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/fate_client-1.7.2-py3.6.egg/pipeline/backend/pipeline.py", line 572, in fit
    self._initiator.party_id)
  File "/opt/app-root/lib/python3.6/site-packages/fate_client-1.7.2-py3.6.egg/pipeline/utils/invoker/job_submitter.py", line 138, in monitor_job_status
    raise ValueError(f"Job is failed, please check out job {job_id} by fate board or fate_flow cli")
ValueError: Job is failed, please check out job 202402231610480302760 by fate board or fate_flow cli

**Comment by hjdongcn** [comment]
[ERROR] [2024-02-23 15:17:47,921] [202402231517410616070] [20113:140428609070912] - [task_executor._run_] [line:243]: can not found table name: breast_homo_guest namespace: experiment
Traceback (most recent call last):
  File "./fate/fateflow/python/fate_flow/worker/task_executor.py", line 195, in _run_
    cpn_output = run_object.run(cpn_input)
  File "./fate/fateflow/python/fate_flow/components/_base.py", line 149, in run
    method(cpn_input)
  File "./fate/fateflow/python/fate_flow/components/reader.py", line 91, in _run
    output_storage_address=output_storage_address,
  File "./fate/fateflow/python/fate_flow/components/reader.py", line 217, in convert_check
    f"can not found table name: {input_name} namespace: {input_namespace}"
RuntimeError: can not found table name: breast_homo_guest namespace: experiment

**Comment by dylan-fan** [comment]
1.7.2 version is too old version which is not supported by FATE Communitiy.
Welcome to use the latest version.
