### ISSUE TITLE
部署问题 fate-flow Timeout when waiting for x.x.xx.x:9360

### ISSUE THREAD

**Issue by ShaoYULi12** [FederatedAI/FATE#5519]
版本1.11.4 执行bash deploy/deploy.sh deploy后报错：

deploy-xxxx.log报错信息：
fatal: FAILED! => {"changed": false, "elapsed": 120, "msg": "Timeout when waiting for x.x.xx.x:9360"}

/data/logs/fate/fateflow/error.log错误信息：
Traceback (most recent call last):
File "/data/projects/fate/fateflow/python/fate_flow/fate_flow_server.py", line 110, in
server.add_insecure_port(f"{HOST}:{GRPC_PORT}")
File "/data/projects/fate/common/python/venv/lib/python3.8/site-packages/grpc/_server.py", line 969, in add_insecure_port
return _common.validate_port_binding_result(
File "/data/projects/fate/common/python/venv/lib/python3.8/site-packages/grpc/_common.py", line 166, in validate_port_binding_result
raise RuntimeError(_ERROR_MESSAGE_PORT_BINDING_FAILED % address)
RuntimeError: Failed to bind to address x.x.x.x:9360; set GRPC_VERBOSITY=debug environment variable to see detailed error message.

/data/logs/fate/fateflow/info.log错误信息：
PROJECT_BASE: /data/projects/fate
PYTHONPATH: /data/projects/fate/fate/python:/data/projects/fate/fateflow/python:/data/projects/fate/eggroll/python
found service conf: /data/projects/fate/conf/service_conf.yaml
fate flow http port: 9380, grpc port: 9360

check process by http port and grpc port
/data/projects/fate/fateflow/bin/service.sh: line 74: lsof: command not found
/data/projects/fate/fateflow/bin/service.sh: line 75: lsof: command not found
PROJECT_BASE: /data/projects/fate
PYTHONPATH: /data/projects/fate/fate/python:/data/projects/fate/fateflow/python:/data/projects/fate/eggroll/python
found service conf: /data/projects/fate/conf/service_conf.yaml
fate flow http port: 9380, grpc port: 9360

check process by http port and grpc port
/data/projects/fate/fateflow/bin/service.sh: line 74: lsof: command not found
/data/projects/fate/fateflow/bin/service.sh: line 75: lsof: command not found

**Comment by zhihuiwan** [comment]
1. 检查下防火墙设置，是否运行端口9360的流量
2.确保网络配置正确，包括网络接口是否正确配置。
3. 按照提示设置 GRPC_VERBOSITY=debug 环境变量
