### ISSUE TITLE
训练住房数据的时候出现“too many dimensions 'str'”

### ISSUE THREAD

**Issue by cgyzfjm** [FederatedAI/FATE#5545]
使用的版本是kubefate-docker-compose-v2.0.0

在训练住房数据时出现“too many dimensions 'str'”

下面是Board里面的报错信息
![image](https://github.com/FederatedAI/FATE/assets/25324817/c0bfef35-3200-4217-adc3-b8061c6cb5c1)

`100
Traceback (most recent call last):
101
  File "/data/projects/fate/fate/python/fate/arch/dataframe/manager/block_manager.py", line 316, in convert_block
102
    return torch.tensor(block, dtype=torch.int32)
103
ValueError: too many dimensions 'str'
104
105
During handling of the above exception, another exception occurred:
106
107
Traceback (most recent call last):
108
  File "/data/projects/fate/eggroll/python/eggroll/trace/_exception_logger.py", line 8, in wrapper
109
    return func(*args, **kw)
110
  File "/data/projects/fate/eggroll/python/eggroll/core/command/command_service.py", line 29, in call
111
    call_result = CommandRouter.get_instance().dispatch(
112
  File "/data/projects/fate/eggroll/python/eggroll/core/command/command_router.py", line 131, in dispatch
113
    raise e
114
  File "/data/projects/fate/eggroll/python/eggroll/core/command/command_router.py", line 126, in dispatch
115
    call_result = _method(_instance, *deserialized_args)
116
  File "/data/projects/fate/eggroll/python/eggroll/computing/tasks/__init__.py", line 65, in exec
117
    result = handler.run(self.env_options, task.job, task)
118
  File "/data/projects/fate/eggroll/python/eggroll/computing/tasks/impl/_map_partitions_with_index.py", line 34, in run
119
    cls._run_shuffle(env_options, job, task, map_op, reduce_op)
120
  File "/data/projects/fate/eggroll/python/eggroll/computing/tasks/impl/_map_partitions_with_index.py", line 206, in _run_shuffle
121
    for k1, v1 in value:
122
  File "/data/projects/fate/fate/python/fate/arch/computing/api/_table.py", line 715, in _lifted
123
    for out_k, out_v in _f(_index, _serdes_wrapped_generator(_iter, input_key_serdes, input_value_serdes)):
124
  File "/data/projects/fate/fate/python/fate/arch/dataframe/_frame_reader.py", line 343, in _to_blocks
125
    converted_blocks = data_manager.convert_to_blocks(splits)
126
  File "/data/projects/fate/fate/python/fate/arch/dataframe/manager/data_manager.py", line 128, in convert_to_blocks
127
    converted_blocks.append(block.convert_block(splits[bid]))
128
  File "/data/projects/fate/fate/python/fate/arch/dataframe/manager/block_manager.py", line 318, in convert_block
129
    return torch.tensor(np.array(block, dtype="int32"), dtype=torch.int32)
130
ValueError: invalid literal for int() with base 10: '17.4'
131
132
==== detail end ====`

下面是训练所使用的数据
![image](https://github.com/FederatedAI/FATE/assets/25324817/635dc2ee-fa36-4cde-b9a4-63638af3fdde)

是不是因为y的类型有问题？因
为之前训练乳腺癌的数据是可以成功的，那个数据集里面的y只有0和1的取值，但是住房数据里面的y的取值是浮点型。

麻烦各位大佬指点指点

**Comment by mgqa34** [comment]
label_type需要设置为float，报错是尝试将float的str转成int出现了问题

**Comment by cgyzfjm** [comment]
> label_type需要设置为float，报错是尝试将float的str转成int出现了问题

请问这个是需要去哪里设置的

**Comment by cgyzfjm** [comment]
> label_type需要设置为float，报错是尝试将float的str转成int出现了问题

感谢！感谢！成功了
![image](https://github.com/FederatedAI/FATE/assets/25324817/304576ee-3c38-4335-b104-5d682b6eb691)
