### ISSUE TITLE
上传数据时候，不加label可以正确上传，但是加入label之后会报错ValueError: invalid literal for int() with base 10: '0.8960573476702509，但是我的数据都是浮点数啊。

### ISSUE THREAD

**Issue by 0814wdwd** [FederatedAI/FATE#5555]
User
==== detail start, at 2024-03-21 23:43:31 668607 ====
Traceback (most recent call last):
  File "/data/projects/fate/fate/python/fate/arch/dataframe/manager/block_manager.py", line 316, in convert_block
    return torch.tensor(block, dtype=torch.int32)
ValueError: too many dimensions 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/projects/fate/eggroll/python/eggroll/trace/_exception_logger.py", line 8, in wrapper
    return func(*args, **kw)
  File "/data/projects/fate/eggroll/python/eggroll/core/command/command_service.py", line 29, in call
    call_result = CommandRouter.get_instance().dispatch(
  File "/data/projects/fate/eggroll/python/eggroll/core/command/command_router.py", line 131, in dispatch
    raise e
  File "/data/projects/fate/eggroll/python/eggroll/core/command/command_router.py", line 126, in dispatch
    call_result = _method(_instance, *deserialized_args)
  File "/data/projects/fate/eggroll/python/eggroll/computing/tasks/__init__.py", line 65, in exec
    result = handler.run(self.env_options, task.job, task)
  File "/data/projects/fate/eggroll/python/eggroll/computing/tasks/impl/_map_partitions_with_index.py", line 34, in run
    cls._run_shuffle(env_options, job, task, map_op, reduce_op)
  File "/data/projects/fate/eggroll/python/eggroll/computing/tasks/impl/_map_partitions_with_index.py", line 206, in _run_shuffle
    for k1, v1 in value:
  File "/data/projects/fate/fate/python/fate/arch/computing/api/_table.py", line 715, in _lifted
    for out_k, out_v in _f(_index, _serdes_wrapped_generator(_iter, input_key_serdes, input_value_serdes)):
  File "/data/projects/fate/fate/python/fate/arch/dataframe/_frame_reader.py", line 343, in _to_blocks
    converted_blocks = data_manager.convert_to_blocks(splits)
  File "/data/projects/fate/fate/python/fate/arch/dataframe/manager/data_manager.py", line 128, in convert_to_blocks
    converted_blocks.append(block.convert_block(splits[bid]))
  File "/data/projects/fate/fate/python/fate/arch/dataframe/manager/block_manager.py", line 318, in convert_block
    return torch.tensor(np.array(block, dtype="int32"), dtype=torch.int32)
ValueError: invalid literal for int() with base 10: '0.8960573476702509                                                                                                                       上述为报错

**Comment by amenkim** [comment]
可以试试meta里加上 "label_type": "float64"

**Comment by 0814wdwd** [comment]
好哒好哒，谢谢您



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年03月25日 13:39 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [FederatedAI/FATE] 上传数据时候，不加label可以正确上传，但是加入label之后会报错ValueError: invalid literal for int() with base 10: '0.8960573476702509，但是我的数据都是浮点数啊。 (Issue #5555) |

可以试试meta里加上 "label_type": "float64"
