### ISSUE TITLE
首页给的demo跑不通。查了源码，是不是demo过时了？

### ISSUE THREAD

**Issue by fggggg7142** [FederatedAI/FATE#5583]
demo地址：
https://github.com/FederatedAI/FATE/blob/master/doc/2.0/fate/quick_start.md

报错信息:
Traceback (most recent call last):
  File "a1.py", line 56, in <module>
    pipeline.compile()
  File "/home/kemove/.local/lib/python3.8/site-packages/fate_client/pipeline/pipeline.py", line 194, in compile
    self._dag.compile(task_insts=self._tasks,
  File "/home/kemove/.local/lib/python3.8/site-packages/fate_client/pipeline/entity/dag.py", line 63, in compile
    task["outputs"] = task_inst.get_output_artifacts()
  File "/home/kemove/.local/lib/python3.8/site-packages/fate_client/pipeline/components/component_base.py", line 313, in get_output_artifacts
    outputs[output_artifact_type][artifact_name] = OutputArtifactSpec(
  File "/home/kemove/.local/lib/python3.8/site-packages/pydantic/main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for OutputArtifactSpec

查了下，里面的大量的类，如OutputArtifactSpec，还有一些task类，构造函数给的变量不全。这个demo是过时了吗？有没有正常成熟的demo？

**Comment by fggggg7142** [comment]
除了给的demo。大量的examples里面也跑不通。fate版本是2.1. fate_client版本也是2.1.0

**Comment by mgqa34** [comment]
> 除了给的demo。大量的examples里面也跑不通。fate版本是2.1. fate_client版本也是2.1.0

请问是怎么安装的？ 我们没法复现(python3.8 + centos 7.2)，另外确认一下pydantic/typing_extensions的版本

**Comment by fggggg7142** [comment]
我觉得是pydantic/typing_extensions的版本问题。
改了版本可以了。多谢
