### ISSUE TITLE
2.1版本pipeline的存储和加载如何实现？

### ISSUE THREAD

**Issue by Sadirry** [FederatedAI/FATE#5613]
在1.10版本，pipeline有dump和load两个接口可实现存储pipeline和加载pipeline，请问2.1版本中是否有相同功能的接口？我直接利用pickle存储和加载会报错！

2.1中我完成的存储和加载：
```
        pkl = pickle.dumps(pipeline)
        with open(save_path, "wb") as fout:
            fout.write(pkl)
        return pkl
```
```
        with open(file_path, "rb") as fin:
            pipeline_obj = pickle.loads(fin.read())
            return pipeline_obj
```

**Comment by Sadirry** [comment]
我的问题是，在2.1版本中，我完成了pipeline.add_tasks([read_0, psi_0, hetero_secure_boost_0, evaluation_0])并且成功compile和fit后，想要保存此时的pipeline：

```
        pkl = pickle.dumps(pipeline)
        with open(save_path, "wb") as fout:
            fout.write(pkl)
        return pkl
```

执行后在save_path下成功保存了pipeline.pkl文件，此时若要加载刚刚得到的pipeline用以deploy：

```
        with open(file_path, "rb") as fin:
            pipeline_obj = pickle.loads(fin.read())
            return pipeline_obj
```

报错：
```
Traceback (most recent call last):
  File "/root/anaconda3/envs/fate_env/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/root/anaconda3/envs/fate_env/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/fate_test/FL/fate_api_2/test_api.py", line 76, in <module>
    model_manager.pipeline_load(param['model_id'], param['model_version'])
  File "/fate_test/FL/fate_api_2/model_management.py", line 97, in pipeline_load
    pipeline_obj = pickle.loads(fin.read())
  File "/root/anaconda3/envs/fate_env/lib/python3.8/site-packages/fate_client/pipeline/pipeline.py", line 357, in __getattr__
    if attr in self._tasks:
  File "/root/anaconda3/envs/fate_env/lib/python3.8/site-packages/fate_client/pipeline/pipeline.py", line 357, in __getattr__
    if attr in self._tasks:
  File "/root/anaconda3/envs/fate_env/lib/python3.8/site-packages/fate_client/pipeline/pipeline.py", line 357, in __getattr__
    if attr in self._tasks:
  [Previous line repeated 984 more times]
RecursionError: maximum recursion depth exceeded
```

但是在1.10的版本中，fate_client/pipeline/backend/pipeline.py直接提供了接口可以存储和加载pipeline：
```
    @LOGGER.catch(reraise=True)
    def dump(self, file_path=None):
        pkl = pickle.dumps(self)

        if file_path is not None:
            with open(file_path, "wb") as fout:
                fout.write(pkl)

        return pkl

    @classmethod
    def load(cls, pipeline_bytes):
        """
        return pickle.loads(pipeline_bytes)
        """
        pipeline_obj = pickle.loads(pipeline_bytes)
        pipeline_obj.set_job_invoker(JobInvoker())
        return pipeline_obj
```

请问2.1版本中如果解决这个问题？

**Comment by mgqa34** [comment]
噢，之前测过一次，后面更新的时候忘记测了，
可以修改下面的文件：/root/anaconda3/envs/fate_env/lib/python3.8/site-packages/fate_client/pipeline/pipeline.py，增加下面两个函数再使用即可，我们近期会发布一个新的fate-client版本，也会补充这个。

```
    def __getstate__(self):
        return vars(self)

    def __setstate__(self, state):
        vars(self).update(state)
```
