### ISSUE TITLE
Fate当中的MPC部分

### ISSUE THREAD

**Issue by DuanYuFi** [FederatedAI/FATE#5664]
**Describe the bug**
我在使用Fate里面的MPC部分，这部分是使用了Crypten的代码，因此我尝试把Crypten上可以用的代码放在Fate上运行，但是`mpc.cat`函数上遇到了问题。

**To Reproduce**
代码如下：
```
from datetime import datetime
import sys
import random

from fate.arch.protocol import mpc
from fate.arch.protocol.mpc.primitives.arithmetic import ArithmeticSharedTensor

def get_current_datetime_str():
    return datetime.now().strftime("%Y-%m-%d-%H-%M")


guest = ("guest", "10000")
host = ("host", "9999")
name = get_current_datetime_str()

def create_ctx(local, context_name):
    from fate.arch import Context
    from fate.arch.computing.backends.standalone import CSession
    from fate.arch.federation.backends.standalone import StandaloneFederation
    import logging

    # prepare log
    logger = logging.getLogger()
    logger.setLevel(logging.INFO)
    console_handler = logging.StreamHandler()
    console_handler.setLevel(logging.DEBUG)
    formatter = logging.Formatter("%(asctime)s - %(name)s - %(levelname)s - %(message)s")
    console_handler.setFormatter(formatter)
    logger.addHandler(console_handler)
    # init fate context
    computing = CSession(data_dir="./cession_dir")
    return Context(computing=computing, federation=StandaloneFederation(computing, context_name, local, [guest, host]))

role = sys.argv[1]

if role == 'host':
    ctx = create_ctx(host, get_current_datetime_str())
else:
    ctx = create_ctx(guest, get_current_datetime_str())

ctx.mpc.init()
# print(type(ctx.mpc._ctx))

rank_guest, rank_host = ctx.guest.rank, ctx.hosts[0].rank

def bubblesort(numbers, size) -> ArithmeticSharedTensor:
    for i in range(size):
        for j in range(size - 1):
            choice_bit = numbers[j] > numbers[j + 1]
            a = mpc.where(choice_bit, numbers[j + 1], numbers[j])
            b = mpc.where(choice_bit, numbers[j], numbers[j + 1])
            numbers[j] = a
            numbers[j + 1] = b

    return numbers

TEST_SIZE = 100

random.seed(0xdeadbeef)
data_from_alice = [random.randint(0, 0xFFFF) for _ in range(TEST_SIZE // 2)]
alice_enc = ctx.mpc.lazy_encrypt(lambda: data_from_alice, src=rank_host)

random.seed(0xc0ffee)
data_from_bob = [random.randint(0, 0xFFFF) for _ in range(TEST_SIZE // 2)]
bob_enc = ctx.mpc.lazy_encrypt(lambda: data_from_bob, src=rank_guest)

data = mpc.cat([alice_enc, bob_enc], dim=0)

sort_result = bubblesort(data, TEST_SIZE)
result = sort_result.get_plain_text()

if role == "host":
    print(result)
```

在两个终端分别运行`python test.py host`和`python test.py guest`，我在ArithmeticSharedTensor构造函数处把warning替换成了raise Error，收到报错和调用栈如下：
```
2024-07-16 09:59:22,320 - fate.arch.protocol.mpc.primitives.arithmetic - WARNING - ctx must be a Context object
Traceback (most recent call last):
  File "mpc_test.py", line 67, in <module>
    data = mpc.cat([alice_enc, bob_enc], dim=0)
  File "/root/anaconda3/envs/fate/lib/python3.8/site-packages/fate/arch/protocol/mpc/__init__.py", line 271, in cat
    return type(tensors[0]).cat(tensors, dim=dim)
  File "/root/anaconda3/envs/fate/lib/python3.8/site-packages/fate/arch/protocol/mpc/cryptensor.py", line 44, in __getattribute__
    dummy = cls(None, [])  # this creates an empty CrypTensor
  File "/root/anaconda3/envs/fate/lib/python3.8/site-packages/fate/arch/protocol/mpc/mpc.py", line 75, in __init__
    self._tensor = tensor_type(ctx=ctx, tensor=tensor, device=device, *args, **kwargs)
  File "/root/anaconda3/envs/fate/lib/python3.8/site-packages/fate/arch/protocol/mpc/primitives/arithmetic.py", line 86, in __init__
    raise ValueError("ctx must be a Context object")
ValueError: ctx must be a Context object
```

**Expected behavior**
排序

**Desktop (please complete the following information):**
 - Linux Ubuntu 22.04

**Comment by sagewe** [comment]
目前FATE只对Crypten做了部分支持，完整的支持需要等后续的版本进行修复适配，暂时无法保证Crypten都能在FATE上运行

**Comment by DuanYuFi** [comment]
好的，十分感谢。
另外想请问，官方有没有相关文档或者表格来体现出Fate目前对于Crypten函数的支持情况？以及MPC组件目前在Fate中是不是一个服务于FL的存在，因此除非FL业务中有相关需求，否则不太可能完善这部分？感谢！

**Comment by sagewe** [comment]
> 另外想请问，官方有没有相关文档或者表格来体现出Fate目前对于Crypten函数的支持情况？
目前的支持以基础的运算为主，对cat，stack之类的数据操作目前没有支持

> 因此除非FL业务中有相关需求，否则不太可能完善这部分？
不完全是，我们在次基础上支持了SSHE协议

> 不太可能完善这部分？
Crypten是个很有意思的项目，由于torch本身对类型扩展的支持并不完善，Crypten为了实现mpctensor事实上重写了torch的很多代码，包括autograd。FATE想要在此基础上扩展FATE的底层类型，所需要的工作量至少与写一个Crypten相当（当然，珠玉在前，可以借鉴）。我们之前有计划完善这部分，但是考虑到我们底层是支持分布式tensor的，支持的难度与最终能够达成的效果我们还没有一个确切的评估，另外我们的工作重点也发生了一些变化。因此，除非后续有新的调整或者社区愿意贡献，我个人的判断是短期内这部分不太可能得到很好的完善。

**Comment by DuanYuFi** [comment]
好的，感谢您的答复！👍🫡
