### ISSUE TITLE
Docker单机部署下运行pipeline中的homo_nn存在bug

### ISSUE THREAD

**Issue by Cyh-sdgf** [FederatedAI/FATE#5674]
**Describe the bug**
docker部署federatedai/standalone_fate:2.1.0。进入docker后，跳转至/fate/examples/pipeline/homo_nn。
执行 python test_nn_binary.py 出现bug。

报错信息如下：

python test_nn_binary.py 
Job id is 202407210849451084850
Job is waiting, time elapse: 0:00:00
Running task reader_0, time elapse: 0:00:05
Running task nn_0, time elapse: 0:00:24
Traceback (most recent call last):
  File "test_nn_binary.py", line 104, in <module>
    main(config=args.config, namespace=args.namespace)
  File "test_nn_binary.py", line 92, in main
    pipeline.fit()
  File "/data/projects/fate/env/python/venv/lib/python3.8/site-packages/fate_client-2.1.0-py3.8.egg/fate_client/pipeline/pipeline.py", line 264, in fit
    self._model_info = self._executor.fit(self._dag.dag_spec,
  File "/data/projects/fate/env/python/venv/lib/python3.8/site-packages/fate_client-2.1.0-py3.8.egg/fate_client/pipeline/executor/task_executor.py", line 33, in fit
    return self._run(
  File "/data/projects/fate/env/python/venv/lib/python3.8/site-packages/fate_client-2.1.0-py3.8.egg/fate_client/pipeline/executor/task_executor.py", line 77, in _run
    flow_job_invoker.monitor_status(job_id, local_role, local_party_id)
  File "/data/projects/fate/env/python/venv/lib/python3.8/site-packages/fate_client-2.1.0-py3.8.egg/fate_client/pipeline/utils/fateflow/fate_flow_job_invoker.py", line 69, in monitor_status
    raise ValueError(f"Job is {status}, please check out job_id={job_id} in fate_flow log directory")
ValueError: Job is failed, please check out job_id=202407210849451084850 in fate_flow log directory

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by yx0090sh** [comment]
@Cyh-sdgf 请问数据是不是和 test_nn_binary.py 里面的一致呢？ 用的 fate/examples/data/breast_homo_guest.csv   fate/examples/data/breast_homo_host.csv ,使用这2份数据， 不用改test_nn_binary.py的代码， 可以跑成功

**Comment by talkingwallace** [comment]
这个具体的错误日志要到fateflow下的Log看下
