### ISSUE TITLE
io_exception rpc

### ISSUE THREAD

**Issue by zhuchangjiang** [FederatedAI/FATE#579]
help!
when i run  python run_toy_example.py 9999 10000 1,it get errors,
what cause this error,how can i slove it?

Traceback (most recent call last):
  File "/data/projects/fate/python/fate_flow/utils/api_utils.py", line 55, in remote_api
    _return = stub.unaryCall(_packet)
  File "/home/app/anaconda3/lib/python3.6/site-packages/grpc/_channel.py", line 533, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/app/anaconda3/lib/python3.6/site-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "io exception"
	debug_error_string = "{"created":"@1568210336.533187742","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"io exception","grpc_status":14}"

**Comment by zhuchangjiang** [comment]
this is my ports desc
<img width="368" alt="image" src="https://user-images.githubusercontent.com/26199641/64704519-0483fe00-d4e1-11e9-9edb-f2d7d91ac2ee.png">

**Comment by zhuchangjiang** [comment]
my processor is on, but the problem is still confuse me!
the error  occur again
