### ISSUE TITLE
secboost example run failed

### ISSUE THREAD

**Issue by usafchn** [FederatedAI/FATE#619]
Hello,

I followed the README files and started fate_flow and fateboard successfully, and also successfully ran the lr example in `examples/federatedml-1.0-examples/hetero_logistic_regression`, however, task failed when I tried secboost example in `examples/federatedml-1.0-examples/hetero_secureboost`.

Below is my config:

version: v1.0.2
fate_flow server: standanloe mode, use sqlite db.

In examples/federatedml-1.0-examples/quick_run.py:
DSL_PATH = 'hetero_secureboost/test_secureboost_train_dsl.json'
SUBMIT_CONF_PATH = 'hetero_secureboost/test_secureboost_train_binary_conf.json'

and then quick_run.py prints:
```
Upload data config json: {'file': 'examples/data/breast_b.csv', 'head': 1, 'partition': 10, 'work_mode': 0, 'table_name': 'breast_b', 'namespace': 'breast_b_guest'}
stdout:{
    "data": {
        "namespace": "breast_b_guest",
        "pid": 24848,
        "table_name": "breast_b"
    },
    "jobId": "201909251558299848924",
    "meta": null,
    "retcode": 0,
    "retmsg": "success"
}


Upload data config json: {'file': 'examples/data/breast_a.csv', 'head': 1, 'partition': 10, 'work_mode': 0, 'table_name': 'breast_a', 'namespace': 'breast_a_host'}
stdout:{
    "data": {
        "namespace": "breast_a_host",
        "pid": 24853,
        "table_name": "breast_a"
    },
    "jobId": "201909251558331064515",
    "meta": null,
    "retcode": 0,
    "retmsg": "success"
}


dsl_path: /home/yuwen/repo/github/FATE/examples/federatedml-1.0-examples/user_config/train_dsl.config_1569398316_1861, conf_path: /home/yuwen/repo/github/FATE/examples/federatedml-1.0-examples/user_config/train_conf.config_1569398316_2790
stdout:{
    "data": {
        "board_url": "http://30.54.206.135:8080/index.html#/dashboard?job_id=201909251558362437256&role=guest&party_id=10000",
        "job_dsl_path": "/home/yuwen/repo/github/FATE/jobs/201909251558362437256/job_dsl.json",
        "job_runtime_conf_path": "/home/yuwen/repo/github/FATE/jobs/201909251558362437256/job_runtime_conf.json",
        "model_info": {
            "model_id": "arbiter-10000#guest-10000#host-10000#model",
            "model_version": "201909251558362437256"
        }
    },
    "jobId": "201909251558362437256",
    "meta": null,
    "retcode": 0,
    "retmsg": "success"
}

Please check your task in fate-board, url is : http://30.54.206.135:8080/index.html#/dashboard?job_id=201909251558362437256&role=guest&party_id=10000
The log info is located in /home/yuwen/repo/github/FATE/examples/federatedml-1.0-examples/../../logs/201909251558362437256
Task is running, wait time: 10.356188535690308
Task Failed
```

The job failed in dataio_1 section:
![image](https://user-images.githubusercontent.com/3414971/65581800-b8d85680-dfae-11e9-8127-12ad260c2ed9.png)

logs:
```
"2019-09-25 15:58:42,495 - model_manager.py[line:74] - INFO: parse DataIOMeta proto object normal"
"2019-09-25 15:58:42,503 - model_manager.py[line:74] - INFO: parse DataIOParam proto object normal"
"2019-09-25 15:58:42,628 - api_utils.py[line:70] - INFO: local api request: http://30.54.206.135:9380/v1/schedule/201909251558362437256/dataio_1/201909251558362437256_dataio_1/host/10000/status"
"2019-09-25 15:58:42,736 - api_utils.py[line:73] - INFO: {"data":null,"jobId":null,"meta":null,"retcode":0,"retmsg":"success"}
"
"2019-09-25 15:58:42,736 - api_utils.py[line:75] - INFO: local api response: /v1/schedule/201909251558362437256/dataio_1/201909251558362437256_dataio_1/host/10000/status {'data': None, 'jobId': None, 'meta': None, 'retcode': 0, 'retmsg': 'success'}"
"2019-09-25 15:58:42,736 - task_executor.py[line:109] - INFO: run 201909251558362437256 dataio_1 201909251558362437256_dataio_1 host 10000 task"
"2019-09-25 15:58:42,736 - task_executor.py[line:110] - INFO: {'DataIOParam': {'input_format': 'dense', 'delimitor': ',', 'data_type': 'float64', 'tag_with_value': False, 'tag_value_delimitor': ':', 'missing_fill': False, 'default_value': 0, 'missing_fill_method': None, 'missing_impute': None, 'outlier_replace': False, 'outlier_replace_method': None, 'outlier_impute': None, 'outlier_replace_value': 0, 'with_label': True, 'label_idx': 0, 'label_type': 'int', 'output_format': 'dense'}, 'initiator': {'role': 'guest', 'party_id': 10000}, 'job_parameters': {'work_mode': 0, 'model_id': 'arbiter-10000#guest-10000#host-10000#model', 'model_version': '201909251558362437256'}, 'role': {'guest': [10000], 'host': [10000], 'arbiter': [10000]}, 'config': '/home/yuwen/repo/github/FATE/examples/federatedml-1.0-examples/user_config/train_conf.config_1569398316_2790', 'dsl': '/home/yuwen/repo/github/FATE/examples/federatedml-1.0-examples/user_config/train_dsl.config_1569398316_1861', 'function': 'submit_job', 'local': {'role': 'host', 'party_id': 10000}, 'CodePath': 'federatedml/util/data_io.py/DataIO', 'module': 'DataIO'}"
"2019-09-25 15:58:42,736 - task_executor.py[line:111] - INFO: {'data': {'data': ['args.eval_data']}, 'model': ['dataio_0.dataio']}"
"2019-09-25 15:58:42,736 - data_io.py[line:108] - INFO: start to read dense data and change data to instance"
"2019-09-25 15:58:42,747 - task_executor.py[line:123] - ERROR: Count of data_instance is 0"
Traceback (most recent call last):
  File "/home/yuwen/repo/github/FATE/fate_flow/driver/task_executor.py", line 112, in run_task
    run_object.run(parameters, task_run_args)
  File "/home/yuwen/repo/github/FATE/federatedml/model_base.py", line 188, in run
    self._run_data(args["data"], stage)
  File "/home/yuwen/repo/github/FATE/federatedml/model_base.py", line 161, in _run_data
    self.data_output = self.transform(data)
  File "/home/yuwen/repo/github/FATE/federatedml/util/data_io.py", line 741, in transform
    return self.reader.read_data(data_inst, "transform")
  File "/home/yuwen/repo/github/FATE/federatedml/util/data_io.py", line 110, in read_data
    abnormal_detection.empty_table_detection(input_data)
  File "/home/yuwen/repo/github/FATE/federatedml/util/abnormal_detection.py", line 25, in empty_table_detection
    raise ValueError("Count of data_instance is 0")
ValueError: Count of data_instance is 0
"2019-09-25 15:58:42,747 - api_utils.py[line:70] - INFO: local api request: http://30.54.206.135:9380/v1/schedule/201909251558362437256/dataio_1/201909251558362437256_dataio_1/host/10000/status"
"2019-09-25 15:58:42,917 - api_utils.py[line:73] - INFO: {"data":null,"jobId":null,"meta":null,"retcode":0,"retmsg":"success"}
"
"2019-09-25 15:58:42,917 - api_utils.py[line:75] - INFO: local api response: /v1/schedule/201909251558362437256/dataio_1/201909251558362437256_dataio_1/host/10000/status {'data': None, 'jobId': None, 'meta': None, 'retcode': 0, 'retmsg': 'success'}"
"2019-09-25 15:58:42,917 - task_executor.py[line:137] - INFO: finish 201909251558362437256 dataio_1 201909251558362437256_dataio_1 host 10000 failed task"
```

It seems like input data is empty, but `dataio_0` do have output data successfully, so can you help me?

**Comment by hi-hi-there** [comment]
hello! could you include your quick_run.py code? I suspect the problem lies in the "submit_job" function

**Comment by mgqa34** [comment]
@usafchn Dataio_0  not passes data to dataio_1, it only passes model to dataio_1, so you should also upload dataio_1's data.

**Comment by usafchn** [comment]
@mgqa34 thanks, I solved this problem

**Comment by 4Details** [comment]
hello~ I have met the same problem, Could you tell me how to solve this problem.

**Comment by usafchn** [comment]
@4Details   example 中默认的 DSL 定义有问题，节点`dataio_1`只有模型输入，没有数据输入，改一下 DSL 配置就行了
