### ISSUE TITLE
fate_flow :service not running

### ISSUE THREAD

**Issue by lichaoliang1** [FederatedAI/FATE#768]
**cluster-deply**
 when I run the command "sh services.sh all start" , the log shows the fate_flow service start sucessfully,but when I run the command "sh services.sh all status" ,the log shows the fate_flow service not running.
**how should i do ？**
ps :"fate_flow_stat.log" shows only "init mysql database on cluster mode successfully".  "logs/error.log" shows the following message:
```
 Traceback (most recent call last):
  File "fate_flow_server.py", line 31, in <module>
    from fate_flow.apps.data_access_app import manager as data_access_app_manager
  File "/data/projects/fate/python/fate_flow/apps/data_access_app.py", line 21, in <module>
    from fate_flow.settings import stat_logger
  File "/data/projects/fate/python/fate_flow/settings.py", line 92, in <module>
    RuntimeConfig.init_config(HTTP_PORT=HTTP_PORT)
  File "/data/projects/fate/python/fate_flow/entity/runtime_config.py", line 33, in init_config
    setattr(RuntimeConfig, 'JOB_SERVER_HOST', "{}:{}".format(get_lan_ip(), RuntimeConfig.HTTP_PORT))
  File "/data/projects/fate/python/arch/api/utils/core.py", line 90, in get_lan_ip
    ip = socket.gethostbyname(socket.getfqdn())
socket.gaierror: [Errno -2] Name or service not known
```

**Comment by zhihuiwan** [comment]
Please refer to the documentation: 
https://blog.csdn.net/qiaokelinaicha/article/details/69211983
