### ISSUE TITLE
Quick Start-Cluster Version，task failed

### ISSUE THREAD

**Issue by lichaoliang1** [FederatedAI/FATE#773]
In the host party,I run this command:   python quick_run.py -r host
In the guest party,I run the command:  python quick_run.py -r guest
The in the logs file ,I find the following message,How should I do?
`"2019-11-13 03:37:06,755 - dag_scheduler.py[line:60] - ERROR: there are no components in dsl, please have a check!"
Traceback (most recent call last):
  File "/data/projects/fate/python/fate_flow/driver/dag_scheduler.py", line 58, in handle_event
    return TaskScheduler.run_job(**job_event)
  File "/data/projects/fate/python/fate_flow/driver/task_scheduler.py", line 74, in run_job
    train_runtime_conf=train_runtime_conf)
  File "/data/projects/fate/python/fate_flow/utils/job_utils.py", line 162, in get_job_dsl_parser
    mode=job_type)
  File "/data/projects/fate/python/fate_flow/driver/dsl_parser.py", line 632, in run
    self._init_components(pipeline_dsl, mode)
  File "/data/projects/fate/python/fate_flow/driver/dsl_parser.py", line 113, in _init_components
    raise ValueError("there are no components in dsl, please have a check!")
ValueError: there are no components in dsl, please have a check!
`

**Comment by dylan-fan** [comment]
Now you can not submit task in host

**Comment by yongrl** [comment]
I have the same Error when  I run min_test_task, @dylan-fan  Can explain these problem more detailed? Thank you very much！
