### ISSUE TITLE
 ERROR: <_Rendezvous of RPC that terminated with: status = StatusCode.INTERNAL

### ISSUE THREAD

**Issue by vivianwky** [FederatedAI/FATE#852]
I am using the cluster version FATE on the Centos 7 OS. I have already successfully passed the toy_example test and min test in both the fast and normal mode.
 When I was trying to use the quick_run.py to run the secureboost example, I successfully completed the train task but failed in the predict task.  
There was no error.log in the eggroll logs but an error.log in logs/fate_flow.  You can see the ERROR.log and the fate_flow ERROR.log in the attachments.
Actually, **I have seen the same error message** when I run the toy_example test and min test. And it seems that once this error occurs, whatever test I run the system will report the same error. 
I have checked the netstat and the status of the service and there reports no error.  Also, I have restarted the service several times but it doesn't help.
I wonder whether anyone can help me locate the problem or solve this problem, thank you so much.

The ERROR message are as follows:
ERROR.log
[ERROR.log](https://github.com/FederatedAI/FATE/files/3965842/ERROR.log)

fate_flow  ERROR.log
[fate_flow_ERROR.log](https://github.com/FederatedAI/FATE/files/3965843/fate_flow_ERROR.log)

The netstat on both sides are as follows:
![netstat](https://user-images.githubusercontent.com/48935149/70875580-5ad96f00-1ff1-11ea-88ad-368b68b4600a.png)

**Comment by Ukyo317** [comment]
I have met the same problem, could anyone give us a hand?

**Comment by linjieccc** [comment]
I have met the same problem using docker deployment.
Version: FATE 1.1.1

**Comment by xuexianju** [comment]
Same too. It cost me almost two days to handle it . All container needed is UP. Still got:

stdout:{
    "data": {
        "board_url": "http://fateboard:8080/index.html#/dashboard?job_id=201912190250066120611&role=guest&party_id=10000",
        "job_dsl_path": "/data/projects/fate/python/jobs/201912190250066120611/job_dsl.json",
        "job_runtime_conf_path": "/data/projects/fate/python/jobs/201912190250066120611/job_runtime_conf.json",
        "logs_directory": "/data/projects/fate/python/logs/201912190250066120611",
        "model_info": {
            "model_id": "guest-10000#host-9999#model",
            "model_version": "201912190250066120611"
        }
    },
    "jobId": "201912190250066120611",
    "retcode": 0,
    "retmsg": "success"
}


job status is running
job status is running
"2019-12-19 02:50:13,175 - task_executor.py[line:127] - ERROR: <_Rendezvous of RPC that terminated with:
status = StatusCode.INTERNAL
details = "172.22.0.8:8011: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
at com.webank.ai.eggroll.framework.roll.api.grpc.client.StorageServiceClient.get(StorageServiceClient.java:223)
at com.webank.ai.eggroll.framework.roll.api.grpc.server.RollKvServiceImpl.lambda$get$5(RollKvServiceImpl.java:240)
at com.webank.ai.eggroll.core.api.grpc.server.GrpcServerWrapper.wrapGrpcServerRunnable(GrpcServerWrapper.java:52)
at com.webank.ai.eggroll.framework.roll.api.grpc.server.RollKvServiceImpl.get(RollKvServiceImpl.java:235)
at com.webank.ai.eggroll.api.storage.KVServiceGrpc$MethodHandlers.invoke(KVServiceGrpc.java:959)
at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)
at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283)
at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:710)
at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
at com.webank.ai.eggroll.core.api.grpc.client.GrpcStreamingClientTemplate.calleeStreamingRpcWithImmediateDelayedResult(GrpcStreamingClientTemplate.java:154)
at com.webank.ai.eggroll.framework.roll.api.grpc.client.StorageServiceClient.get(StorageServiceClient.java:219)
... 16 more
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
at io.grpc.Status.asRuntimeException(Status.java:526)
at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:434)
at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:678)
at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397)
at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
... 5 more
Caused by: io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: egg/172.22.0.6:7778
at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
at io.grpc.netty.shaded.io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
at io.grpc.netty.shaded.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:632)
at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
... 1 more
Caused by: java.net.ConnectException: Connection refused
... 11 more
"

**Comment by itboyljm** [comment]
> I am using the cluster version FATE on the Centos 7 OS. I have already successfully passed the toy_example test and min test in both the fast and normal mode.
> When I was trying to use the quick_run.py to run the secureboost example, I successfully completed the train task but failed in the predict task.
> There was no error.log in the eggroll logs but an error.log in logs/fate_flow. You can see the ERROR.log and the fate_flow ERROR.log in the attachments.
> Actually, **I have seen the same error message** when I run the toy_example test and min test. And it seems that once this error occurs, whatever test I run the system will report the same error.
> I have checked the netstat and the status of the service and there reports no error. Also, I have restarted the service several times but it doesn't help.
> I wonder whether anyone can help me locate the problem or solve this problem, thank you so much.
> 
> The ERROR message are as follows:
> ERROR.log
> [ERROR.log](https://github.com/FederatedAI/FATE/files/3965842/ERROR.log)
> 
> fate_flow ERROR.log
> [fate_flow_ERROR.log](https://github.com/FederatedAI/FATE/files/3965843/fate_flow_ERROR.log)
> 
> The netstat on both sides are as follows:
> ![netstat](https://user-images.githubusercontent.com/48935149/70875580-5ad96f00-1ff1-11ea-88ad-368b68b4600a.png)

![image](https://user-images.githubusercontent.com/9403585/71142896-b86cf600-2253-11ea-81f0-db3ebfa99d2c.png)
I checked the logs and found msg "connection refused". The IP: "egg/172.22.0.6" is not a pure IP, could you please have a check if it is attachable？

**Comment by vivianwky** [comment]
> I am using the cluster version FATE on the Centos 7 OS. I have already successfully passed the toy_example test and min test in both the fast and normal mode.
> When I was trying to use the quick_run.py to run the secureboost example, I successfully completed the train task but failed in the predict task.
> There was no error.log in the eggroll logs but an error.log in logs/fate_flow. You can see the ERROR.log and the fate_flow ERROR.log in the attachments.
> Actually, I have seen the same error message when I run the toy_example test and min test. And it seems that once this error occurs, whatever test I run the system will report the same error.
> I have checked the netstat and the status of the service and there reports no error. Also, I have restarted the service several times but it doesn't help.
> I wonder whether anyone can help me locate the problem or solve this problem, thank you so much.
> The ERROR message are as follows:
> ERROR.log
> ERROR.log
> fate_flow ERROR.log
> fate_flow_ERROR.log
> The netstat on both sides are as follows:
> 
> 
> 
> I checked the logs and found msg "connection refused". The IP: "egg/172.22.0.6" is not a pure IP, could you please have a check if it is attachable？

I have checked the status of egg using commad "sh service.sh egg status" and it was on.  Then I ping 172.22.0.6 but there was just no response, not showing timeout or anything .  I wonder if this means it is not attachable or what should I do next?

**Comment by itboyljm** [comment]
> > I am using the cluster version FATE on the Centos 7 OS. I have already successfully passed the toy_example test and min test in both the fast and normal mode.
> > When I was trying to use the quick_run.py to run the secureboost example, I successfully completed the train task but failed in the predict task.
> > There was no error.log in the eggroll logs but an error.log in logs/fate_flow. You can see the ERROR.log and the fate_flow ERROR.log in the attachments.
> > Actually, I have seen the same error message when I run the toy_example test and min test. And it seems that once this error occurs, whatever test I run the system will report the same error.
> > I have checked the netstat and the status of the service and there reports no error. Also, I have restarted the service several times but it doesn't help.
> > I wonder whether anyone can help me locate the problem or solve this problem, thank you so much.
> > The ERROR message are as follows:
> > ERROR.log
> > ERROR.log
> > fate_flow ERROR.log
> > fate_flow_ERROR.log
> > The netstat on both sides are as follows:
> > I checked the logs and found msg "connection refused". The IP: "egg/172.22.0.6" is not a pure IP, could you please have a check if it is attachable？
> 
> I have checked the status of egg using commad "sh service.sh egg status" and it was on. Then I ping 172.22.0.6 but there was just no response, not showing timeout or anything . I wonder if this means it is not attachable or what should I do next?
Maybe you should ping egg/172.22.0.6, not only 172.22.0.6. Because if you are using kubeFATE, IP addr may as follow: egg/172.22.0.6.

**Comment by vivianwky** [comment]
> I am using the cluster version FATE on the Centos 7 OS. I have already successfully passed the toy_example test and min test in both the fast and normal mode.
> When I was trying to use the quick_run.py to run the secureboost example, I successfully completed the train task but failed in the predict task.
> There was no error.log in the eggroll logs but an error.log in logs/fate_flow. You can see the ERROR.log and the fate_flow ERROR.log in the attachments.
> Actually, I have seen the same error message when I run the toy_example test and min test. And it seems that once this error occurs, whatever test I run the system will report the same error.
> I have checked the netstat and the status of the service and there reports no error. Also, I have restarted the service several times but it doesn't help.
> I wonder whether anyone can help me locate the problem or solve this problem, thank you so much.
> The ERROR message are as follows:
> ERROR.log
> ERROR.log
> fate_flow ERROR.log
> fate_flow_ERROR.log
> The netstat on both sides are as follows:
> I checked the logs and found msg "connection refused". The IP: "egg/172.22.0.6" is not a pure IP, could you please have a check if it is attachable？
> 
> I have checked the status of egg using commad "sh service.sh egg status" and it was on. Then I ping 172.22.0.6 but there was just no response, not showing timeout or anything . I wonder if this means it is not attachable or what should I do next?
> Reply sorry late. Maybe you should ping egg/172.22.0.6, not only 172.22.0.6. Because if you are using kubeFATE, IP addr may as follow: egg/172.22.0.6.

I have tired the command ping egg/172.22.0.6 and I get the following information:
ping: egg/172.22.0.6: Unknown name or service.

**Comment by vivianwky** [comment]
> I am using the cluster version FATE on the Centos 7 OS. I have already successfully passed the toy_example test and min test in both the fast and normal mode.
> When I was trying to use the quick_run.py to run the secureboost example, I successfully completed the train task but failed in the predict task.
> There was no error.log in the eggroll logs but an error.log in logs/fate_flow. You can see the ERROR.log and the fate_flow ERROR.log in the attachments.
> Actually, I have seen the same error message when I run the toy_example test and min test. And it seems that once this error occurs, whatever test I run the system will report the same error.
> I have checked the netstat and the status of the service and there reports no error. Also, I have restarted the service several times but it doesn't help.
> I wonder whether anyone can help me locate the problem or solve this problem, thank you so much.
> The ERROR message are as follows:
> ERROR.log
> ERROR.log
> fate_flow ERROR.log
> fate_flow_ERROR.log
> The netstat on both sides are as follows:
> I checked the logs and found msg "connection refused". The IP: "egg/172.22.0.6" is not a pure IP, could you please have a check if it is attachable？
> 
> I have checked the status of egg using commad "sh service.sh egg status" and it was on. Then I ping 172.22.0.6 but there was just no response, not showing timeout or anything . I wonder if this means it is not attachable or what should I do next?
> Reply sorry late. Maybe you should ping egg/172.22.0.6, not only 172.22.0.6. Because if you are using kubeFATE, IP addr may as follow: egg/172.22.0.6.

I have checked my logs that I attached at the beginning and I am sure there is no message like: connection refused: egg/172.22.0.6 . Maybe you have seen it in other people's comments not the logs I attached. Could you please check the logs again and help me locate this problem?

**Comment by RicLee0124** [comment]
I have got the same problem and solved the problem，I updated  egg.properties(filePath: /data/projects/fate/eggroll/egg/conf/egg.properties),transfer edeggroll.computing.processor.session.max.count=16 to eggroll.computing.processor.session.max.count=2.  restarted  all the services, in the end, it worked!!!

**Comment by vivianwky** [comment]
> I have got the same problem and solved the problem，I updated  egg.properties(filePath: /data/projects/fate/eggroll/egg/conf/egg.properties),transfer edeggroll.computing.processor.session.max.count=16 to eggroll.computing.processor.session.max.count=2.  restarted  all the services, in the end, it worked!!!

I have also changed the edeggroll.computing.processor.session.max.count to the number of cpus of my computer  and it also works.  I think this is the right solution. Thanks for your reply!

**Comment by youngquan** [comment]
@RicLee0124 
Could you explain why this configuration `edeggroll.computing.processor.session.max.count` should be changed to 2 ? Is this a bug or something ?

**Comment by novaxiaohui** [comment]
I met the same issue. And I find egg.properties in path /date/projects/confs-10000/confs/egg/conf ,But the  edeggroll.computing.processor.session.max.count  is already set 2 . Anybody have another  solution?

**Comment by slowlyswimming** [comment]
I met the same issue, too. My FATE version is 1.3.0. I modified the edeggroll.computing.processor.session.max.count to my CPU number, which is 4 under the folder /date/projects/confs-10000/confs/egg/conf as @novaxiaohui suggested, but the "connection refused" error still exists.

**Comment by wanggc2019** [comment]
> I have got the same problem and solved the problem，I updated egg.properties(filePath: /data/projects/fate/eggroll/egg/conf/egg.properties),transfer edeggroll.computing.processor.session.max.count=16 to eggroll.computing.processor.session.max.count=2. restarted all the services, in the end, it worked!!!

what fate version? my fate is 1.4.4 and i not find eggroll.computing.processor.session.max.count
