### ISSUE TITLE
can't run job in 1.2

### ISSUE THREAD

**Issue by cometta** [FederatedAI/FATE#927]
First, i have no issue to run a job on a cluster mode for 1.1 . For 1.2, I able to run a job on a single machine  (guest and host on the same machine). However, when host and guest are on different machines, i get below error in egg log.

```

 [ERROR] 2020-01-08T07:39:32,907 [grpcServiceExecutor-9] [GrpcServerWrapper:54] - java.lang.IllegalStateException: sessionId 202001080739241686922_dataio_0_guest_10000 does not exist
	at com.webank.ai.eggroll.framework.egg.manager.EggSessionManager.getComputeEngine(EggSessionManager.java:163)
	at com.webank.ai.eggroll.framework.egg.api.grpc.server.EggSessionServiceImpl.lambda$getComputingEngine$2(EggSessionServiceImpl.java:72)
	at com.webank.ai.eggroll.core.api.grpc.server.GrpcServerWrapper.wrapGrpcServerRunnable(GrpcServerWrapper.java:52)
	at com.webank.ai.eggroll.framework.egg.api.grpc.server.EggSessionServiceImpl.getComputingEngine(EggSessionServiceImpl.java:70)
	at com.webank.ai.eggroll.api.framework.egg.SessionServiceGrpc$MethodHandlers.invoke(SessionServiceGrpc.java:357)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283)



	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:710)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
additional info: 202001080739241686922_dataio_0_guest_10000 folder exist in /data/projects/fate/data-dir/lmdb/ 

Also, i notice the route table is different from 1.1 . On 1.2 , another machine info is inside the route table. On 1.1, the route table shows only info about the exchange server

**Comment by cometta** [comment]
i able to get it running, after making sure egg is running on port 7778
