### ISSUE TITLE
heter_logic_regression failed when use spark backend

### ISSUE THREAD

**Issue by sookieqin** [FederatedAI/FATE#980]
**Describe the bug**
There are two bugs in this situation:
1. an error occurred in dataio stage, and error log is as follows
```
20/02/11 16:24:24 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
process 12465 thread 140369892562752 run __init__ init table name:__gc_e9eeb622-4ca7-11ea-b80d-525400cb55fa, namespace:e9eeb622-4ca7-11ea-b80d-525400cb55fa
created table: storage_type: LMDB, namespace: e9eeb622-4ca7-11ea-b80d-525400cb55fa, name: __gc_e9eeb622-4ca7-11ea-b80d-525400cb55fa, partitions: 1, in_place_computing: False
Traceback (most recent call last):
  File "/data/projects/fate/python/fate_flow/driver/task_executor.py", line 79, in run_task
    session.init(job_id='{}_{}_{}'.format(task_id, role, party_id), mode=RuntimeConfig.WORK_MODE, backend=RuntimeConfig.BACKEND)
  File "/data/projects/fate/python/arch/api/session.py", line 50, in init
    session = build_session(job_id=job_id, work_mode=mode, backend=backend)
  File "/data/projects/fate/python/arch/api/table/session.py", line 38, in build_session
    session = session_impl.FateSessionImpl(eggroll_session, work_mode)
  File "/data/projects/fate/python/arch/api/table/pyspark/session_impl.py", line 38, in __init__
    eggroll_util.broadcast_eggroll_session(self._sc, work_mode, eggroll_session)
  File "/data/projects/fate/python/arch/api/table/eggroll_util.py", line 50, in broadcast_eggroll_session
    pickled_client = pickle.dumps((work_mode.value, eggroll_session)).hex()
  File "stringsource", line 2, in grpc._cython.cygrpc.Channel.__reduce_cython__
TypeError: no default __reduce__ due to non-trivial __cinit__
Traceback (most recent call last):
  File "/data/projects/fate/python/fate_flow/driver/task_executor.py", line 132, in run_task
    session.stop()
  File "/data/projects/fate/python/arch/api/session.py", line 179, in stop
    RuntimeInstance.SESSION.stop()
AttributeError: 'NoneType' object has no attribute 'stop'
finish 202002111624222006152 dataio_0 202002111624222006152_dataio_0 host 10000 failed task
```
2. job status in fateboard was remaining running after the error occurred in both guest and host.

**job_parameters config**
```
"job_parameters": {
    "work_mode": 1,
    "backend": 1,
    "spark_submit_config": {
        "driver-memory": "1g",
        "num-executors": 10,
        "executor-memory": "1g",
        "executor-cores": 1
    }
  }
```

**Comment by sookieqin** [comment]
After we update version to Release 1.2.0, the error changed, details as follows:
```
1
"2020-02-25 22:47:38,212 - task_executor.py[line:132] - ERROR: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.
2
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 2.0 failed 1 times, most recent failure: Lost task 1.0 in stage 2.0 (TID 21, localhost, executor driver): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
3
File "/usr/local/service/spark/python/lib/pyspark.zip/pyspark/worker.py", line 253, in main
4
process()
5
File "/usr/local/service/spark/python/lib/pyspark.zip/pyspark/worker.py", line 248, in process
6
serializer.dump_stream(func(split_index, iterator), outfile)
7
File "/data/projects/fate/python/arch/api/table/pyspark/rdd_func.py", line 30, in _func
8
eggroll_util.maybe_create_eggroll_client()
9
File "/data/projects/fate/python/arch/api/table/eggroll_util.py", line 63, in maybe_create_eggroll_client
10
mode, eggroll_session = pickle.loads(bytes.fromhex(TaskContext.get().getLocalProperty(_EGGROLL_CLIENT)))
11
AttributeError: 'TaskContext' object has no attribute 'getLocalProperty'
12
13
at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:330)
14
at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRunner.scala:470)
15
at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRunner.scala:453)
16
at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:284)
17
at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
18
at scala.collection.Iterator$class.foreach(Iterator.scala:893)
19
at org.apache.spark.InterruptibleIterator.foreach(InterruptibleIterator.scala:28)
20
at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
21
at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:104)
22
at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:48)
23
at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
24
at org.apache.spark.InterruptibleIterator.to(InterruptibleIterator.scala:28)
25
at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:302)
26
at org.apache.spark.InterruptibleIterator.toBuffer(InterruptibleIterator.scala:28)
27
at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:289)
28
at org.apache.spark.InterruptibleIterator.toArray(InterruptibleIterator.scala:28)
29
at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$12.apply(RDD.scala:945)
30
at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$12.apply(RDD.scala:945)
31
at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2074)
32
at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2074)
33
at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
34
at org.apache.spark.scheduler.Task.run(Task.scala:109)
35
at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
36
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
37
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
38
at java.lang.Thread.run(Thread.java:748)
39
40
Driver stacktrace:
41
at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1651)
42
at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1639)
43
at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1638)
44
at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
45
at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
46
at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1638)
47
at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:831)
48
at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:831)
49
at scala.Option.foreach(Option.scala:257)
50
at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:831)
51
at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1872)
52
at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1821)
53
at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1810)
54
at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
55
at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:642)
56
at org.apache.spark.SparkContext.runJob(SparkContext.scala:2034)
57
at org.apache.spark.SparkContext.runJob(SparkContext.scala:2055)
58
at org.apache.spark.SparkContext.runJob(SparkContext.scala:2074)
59
at org.apache.spark.SparkContext.runJob(SparkContext.scala:2099)
60
at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:945)
61
at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
62
at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
63
at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
64
at org.apache.spark.rdd.RDD.collect(RDD.scala:944)
65
at org.apache.spark.api.python.PythonRDD$.collectAndServe(PythonRDD.scala:165)
66
at org.apache.spark.api.python.PythonRDD.collectAndServe(PythonRDD.scala)
67
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
68
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
69
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
70
at java.lang.reflect.Method.invoke(Method.java:498)
71
at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
72
at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
73
at py4j.Gateway.invoke(Gateway.java:282)
74
at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
75
at py4j.commands.CallCommand.execute(CallCommand.java:79)
76
at py4j.GatewayConnection.run(GatewayConnection.java:238)
77
at java.lang.Thread.run(Thread.java:748)
78
Caused by: org.apache.spark.api.python.PythonException: Traceback (most recent call last):
79
File "/usr/local/service/spark/python/lib/pyspark.zip/pyspark/worker.py", line 253, in main
80
process()
81
File "/usr/local/service/spark/python/lib/pyspark.zip/pyspark/worker.py", line 248, in process
82
serializer.dump_stream(func(split_index, iterator), outfile)
83
File "/data/projects/fate/python/arch/api/table/pyspark/rdd_func.py", line 30, in _func
84
eggroll_util.maybe_create_eggroll_client()
85
File "/data/projects/fate/python/arch/api/table/eggroll_util.py", line 63, in maybe_create_eggroll_client
86
mode, eggroll_session = pickle.loads(bytes.fromhex(TaskContext.get().getLocalProperty(_EGGROLL_CLIENT)))
87
AttributeError: 'TaskContext' object has no attribute 'getLocalProperty'
88
89
at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:330)
90
at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRunner.scala:470)
91
at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRunner.scala:453)
92
at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:284)
93
at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
94
at scala.collection.Iterator$class.foreach(Iterator.scala:893)
95
at org.apache.spark.InterruptibleIterator.foreach(InterruptibleIterator.scala:28)
96
at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
97
at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:104)
98
at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:48)
99
at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
100
at org.apache.spark.InterruptibleIterator.to(InterruptibleIterator.scala:28)
101
at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:302)
102
at org.apache.spark.InterruptibleIterator.toBuffer(InterruptibleIterator.scala:28)
103
at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:289)
104
at org.apache.spark.InterruptibleIterator.toArray(InterruptibleIterator.scala:28)
105
at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$12.apply(RDD.scala:945)
106
at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$12.apply(RDD.scala:945)
107
at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2074)
108
at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2074)
109
at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
110
at org.apache.spark.scheduler.Task.run(Task.scala:109)
111
at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
112
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
113
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
114
... 1 more
115
"
116
Traceback (most recent call last):
117
File "/data/projects/fate/python/fate_flow/driver/task_executor.py", line 125, in run_task
118
tracker.save_output_data_table(output_data, task_output_dsl.get('data')[0] if task_output_dsl.get('data') else 'component')
119
File "/data/projects/fate/python/fate_flow/manager/tracking.py", line 179, in save_output_data_table
120
name='{}_persistent'.format(data_table._name))
121
File "/data/projects/fate/python/arch/api/utils/profile_util.py", line 31, in _fn
122
rtn = func(*args, **kwargs)
123
File "/data/projects/fate/python/arch/api/table/pyspark/table_impl.py", line 287, in save_as
124
return _save_as_func(self._rdd, name=name, namespace=namespace, partition=partition, persistent=persistent)
125
File "/data/projects/fate/python/arch/api/table/pyspark/rdd_func.py", line 34, in _save_as_func
126
rdd.mapPartitionsWithIndex(_func, preservesPartitioning=False).collect()
127
File "/usr/local/service/spark/python/lib/pyspark.zip/pyspark/rdd.py", line 814, in collect
128
sock_info = self.ctx._jvm.PythonRDD.collectAndServe(self._jrdd.rdd())
129
File "/usr/local/service/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
130
answer, self.gateway_client, self.target_id, self.name)
131
File "/usr/local/service/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
132
format(target_id, ".", name), value)
133
py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.
134
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 2.0 failed 1 times, most recent failure: Lost task 1.0 in stage 2.0 (TID 21, localhost, executor driver): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
135
File "/usr/local/service/spark/python/lib/pyspark.zip/pyspark/worker.py", line 253, in main
136
process()
137
File "/usr/local/service/spark/python/lib/pyspark.zip/pyspark/worker.py", line 248, in process
138
serializer.dump_stream(func(split_index, iterator), outfile)
139
File "/data/projects/fate/python/arch/api/table/pyspark/rdd_func.py", line 30, in _func
140
eggroll_util.maybe_create_eggroll_client()
141
File "/data/projects/fate/python/arch/api/table/eggroll_util.py", line 63, in maybe_create_eggroll_client
142
mode, eggroll_session = pickle.loads(bytes.fromhex(TaskContext.get().getLocalProperty(_EGGROLL_CLIENT)))
143
AttributeError: 'TaskContext' object has no attribute 'getLocalProperty'
144
145
at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:330)
146
at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRunner.scala:470)
147
at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRunner.scala:453)
148
at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:284)
149
at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
150
at scala.collection.Iterator$class.foreach(Iterator.scala:893)
151
at org.apache.spark.InterruptibleIterator.foreach(InterruptibleIterator.scala:28)
152
at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
153
at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:104)
154
at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:48)
155
at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
156
at org.apache.spark.InterruptibleIterator.to(InterruptibleIterator.scala:28)
157
at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:302)
158
at org.apache.spark.InterruptibleIterator.toBuffer(InterruptibleIterator.scala:28)
159
at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:289)
160
at org.apache.spark.InterruptibleIterator.toArray(InterruptibleIterator.scala:28)
161
at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$12.apply(RDD.scala:945)
162
at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$12.apply(RDD.scala:945)
163
at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2074)
164
at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2074)
165
at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
166
at org.apache.spark.scheduler.Task.run(Task.scala:109)
167
at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
168
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
169
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
170
at java.lang.Thread.run(Thread.java:748)
171
172
Driver stacktrace:
173
at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1651)
174
at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1639)
175
at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1638)
176
at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
177
at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
178
at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1638)
179
at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:831)
180
at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:831)
181
at scala.Option.foreach(Option.scala:257)
182
at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:831)
183
at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1872)
184
at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1821)
185
at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1810)
186
at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
187
at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:642)
188
at org.apache.spark.SparkContext.runJob(SparkContext.scala:2034)
189
at org.apache.spark.SparkContext.runJob(SparkContext.scala:2055)
190
at org.apache.spark.SparkContext.runJob(SparkContext.scala:2074)
191
at org.apache.spark.SparkContext.runJob(SparkContext.scala:2099)
192
at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:945)
193
at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
194
at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
195
at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
196
at org.apache.spark.rdd.RDD.collect(RDD.scala:944)
197
at org.apache.spark.api.python.PythonRDD$.collectAndServe(PythonRDD.scala:165)
198
at org.apache.spark.api.python.PythonRDD.collectAndServe(PythonRDD.scala)
199
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
200
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
201
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
202
at java.lang.reflect.Method.invoke(Method.java:498)
203
at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
204
at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
205
at py4j.Gateway.invoke(Gateway.java:282)
206
at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
207
at py4j.commands.CallCommand.execute(CallCommand.java:79)
208
at py4j.GatewayConnection.run(GatewayConnection.java:238)
209
at java.lang.Thread.run(Thread.java:748)
210
Caused by: org.apache.spark.api.python.PythonException: Traceback (most recent call last):
211
File "/usr/local/service/spark/python/lib/pyspark.zip/pyspark/worker.py", line 253, in main
212
process()
213
File "/usr/local/service/spark/python/lib/pyspark.zip/pyspark/worker.py", line 248, in process
214
serializer.dump_stream(func(split_index, iterator), outfile)
215
File "/data/projects/fate/python/arch/api/table/pyspark/rdd_func.py", line 30, in _func
216
eggroll_util.maybe_create_eggroll_client()
217
File "/data/projects/fate/python/arch/api/table/eggroll_util.py", line 63, in maybe_create_eggroll_client
218
mode, eggroll_session = pickle.loads(bytes.fromhex(TaskContext.get().getLocalProperty(_EGGROLL_CLIENT)))
219
AttributeError: 'TaskContext' object has no attribute 'getLocalProperty'
220
221
at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:330)
222
at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRunner.scala:470)
223
at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRunner.scala:453)
224
at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:284)
225
at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
226
at scala.collection.Iterator$class.foreach(Iterator.scala:893)
227
at org.apache.spark.InterruptibleIterator.foreach(InterruptibleIterator.scala:28)
228
at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
229
at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:104)
230
at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:48)
231
at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
232
at org.apache.spark.InterruptibleIterator.to(InterruptibleIterator.scala:28)
233
at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:302)
234
at org.apache.spark.InterruptibleIterator.toBuffer(InterruptibleIterator.scala:28)
235
at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:289)
236
at org.apache.spark.InterruptibleIterator.toArray(InterruptibleIterator.scala:28)
237
at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$12.apply(RDD.scala:945)
238
at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$12.apply(RDD.scala:945)
239
at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2074)
240
at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2074)
241
at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
242
at org.apache.spark.scheduler.Task.run(Task.scala:109)
243
at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
244
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
245
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
246
... 1 more
```

**Comment by weiwee** [comment]
This msg: indicate that you are using spark version under 2.4: "AttributeError: 'TaskContext' object has no attribute 'getLocalProperty'" , which is not supported or tested

**Comment by weiwee** [comment]
I'm closing issue now, please reopen this if issue not resolved
