### ISSUE TITLE
Run standalone deploy failed with WSL

### ISSUE THREAD

**Issue by linkerzhang** [FederatedAI/FATE#997]
**Describe the bug**
Running standalone deploy with WSL failed.

**To Reproduce**
In windows 10 enterprise, with WSL, following https://github.com/FederatedAI/FATE/tree/master/standalone-deploy#1-install-fate-using-dockerrecommended to run the standalone deploy and get failures as,

1. "fate_python" container can't be run successfully. It has to be started in windows manually.
2. "fate_board" has failures on running sql queries - "no t_job table".

Is there anyone trying to run FATE in WSL please? Thank you!

**Comment by KathyKing** [comment]
WSL has not been tested yet. Whether it can be supported requires internal testing

Can give detailed error report

**Comment by linkerzhang** [comment]
Thanks @KathyKing for the follow-up!

Following the https://github.com/FederatedAI/FATE/tree/master/standalone-deploy#1-install-fate-using-dockerrecommended in WSL is having the errors as:
1. Failed to run the fate_python container
Error message: python: can't open file 'fate_flow_server.py': [Errno 2] No such file or directory.
I have to delete this container and start the run fate_python image manually.
2. The fate_board container looks to be running good, but the log shows error message as:
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

at java.lang.Thread.run(Thread.java:748)

Caused by: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: t_job)

at org.sqlite.core.DB.newSQLException(DB.java:941)

at org.sqlite.core.DB.newSQLException(DB.java:953)

at org.sqlite.core.DB.throwex(DB.java:918)

at org.sqlite.core.NativeDB.prepare_utf8(Native Method)

at org.sqlite.core.NativeDB.prepare(NativeDB.java:134)

at org.sqlite.core.DB.prepare(DB.java:257)

at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:47)

at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)

at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:19)

at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35)

at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241)

at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)

Let me know if more information needed.

My environment is: windows 10 enterprise / WSL, Docker version 18.09.7, build 2d0083d.

**Comment by KathyKing** [comment]
WSL has not been tested yet

**Comment by linkerzhang** [comment]
is there a plan to have support/test against WSL please?
